const BENGALI = {
	"footer": "Write the Latin transliteration of the given Bengali letter.",
	"sets": [
    { "letter": "অ, -, ক", "answers": ["ô", "o"] },
    { "letter": "ই, ি, কি", "answers": ["i"] },
    { "letter": "উ, ু, কু", "answers": ["u"] },
    { "letter": "ঋ, ৃ, কৃ", "answers": ["ṛ", "ri"] },
    { "letter": "ঌ, ৢ, কৢ", "answers": ["ḷ", "li"] },
    { "letter": "এ, ে, কে", "answers": ["e"] },
    { "letter": "ও, ো, কো", "answers": ["o"] },
    { "letter": "আ, া, কা", "answers": ["a"] },
    { "letter": "ঈ, ী, কী", "answers": ["ī", "ee", "ii"] },
    { "letter": "ঊ, ূ, কূ", "answers": ["ū", "oo", "uu"] },
    { "letter": "ৠ, ৄ, কৄ", "answers": ["ṝ", "rri"] },
    { "letter": "ৡ, ৣ, কৣ", "answers": ["ḹ", "lli"] },
    { "letter": "ঐ, ৈ, কৈ", "answers": ["oi"] },
    { "letter": "ঔ, ৌ, কৌ", "answers": ["ou"] },
    { "letter": "ক", "answers": ["k"] },
    { "letter": "চ", "answers": ["ch", "s"] },
    { "letter": "ট", "answers": ["t"] },
    { "letter": "ত", "answers": ["t"] },
    { "letter": "প", "answers": ["p"] },
    { "letter": "খ", "answers": ["kh"] },
    { "letter": "ছ", "answers": ["chh", "ss"] },
    { "letter": "ঠ", "answers": ["th"] },
    { "letter": "থ", "answers": ["th"] },
    { "letter": "ফ", "answers": ["ph", "f"] },
    { "letter": "গ", "answers": ["g"] },
    { "letter": "জ", "answers": ["j"] },
    { "letter": "ড", "answers": ["d"] },
    { "letter": "দ", "answers": ["d"] },
    { "letter": "ব", "answers": ["b"] },
    { "letter": "ঘ", "answers": ["gh"] },
    { "letter": "ঝ", "answers": ["jh"] },
    { "letter": "ঢ", "answers": ["dh"] },
    { "letter": "ধ", "answers": ["dh"] },
    { "letter": "ভ", "answers": ["bh", "v"] },
    { "letter": "ঙ", "answers": ["ng"] },
    { "letter": "ঞ", "answers": ["ñ", "n"] },
    { "letter": "ণ", "answers": ["ṇ", "n"] },
    { "letter": "ন", "answers": ["n"] },
    { "letter": "ম", "answers": ["m"] },
    { "letter": "য", "answers": ["j"] },
    { "letter": "র", "answers": ["r"] },
    { "letter": "ল", "answers": ["l"] },
    { "letter": "ব", "answers": ["β", "b"] },
    { "letter": "শ", "answers": ["sh"] },
    { "letter": "ষ", "answers": ["ṣ", "sh"] },
    { "letter": "স", "answers": ["s", "sh"] },
    { "letter": "হ", "answers": ["h"] },
    { "letter": "ড়", "answers": ["ṛ", "r"] },
    { "letter": "ঢ়", "answers": ["ṛh", "r"] },
    { "letter": "য়", "answers": ["y"] },
  ]
};

module.exports = BENGALI;