const BRCITYCODES = {
	"footer": "Write the Brazilian area code the given city is the biggest in.",
	"sets": [
    { "letter": "São Paulo", "answers": ["11"] },
    { "letter": "São Jose dos Campos", "answers": ["12"] },
    { "letter": "Santos", "answers": ["13"] },
    { "letter": "Bauru", "answers": ["14"] },
    { "letter": "Sorocaba", "answers": ["15"] },
    { "letter": "Ribeirão Preto", "answers": ["16"] },
    { "letter": "São José do Rio Preto", "answers": ["17"] },
    { "letter": "Presidente Prudente", "answers": ["18"] },
    { "letter": "Campinas", "answers": ["19"] },
    { "letter": "Rio de Janeiro", "answers": ["21"] },
    { "letter": "Campos dos Goytacazes", "answers": ["22"] },
    { "letter": "Petrópolis", "answers": ["24"] },
    { "letter": "Vitória", "answers": ["27"] },
    { "letter": "Cachoeiro de Itapemirim", "answers": ["28"] },
    { "letter": "Belo Horizonte", "answers": ["31"] },
    { "letter": "Juiz de Fora", "answers": ["32"] },
    { "letter": "Governador Valadares", "answers": ["33"] },
    { "letter": "Uberlândia", "answers": ["34"] },
    { "letter": "Poços de Caldas", "answers": ["35"] },
    { "letter": "Divinópolis", "answers": ["37"] },
    { "letter": "Montes Claros", "answers": ["38"] },
    { "letter": "Curitiba", "answers": ["41"] },
    { "letter": "Ponta Grossa", "answers": ["42"] },
    { "letter": "Londrina", "answers": ["43"] },
    { "letter": "Maringá", "answers": ["44"] },
    { "letter": "Foz do Iguaçu", "answers": ["45"] },
    { "letter": "Francisco Beltrão", "answers": ["46"] },
    { "letter": "Joinville", "answers": ["47"] },
    { "letter": "Florianópolis", "answers": ["48"] },
    { "letter": "Chapecó", "answers": ["49"] },
    { "letter": "Porto Alegre", "answers": ["51"] },
    { "letter": "Pelotas", "answers": ["53"] },
    { "letter": "Caxias do Sul", "answers": ["54"] },
    { "letter": "Santa Maria", "answers": ["55"] },
    { "letter": "Brasília", "answers": ["61"] },
    { "letter": "Goiânia", "answers": ["62"] },
    { "letter": "Rio Verde", "answers": ["64"] },
    { "letter": "Palmas", "answers": ["63"] },
    { "letter": "Cuiabá", "answers": ["65"] },
    { "letter": "Rondonópolis", "answers": ["66"] },
    { "letter": "Campo Grande", "answers": ["67"] },
    { "letter": "Rio Branco", "answers": ["68"] },
    { "letter": "Porto Velho", "answers": ["69"] },
    { "letter": "Salvador", "answers": ["71"] },
    { "letter": "Ilhéus", "answers": ["73"] },
    { "letter": "Juazeiro", "answers": ["74"] },
    { "letter": "Feira de Santana", "answers": ["75"] },
    { "letter": "Vitória da Conquista", "answers": ["77"] },
    { "letter": "Aracaju", "answers": ["79"] },
    { "letter": "Recife", "answers": ["81"] },
    { "letter": "Petrolina", "answers": ["87"] },
    { "letter": "Maceió", "answers": ["82"] },
    { "letter": "João Pessoa", "answers": ["83"] },
    { "letter": "Natal", "answers": ["84"] },
    { "letter": "Fortaleza", "answers": ["85"] },
    { "letter": "Juazeiro do Norte", "answers": ["88"] },
    { "letter": "Teresina", "answers": ["86"] },
    { "letter": "Picos", "answers": ["89"] },
    { "letter": "Belém", "answers": ["91"] },
    { "letter": "Santarém", "answers": ["93"] },
    { "letter": "Marabá", "answers": ["94"] },
    { "letter": "Manaus", "answers": ["92"] },
    { "letter": "Coari", "answers": ["97"] },
    { "letter": "Boa Vista", "answers": ["95"] },
    { "letter": "Macapá", "answers": ["96"] },
    { "letter": "São Luís", "answers": ["98"] },
    { "letter": "Imperatriz", "answers": ["99"] },
  ]
};

module.exports = BRCITYCODES;