const CAMERAS = {
	"footer": "Write the common camera gens in this country.",
	"sets": [
    { "letter": "Albania", "answers": ["3"] },
	{ "letter": "Andorra", "answers": ["23"] },
	{ "letter": "Argentina", "answers": ["34"] },
	{ "letter": "Australia", "answers": ["1234"] },
	{ "letter": "Austria", "answers": ["34"] },
	{ "letter": "Bangladesh", "answers": ["34"] },
	{ "letter": "Belgium", "answers": ["234"] },
	{ "letter": "Bhutan", "answers": ["3"] },
	{ "letter": "Bolivia", "answers": ["3"] },
	{ "letter": "Botswana", "answers": ["3"] },
	{ "letter": "Brazil", "answers": ["34"] },
	{ "letter": "Bulgaria", "answers": ["34"] },
	{ "letter": "Cambodia", "answers": ["3"] },
	{ "letter": "Canada", "answers": ["234"] },
	{ "letter": "Chile", "answers": ["34"] },
	{ "letter": "Colombia", "answers": ["34"] },
	{ "letter": "Dominican Republic", "answers": ["3"] },
	{ "letter": "Ecuador", "answers": ["3"] },
	{ "letter": "Estonia", "answers": ["3"] },
	{ "letter": "Eswatini", "answers": ["3"] },
	{ "letter": "Finland", "answers": ["23"] },
	{ "letter": "France", "answers": ["234"] },
	{ "letter": "Germany", "answers": ["2"] },
	{ "letter": "Ghana", "answers": ["3"] },
	{ "letter": "Greece", "answers": ["234"] },
	{ "letter": "Guatemala", "answers": ["3"] },
	{ "letter": "Hungary", "answers": ["34"] },
	{ "letter": "Iceland", "answers": ["3"] },
	{ "letter": "Indonesia", "answers": ["34"] },
	{ "letter": "Ireland", "answers": ["234"] },
	{ "letter": "Israel", "answers": ["3"] },
	{ "letter": "Italy", "answers": ["234"] },
	{ "letter": "Japan", "answers": ["234"] },
	{ "letter": "Jordan", "answers": ["3"] },
	{ "letter": "Kenya", "answers": ["3"] },
	{ "letter": "Kyrgyzstan", "answers": ["3"] },
	{ "letter": "Laos", "answers": ["3"] },
	{ "letter": "Latvia", "answers": ["3"] },
	{ "letter": "Lesotho", "answers": ["3"] },
	{ "letter": "Lithuania", "answers": ["3"] },
	{ "letter": "Luxembourg", "answers": ["24"] },
	{ "letter": "Malaysia", "answers": ["34"] },
	{ "letter": "Malta", "answers": ["3"] },
	{ "letter": "Mexico", "answers": ["234"] },
	{ "letter": "Monaco", "answers": ["2"] },
	{ "letter": "Mongolia", "answers": ["3"] },
	{ "letter": "Montenegro", "answers": ["3"] },
	{ "letter": "Netherlands", "answers": ["234"] },
	{ "letter": "New Zealand", "answers": ["1234"] },
	{ "letter": "Nigeria", "answers": ["3"] },
	{ "letter": "North Macedonia", "answers": ["3"] },
	{ "letter": "Norway", "answers": ["234"] },
	{ "letter": "Palestine", "answers": ["3"] },
	{ "letter": "Peru", "answers": ["3"] },
	{ "letter": "Philippines", "answers": ["34"] },
	{ "letter": "Poland", "answers": ["34"] },
	{ "letter": "Portugal", "answers": ["234"] },
	{ "letter": "Romania", "answers": ["34"] },
	{ "letter": "Russia", "answers": ["34"] },
	{ "letter": "San Marino", "answers": ["2"] },
	{ "letter": "Senegal", "answers": ["3"] },
	{ "letter": "Serbia", "answers": ["3"] },
	{ "letter": "Singapore", "answers": ["34"] },
	{ "letter": "Slovakia", "answers": ["3"] },
	{ "letter": "Slovenia", "answers": ["3"] },
	{ "letter": "South Africa", "answers": ["234"] },
	{ "letter": "South Korea", "answers": ["3"] },
	{ "letter": "Spain", "answers": ["234"] },
	{ "letter": "Sri Lanka", "answers": ["34"] },
	{ "letter": "Sweden", "answers": ["234"] },
	{ "letter": "Switzerland", "answers": ["3"] },
	{ "letter": "Taiwan", "answers": ["234"] },
	{ "letter": "Thailand", "answers": ["34"] },
	{ "letter": "Tunisia", "answers": ["3"] },
	{ "letter": "Turkey", "answers": ["34"] },
	{ "letter": "Uganda", "answers": ["3"] },
	{ "letter": "Ukraine", "answers": ["3"] },
	{ "letter": "United Arab Emirates", "answers": ["3"] },
	{ "letter": "United Kingdom", "answers": ["234"] },
	{ "letter": "United States", "answers": ["1234"] },
	{ "letter": "Uruguay", "answers": ["3"] },
	{ "letter": "Vietnam", "answers": ["34"] },
	{ "letter": "American Samoa (US)", "answers": ["3"] },
	{ "letter": "Bermuda (UK)", "answers": ["3"] },
	{ "letter": "Christmas/Cocos Islands (AU)", "answers": ["3"] },
	{ "letter": "Curação (NL)", "answers": ["3"] },
	{ "letter": "Faroe Islands (DK)", "answers": ["3"] },
	{ "letter": "Gibraltar (UK)", "answers": ["3"] },
	{ "letter": "Greenland (DK)", "answers": ["3"] },
	{ "letter": "Guam/NMI (US)", "answers": ["3"] },
	{ "letter": "Hong Kong (CN)", "answers": ["234"] },
	{ "letter": "Jersey (UK)", "answers": ["2"] },
	{ "letter": "Isle of Man (UK)", "answers": ["2"] },
	{ "letter": "Macao (CN)", "answers": ["2"] },
	{ "letter": "Puerto Rico (US)", "answers": ["3"] },
	{ "letter": "Réunion (FR)", "answers": ["3"] },
	{ "letter": "US Virgin Islands (US)", "answers": ["3"] },
  ]
};

module.exports = CAMERAS;