const CASHIELDS = {
	"title": "Guess the province",
  "footer": "Write the province the highway shield is from.",
  "sets": [
    { "letter": "https://i.imgur.com/Eou7v1Y.png", "answers": ["Alberta", "AB"] },
	{ "letter": "https://i.imgur.com/9Dwz9qW.png", "answers": ["Alberta", "AB"] },
	{ "letter": "https://i.imgur.com/gGu0aPg.png", "answers": ["British Columbia", "BC"] },
	{ "letter": "https://i.imgur.com/9njkE5x.png", "answers": ["British Columbia", "BC"] },
	{ "letter": "https://i.imgur.com/EcEpUN6.png", "answers": ["Manitoba", "MB"] },
	{ "letter": "https://i.imgur.com/xxZyTCX.png", "answers": ["Manitoba", "MB"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Winnipeg_city_route_90.svg/600px-Winnipeg_city_route_90.svg.png", "answers": ["Manitoba", "MB"] },
	{ "letter": "https://i.imgur.com/DwfughU.png", "answers": ["New Brunswick", "NB"] },
	{ "letter": "https://i.imgur.com/sFnfU8U.png", "answers": ["New Brunswick", "NB"] },
	{ "letter": "https://i.imgur.com/Ly7liE4.png", "answers": ["New Brunswick", "NB"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/NL_Route_2.svg/480px-NL_Route_2.svg.png", "answers": ["New Foundland and Labrador", "Newfoundland", "NL"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Nova_Scotia_4.svg/480px-Nova_Scotia_4.svg.png", "answers": ["Nova Scotia", "NS"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Nova_Scotia_102.svg/384px-Nova_Scotia_102.svg.png", "answers": ["Nova Scotia", "NS"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Nova_Scotia_Route_221.svg/640px-Nova_Scotia_Route_221.svg.png", "answers": ["Nova Scotia", "NS"] },
	{ "letter": "https://i.imgur.com/Zzwgkls.png", "answers": ["Ontario", "ON"] },
	{ "letter": "https://i.imgur.com/GpRIEfb.png", "answers": ["Ontario", "ON"] },
	{ "letter": "https://i.imgur.com/kth7WqM.png", "answers": ["Ontario", "ON"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Ontario_36_crown.svg/480px-Ontario_36_crown.svg.png", "answers": ["Ontario", "ON"] },
	{ "letter": "https://i.imgur.com/bBLG9EZ.png", "answers": ["Ontario", "ON"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/PEI_Highway_1A.svg/402px-PEI_Highway_1A.svg.png", "answers": ["Prince Edward Island", "PE", "PEI"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Quebec_Autoroute_20.svg/360px-Quebec_Autoroute_20.svg.png", "answers": ["Quebec", "QC", "Québec"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Qc138.svg/359px-Qc138.svg.png", "answers": ["Quebec", "QC", "Québec"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Saskatchewan_Highway_11_%28jct%29.svg/384px-Saskatchewan_Highway_11_%28jct%29.svg.png", "answers": ["Saskatchewan", "SK"] },
	{ "letter": "https://i.imgur.com/Ou0OPSm.png", "answers": ["Saskatchewan", "SK"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Saskatchewan_Highway_999_%28jct%29.svg/384px-Saskatchewan_Highway_999_%28jct%29.svg.png", "answers": ["Saskatchewan", "SK"] },
	{ "letter": "https://i.imgur.com/pQFLm2Z.png", "answers": ["Northwest Territories", "NT", "NWT"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Yukon_Highway_4.svg/480px-Yukon_Highway_4.svg.png", "answers": ["Yukon", "YT"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Yukon_Highway_2.svg/480px-Yukon_Highway_2.svg.png", "answers": ["Yukon", "YT"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Yukon_Highway_5.svg/480px-Yukon_Highway_5.svg.png", "answers": ["Yukon", "YT"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Yukon_Highway_6.svg/480px-Yukon_Highway_6.svg.png", "answers": ["Yukon", "YT"] },
  ]
};

module.exports = CASHIELDS;