const CNAREACODES = {
	"footer": "Write the Chinese province/city containing these area codes.",
	"sets": [
		{ "letter": "090, 099", "answers": ["Xinjiang"] },
		{ "letter": "0891-0897", "answers": ["Xizang", "Tibet"] },
		{ "letter": "097", "answers": ["Qinghai"] },
		{ "letter": "093, 094", "answers": ["Gansu"] },
		{ "letter": "095", "answers": ["Ningxia"] },
		{ "letter": "047, 048", "answers": ["Neimenggu", "Inner Mongolia"] },
		{ "letter": "045, 046", "answers": ["Heilongjiang"] },
		{ "letter": "043", "answers": ["Jilin"] },
		{ "letter": "041, 042", "answers": ["Liaoning"] },
		{ "letter": "024", "answers": ["Shenyang"] },
		{ "letter": "031, 033", "answers": ["Hebei"] },
		{ "letter": "010", "answers": ["Beijing"] },
		{ "letter": "022", "answers": ["Tianjin"] },
		{ "letter": "034, 035", "answers": ["Shanxi"] },
		{ "letter": "091", "answers": ["Shaanxi"] },
		{ "letter": "029", "answers": ["Xi'an"] },
		{ "letter": "053, 054, 063", "answers": ["Shandong"] },
		{ "letter": "037, 039", "answers": ["Henan"] },
		{ "letter": "071, 072", "answers": ["Hubei"] },
		{ "letter": "027", "answers": ["Wuhan"] },
		{ "letter": "023", "answers": ["Chongqing"] },
		{ "letter": "081, 082, 083", "answers": ["Sichuan"] },
		{ "letter": "028", "answers": ["Chengdu"] },
		{ "letter": "051, 052", "answers": ["Jiangsu"] },
		{ "letter": "021", "answers": ["Shanghai"] },
		{ "letter": "055, 056", "answers": ["Anhui"] },
		{ "letter": "025", "answers": ["Nanjing"] },
		{ "letter": "070, 079", "answers": ["Jiangxi"] },
		{ "letter": "073, 074", "answers": ["Hunan"] },
		{ "letter": "085", "answers": ["Guizhou"] },
		{ "letter": "069, 087, 088", "answers": ["Yunnan"] },
		{ "letter": "077", "answers": ["Guangxi"] },
		{ "letter": "0898", "answers": ["Hainan"] },
		{ "letter": "066, 075, 076", "answers": ["Guangdong"] },
		{ "letter": "020", "answers": ["Guangzhou"] },
		{ "letter": "+852", "answers": ["Hong Kong"] },
		{ "letter": "+853", "answers": ["Macao", "Macau"] },
		{ "letter": "059", "answers": ["Fujian"] },
		{ "letter": "057, 058", "answers": ["Zhejiang"] },
  ]
};

module.exports = CNAREACODES;