const CNAREACODES = {
	"footer": "Write the Chinese province/city containing these area codes.",
	"sets": [
		{ "letter": "90, 99", "answers": ["Xinjiang"] },
		{ "letter": "891-897", "answers": ["Xizang", "Tibet"] },
		{ "letter": "97", "answers": ["Qinghai"] },
		{ "letter": "93, 94", "answers": ["Gansu"] },
		{ "letter": "95", "answers": ["Ningxia"] },
		{ "letter": "47, 48", "answers": ["Neimenggu", "Inner Mongolia"] },
		{ "letter": "45, 46", "answers": ["Heilongjiang"] },
		{ "letter": "43", "answers": ["Jilin"] },
		{ "letter": "41, 42", "answers": ["Liaoning"] },
		{ "letter": "24", "answers": ["Shenyang"] },
		{ "letter": "31, 33", "answers": ["Hebei"] },
		{ "letter": "10", "answers": ["Beijing"] },
		{ "letter": "22", "answers": ["Tianjin"] },
		{ "letter": "34, 35", "answers": ["Shanxi"] },
		{ "letter": "91", "answers": ["Shaanxi"] },
		{ "letter": "29", "answers": ["Xi'an"] },
		{ "letter": "53, 54, 63", "answers": ["Shandong"] },
		{ "letter": "37, 39", "answers": ["Henan"] },
		{ "letter": "71, 72", "answers": ["Hubei"] },
		{ "letter": "27", "answers": ["Wuhan"] },
		{ "letter": "23", "answers": ["Chongqing"] },
		{ "letter": "81, 82, 83", "answers": ["Sichuan"] },
		{ "letter": "28", "answers": ["Chengdu"] },
		{ "letter": "51, 52", "answers": ["Jiangsu"] },
		{ "letter": "21", "answers": ["Shanghai"] },
		{ "letter": "55, 56", "answers": ["Anhui"] },
		{ "letter": "25", "answers": ["Nanjing"] },
		{ "letter": "70, 79", "answers": ["Jiangxi"] },
		{ "letter": "73, 74", "answers": ["Hunan"] },
		{ "letter": "85", "answers": ["Guizhou"] },
		{ "letter": "69, 87, 88", "answers": ["Yunnan"] },
		{ "letter": "77", "answers": ["Guangxi"] },
		{ "letter": "898", "answers": ["Hainan"] },
		{ "letter": "66, 75, 76", "answers": ["Guangdong"] },
		{ "letter": "20", "answers": ["Guangzhou"] },
		{ "letter": "+852", "answers": ["Hong Kong"] },
		{ "letter": "+853", "answers": ["Macao", "Macau"] },
		{ "letter": "59", "answers": ["Fujian"] },
		{ "letter": "57, 58", "answers": ["Zhejiang"] },
  ]
};

module.exports = CNAREACODES;