const CNPLATES = {
	"title": "Guess the province",
	"footer": "Write the province the given plate is from.",
	"sets": [
		{ "letter": "http://www.plateshack.com/y2k/PRChina/ningxiahui2016.jpg", "answers": ["Ningxia"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chongquing2016.jpg", "answers": ["Chongqing"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/gansu2016.jpg", "answers": ["Gansu"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinaanhui.jpg", "answers": ["Anhui"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinafujian2.jpg", "answers": ["Fujian"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinahainan.jpg", "answers": ["Hainan"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinahebei.jpg", "answers": ["Hebei"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinaheilongjiang.jpg", "answers": ["Heilongjiang"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinahenan.jpg", "answers": ["Henan"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinahubei.jpg", "answers": ["Hubei"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinahunan.jpg", "answers": ["Hunan"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinajiangsu.jpg", "answers": ["Jiangsu"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinajiangxi.jpg", "answers": ["Jiangxi"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinajilin.jpg", "answers": ["Jilin"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinaliaoning.jpg", "answers": ["Liaoning"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinasichuan.jpg", "answers": ["Sichuan"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinazhejiang.jpg", "answers": ["Zhejiang"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinaxizangtibet2014.jpg", "answers": ["Xizang", "Tibet"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinatianjin2014.jpg", "answers": ["Tianjin"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/china2014shanxi.jpg", "answers": ["Shanxi"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/shandong2014.jpg", "answers": ["Shandong"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/guangdong2014.jpg", "answers": ["Guangdong"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/qinghai.jpg", "answers": ["Qinghai"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinashaanxi.jpg", "answers": ["Shaanxi"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/beijingN.jpg", "answers": ["Beijing"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/shanghai2014.jpg", "answers": ["Shanghai"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinaneimenggu.jpg", "answers": ["Neimenggu", "Inner Mongolia"] },
		{ "letter": "https://i.imgur.com/LX6QAkC.jpg", "answers": ["Guangxi"] },
		{ "letter": "https://i.imgur.com/upYxRX7.jpg", "answers": ["Yunnan"] },
		{ "letter": "https://i.imgur.com/TMDCUE9.jpg", "answers": ["Guizhou"] },
		{ "letter": "https://i.imgur.com/fHI5FAW.jpg", "answers": ["Xinjiang"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinacrosshongkong.jpg", "answers": ["Hong Kong"] },
		{ "letter": "http://www.plateshack.com/y2k/PRChina/chinacrossmacao.jpg", "answers": ["Macau", "Macao"] },
  ]
};

module.exports = CNPLATES;