const CNPROVINCES = {
	"footer": "Write the English name of the given Chinese province.",
	"sets": [
    { "letter": "安徽", "answers": ["Anhui"] },
    { "letter": "北京", "answers": ["Beijing"] },
    { "letter": "重庆", "answers": ["Chongqing"] },
    { "letter": "福建", "answers": ["Fujian"] },
    { "letter": "广东", "answers": ["Guangdong"] },
    { "letter": "甘肃", "answers": ["Gansu"] },
    { "letter": "广西", "answers": ["Guangxi"] },
    { "letter": "贵州", "answers": ["Guizhou"] },
    { "letter": "河南", "answers": ["Henan"] },
    { "letter": "湖北", "answers": ["Hubei"] },
    { "letter": "河北", "answers": ["Hebei"] },
    { "letter": "海南", "answers": ["Hainan"] },
    { "letter": "香港", "answers": ["Hong Kong"] },
    { "letter": "黑龙江", "answers": ["Heilongjiang"] },
    { "letter": "湖南", "answers": ["Hunan"] },
    { "letter": "吉林", "answers": ["Jilin"] },
    { "letter": "江苏", "answers": ["Jiangsu"] },
    { "letter": "江西", "answers": ["Jiangxi"] },
    { "letter": "辽宁", "answers": ["Liaoning"] },
    { "letter": "澳门", "answers": ["Macau", "Macao"] },
    { "letter": "内蒙古", "answers": ["Inner Mongolia"] },
    { "letter": "宁夏", "answers": ["Ningxia"] },
    { "letter": "青海", "answers": ["Qinghai"] },
    { "letter": "四川", "answers": ["Sichuan"] },
    { "letter": "山东", "answers": ["Shandong"] },
    { "letter": "上海", "answers": ["Shanghai"] },
    { "letter": "陕西", "answers": ["Shaanxi"] },
    { "letter": "山西", "answers": ["Shanxi"] },
    { "letter": "天津", "answers": ["Tianjin"] },
    { "letter": "新疆", "answers": ["Xinjiang"] },
    { "letter": "西藏", "answers": ["Tibet"] },
    { "letter": "云南", "answers": ["Yunnan"] },
    { "letter": "浙江", "answers": ["Zhejiang"] },
  ]
};

module.exports = CNPROVINCES;