const CYRILLIC = {
	"footer": "Write the Latin transliteration of the given Russian Cyrillic letter.",
	"sets": [
    { "letter": "А а", "answers": ["a"] },
    { "letter": "Б б", "answers": ["b"] },
    { "letter": "В в", "answers": ["v"] },
    { "letter": "Г г", "answers": ["g"] },
    { "letter": "Д д", "answers": ["d"] },
    { "letter": "Е е", "answers": ["e", "ye", "ie"] },
    { "letter": "Ё ё", "answers": ["yo", "io"] },
    { "letter": "Ж ж", "answers": ["zh"] },
    { "letter": "З з", "answers": ["z"] },
    { "letter": "И и", "answers": ["i", "yi"] },
    { "letter": "Й й", "answers": ["y", "j"] },
    { "letter": "К к", "answers": ["k"] },
    { "letter": "Л л", "answers": ["l"] },
    { "letter": "М м", "answers": ["m"] },
    { "letter": "Н н", "answers": ["n"] },
    { "letter": "О о", "answers": ["o"] },
    { "letter": "П п", "answers": ["p"] },
    { "letter": "Р р", "answers": ["r"] },
    { "letter": "С с", "answers": ["s"] },
    { "letter": "Т т", "answers": ["t"] },
    { "letter": "У у", "answers": ["u"] },
    { "letter": "Ф ф", "answers": ["f"] },
    { "letter": "Х х", "answers": ["kh", "h"] },
    { "letter": "Ц ц", "answers": ["ts", "c"] },
    { "letter": "Ч ч", "answers": ["ch"] },
    { "letter": "Ш ш", "answers": ["sh"] },
    { "letter": "Щ щ", "answers": ["shch", "soft sh", "shh"] },
    { "letter": "Ъ ъ", "answers": ["-", "hard sign", "\""] },
    { "letter": "Ы ы", "answers": ["y", "hard i"] },
    { "letter": "Ь ь", "answers": ["-", "soft sign", "'"] },
    { "letter": "Э э", "answers": ["e"] },
    { "letter": "Ю ю", "answers": ["yu", "iu"] },
    { "letter": "Я я", "answers": ["ya", "ia"] },
  ]
};

module.exports = CYRILLIC;