const GEORGIAN = {
	"footer": "Write the Latin transliteration of the given Georgian letter.",
	"sets": [
    { "letter": "ა Ა", "answers": ["a"] },
    { "letter": "ბ Ბ", "answers": ["b"] },
    { "letter": "გ Გ", "answers": ["g"] },
    { "letter": "დ Დ", "answers": ["d"] },
    { "letter": "ე Ე", "answers": ["e"] },
    { "letter": "ვ Ვ", "answers": ["v"] },
    { "letter": "ზ Ზ", "answers": ["z"] },
    { "letter": "თ Თ", "answers": ["t"] },
    { "letter": "ი Ი", "answers": ["i"] },
    { "letter": "კ Კ", "answers": ["k'"] },
    { "letter": "ლ Ლ", "answers": ["l"] },
    { "letter": "მ Მ", "answers": ["m"] },
    { "letter": "ნ Ნ", "answers": ["n"] },
    { "letter": "ო Ო", "answers": ["o"] },
    { "letter": "პ Პ", "answers": ["p'"] },
    { "letter": "ჟ Ჟ", "answers": ["zh"] },
    { "letter": "რ Რ", "answers": ["r"] },
    { "letter": "ს Ს", "answers": ["s"] },
    { "letter": "ტ Ტ", "answers": ["t'"] },
    { "letter": "უ Უ", "answers": ["u"] },
    { "letter": "ფ Ფ", "answers": ["p"] },
    { "letter": "ქ Ქ", "answers": ["k"] },
    { "letter": "ღ Ღ", "answers": ["gh"] },
    { "letter": "ყ Ყ", "answers": ["q'", "q"] },
    { "letter": "შ Შ", "answers": ["sh"] },
    { "letter": "ჩ Ჩ", "answers": ["ch"] },
    { "letter": "ც Ც", "answers": ["ts"] },
    { "letter": "ძ Ძ", "answers": ["dz"] },
    { "letter": "წ Წ", "answers": ["ts'"] },
    { "letter": "ჭ Ჭ", "answers": ["ch'"] },
    { "letter": "ხ Ხ", "answers": ["kh", "x"] },
    { "letter": "ჯ Ჯ", "answers": ["j"] },
    { "letter": "ჰ Ჰ", "answers": ["h"] },
  ]
};

module.exports = GEORGIAN;