const GUJARATI = {
	"footer": "Write the Latin transliteration of the given Gujarati letter.",
	"sets": [
    { "letter": "અ, ભ", "answers": ["a"] },
    { "letter": "આ, ા, ભા", "answers": ["aa", "ā"] },
    { "letter": "ઇ,	િ, ભિ", "answers": ["i"] },
    { "letter": "ઈ,	ી, ભી", "answers": ["ii", "ī"] },
    { "letter": "ઉ,	ુ, ભુ", "answers": ["u"] },
    { "letter": "ઊ,	ૂ, ભૂ ", "answers": ["uu", "ū"] },
    { "letter": "એ,	ે, ભે", "answers": ["e"] },
    { "letter": "ઐ,	ૈ, ભૈ", "answers": ["ai"] },
    { "letter": "ઓ,	ો, ભો", "answers": ["o"] },
    { "letter": "ઔ, ૌ, ભૌ", "answers": ["au"] },
    { "letter": "અં, ં, ભં", "answers": ["a'", "ṁ"] },
    { "letter": "અ:, ઃ, ભઃ ", "answers": ["-", "ḥ"] },
    { "letter": "ઋ, ૃ, ભૃ", "answers": ["ru", "r̥"] },
    { "letter": "ઍ, ૅ, ભૅ", "answers": ["ae", "â"] },
    { "letter": "ઑ,	ૉ, ભૉ", "answers": ["ou", "ô"] },
    { "letter": "ક", "answers": ["k"] },
    { "letter": "ચ", "answers": ["ch"] },
    { "letter": "ટ", "answers": ["t"] },
    { "letter": "ત", "answers": ["t"] },
    { "letter": "પ", "answers": ["p"] },
    { "letter": "ખ", "answers": ["kh"] },
    { "letter": "છ", "answers": ["chh"] },
    { "letter": "ઠ", "answers": ["th"] },
    { "letter": "થ", "answers": ["th"] },
    { "letter": "ફ", "answers": ["ph"] },
    { "letter": "ગ", "answers": ["g"] },
    { "letter": "જ", "answers": ["j"] },
    { "letter": "ડ", "answers": ["d"] },
    { "letter": "દ", "answers": ["d"] },
    { "letter": "બ", "answers": ["b"] },
    { "letter": "ઘ", "answers": ["gh"] },
    { "letter": "ઝ", "answers": ["jh"] },
    { "letter": "ઢ", "answers": ["dh"] },
    { "letter": "ધ", "answers": ["dh"] },
    { "letter": "ભ", "answers": ["bh"] },
    { "letter": "ઙ", "answers": ["ng", "ṅ"] },
    { "letter": "ઞ", "answers": ["n'", "ñ", "ny"] },
    { "letter": "ણ", "answers": ["n", "ṇ", "hn"] },
    { "letter": "ન", "answers": ["n"] },
    { "letter": "મ", "answers": ["m"] },
    { "letter": "ય", "answers": ["y"] },
    { "letter": "ર", "answers": ["r"] },
    { "letter": "લ", "answers": ["l"] },
    { "letter": "વ", "answers": ["v"] },
    { "letter": "શ", "answers": ["sh", "ś"] },
    { "letter": "ષ", "answers": ["sh", "ṣ"] },
    { "letter": "સ", "answers": ["s"] },
    { "letter": "હ", "answers": ["h"] },
    { "letter": "ળ", "answers": ["l", "ḷ"] },
    { "letter": "ક્ષ", "answers": ["ksh", "kṣ"] },
    { "letter": "જ્ઞ", "answers": ["gn'", "gñ", "gny"] },
  ]
};

module.exports = GUJARATI;