const JAPANESE = {
	"footer": "Write the Latin transliteration of the given Hiragana/Katakana letter.",
	"sets": [
    { "letter": "あ, ア", "answers": ["a"] },
    { "letter": "い, イ", "answers": ["i"] },
    { "letter": "う, ウ", "answers": ["u"] },
    { "letter": "え, エ", "answers": ["e"] },
    { "letter": "お, オ", "answers": ["o"] },
    { "letter": "か, カ", "answers": ["ka"] },
    { "letter": "き, キ", "answers": ["ki"] },
    { "letter": "く, ク", "answers": ["ku"] },
    { "letter": "け, ケ", "answers": ["ke"] },
    { "letter": "こ, コ", "answers": ["ko"] },
    { "letter": "きゃ, キャ", "answers": ["kya"] },
    { "letter": "きゅ, キュ", "answers": ["kyu"] },
    { "letter": "きょ, キョ", "answers": ["kyo"] },
    { "letter": "さ, サ", "answers": ["sa"] },
    { "letter": "し, シ", "answers": ["shi", "si"] },
    { "letter": "す, ス", "answers": ["su"] },
    { "letter": "せ, セ", "answers": ["se"] },
    { "letter": "そ, ソ", "answers": ["so"] },
    { "letter": "しゃ, シャ", "answers": ["sha", "sya"] },
    { "letter": "しゅ, シュ", "answers": ["shu", "syu"] },
    { "letter": "しょ, ショ", "answers": ["sho", "syo"] },
    { "letter": "た, タ", "answers": ["ta"] },
    { "letter": "ち, チ", "answers": ["chi", "ti"] },
    { "letter": "つ, ツ", "answers": ["tsu", "tu"] },
    { "letter": "て, テ", "answers": ["te"] },
    { "letter": "と, ト", "answers": ["to"] },
    { "letter": "ちゃ, チャ", "answers": ["cha", "tya"] },
    { "letter": "ちゅ, チュ", "answers": ["chu", "tyu"] },
    { "letter": "ちょ, チョ", "answers": ["cho", "tyo"] },
    { "letter": "な, ナ", "answers": ["na"] },
    { "letter": "に, ニ", "answers": ["ni"] },
    { "letter": "ぬ, ヌ", "answers": ["nu"] },
    { "letter": "ね, ネ", "answers": ["ne"] },
    { "letter": "の, ノ", "answers": ["no"] },
    { "letter": "にゃ, ニャ", "answers": ["nya"] },
    { "letter": "にゅ, ニュ", "answers": ["nyu"] },
    { "letter": "にょ, ニョ", "answers": ["nyo"] },
    { "letter": "は, ハ", "answers": ["ha"] },
    { "letter": "ひ, ヒ", "answers": ["hi"] },
    { "letter": "ふ, フ", "answers": ["fu", "hu"] },
    { "letter": "へ, ヘ", "answers": ["he"] },
    { "letter": "ほ, ホ", "answers": ["ho"] },
    { "letter": "ひゃ, ヒャ", "answers": ["hya"] },
    { "letter": "ひゅ, ヒュ", "answers": ["hyu"] },
    { "letter": "ひょ, ヒョ", "answers": ["hyo"] },
    { "letter": "ま, マ", "answers": ["ma"] },
    { "letter": "み, ミ", "answers": ["mi"] },
    { "letter": "む, ム", "answers": ["mu"] },
    { "letter": "め, メ", "answers": ["me"] },
    { "letter": "も, モ", "answers": ["mo"] },
    { "letter": "みゃ, ミャ", "answers": ["mya"] },
    { "letter": "みゅ, ミュ", "answers": ["myu"] },
    { "letter": "みょ, ミョ", "answers": ["myo"] },
    { "letter": "や, ヤ", "answers": ["ya"] },
    { "letter": "ゆ, ユ", "answers": ["yu"] },
    { "letter": "よ, ヨ", "answers": ["yo"] },
    { "letter": "ら, ラ", "answers": ["ra"] },
    { "letter": "り, リ", "answers": ["ri"] },
    { "letter": "る, ル", "answers": ["ru"] },
    { "letter": "れ, レ", "answers": ["re"] },
    { "letter": "ろ, ロ", "answers": ["ro"] },
    { "letter": "りゃ, リャ", "answers": ["rya"] },
    { "letter": "りゅ, リュ", "answers": ["ryu"] },
    { "letter": "りょ, リョ", "answers": ["ryo"] },
    { "letter": "わ, ワ", "answers": ["wa"] },
    { "letter": "ゐ, ヰ", "answers": ["i", "wi"] },
    { "letter": "ゑ, ヱ", "answers": ["e", "we"] },
    { "letter": "を, ヲ", "answers": ["o", "wo"] },
    { "letter": "ん, ン", "answers": ["n", "n'"] },
    { "letter": "が, ガ", "answers": ["ga"] },
    { "letter": "ぎ, ギ", "answers": ["gi"] },
    { "letter": "ぐ, グ", "answers": ["gu"] },
    { "letter": "げ, ゲ", "answers": ["ge"] },
    { "letter": "ご, ゴ", "answers": ["go"] },
    { "letter": "ぎゃ, ギャ", "answers": ["gya"] },
    { "letter": "ぎゅ, ギュ", "answers": ["gyu"] },
    { "letter": "ぎょ, ギョ", "answers": ["gyo"] },
    { "letter": "ざ, ザ", "answers": ["za"] },
    { "letter": "じ, ジ", "answers": ["ji", "zi"] },
    { "letter": "ず, ズ", "answers": ["zu"] },
    { "letter": "ぜ, ゼ", "answers": ["ze"] },
    { "letter": "ぞ, ゾ", "answers": ["zo"] },
    { "letter": "じゃ, ジャ", "answers": ["ja", "zya"] },
    { "letter": "じゅ, ジュ", "answers": ["ju", "zyu"] },
    { "letter": "じょ, ジョ", "answers": ["jo", "zyo"] },
    { "letter": "だ, ダ", "answers": ["da"] },
    { "letter": "ぢ, ヂ", "answers": ["ji", "di"] },
    { "letter": "づ, ヅ", "answers": ["zu", "du"] },
    { "letter": "で, デ", "answers": ["de"] },
    { "letter": "ど, ド", "answers": ["do"] },
    { "letter": "ぢゃ, ヂャ", "answers": ["ja", "dya"] },
    { "letter": "ぢゅ, ヂュ", "answers": ["ju", "dyu"] },
    { "letter": "ぢょ, ヂョ", "answers": ["jo", "dyo"] },
    { "letter": "ば, バ", "answers": ["ba"] },
    { "letter": "び, ビ", "answers": ["bi"] },
    { "letter": "ぶ, ブ", "answers": ["bu"] },
    { "letter": "べ, ベ", "answers": ["be"] },
    { "letter": "ぼ, ボ", "answers": ["bo"] },
    { "letter": "びゃ, ビャ", "answers": ["bya"] },
    { "letter": "びゅ, ビュ", "answers": ["byu"] },
    { "letter": "びょ, ビョ", "answers": ["byo"] },
    { "letter": "ぱ, パ", "answers": ["pa"] },
    { "letter": "ぴ, ピ", "answers": ["pi"] },
    { "letter": "ぷ, プ", "answers": ["pu"] },
    { "letter": "ぺ, ペ", "answers": ["pe"] },
    { "letter": "ぽ, ポ", "answers": ["po"] },
    { "letter": "ぴゃ, ピャ", "answers": ["pya"] },
    { "letter": "ぴゅ, ピュ", "answers": ["pyu"] },
    { "letter": "ぴょ, ピョ", "answers": ["pyo"] },
    { "letter": "ゔ, ヴ", "answers": ["vu"] },
  ]
};

module.exports = JAPANESE;