const KOREAN = {
	"footer": "Write the Latin transliteration of the given Hangul letter.",
	"sets": [
    { "letter": "ㄱ", "answers": ["g", "k"] },
    { "letter": "ㄴ", "answers": ["n"] },
    { "letter": "ㄷ", "answers": ["d", "t"] },
    { "letter": "ㄹ", "answers": ["r", "l"] },
    { "letter": "ㅁ", "answers": ["m"] },
    { "letter": "ㅂ", "answers": ["b", "p"] },
    { "letter": "ㅅ", "answers": ["s", "t"] },
    { "letter": "ㅇ", "answers": ["-", "ng"] },
    { "letter": "ㅈ", "answers": ["j", "t"] },
    { "letter": "ㅊ", "answers": ["ch", "t"] },
    { "letter": "ㅋ", "answers": ["k"] },
    { "letter": "ㅌ", "answers": ["t"] },
    { "letter": "ㅍ", "answers": ["p"] },
    { "letter": "ㅎ", "answers": ["h", "t"] },
    { "letter": "ㅏ", "answers": ["a"] },
    { "letter": "ㅑ", "answers": ["ya"] },
    { "letter": "ㅓ", "answers": ["eo"] },
    { "letter": "ㅕ", "answers": ["yeo"] },
    { "letter": "ㅗ", "answers": ["o"] },
    { "letter": "ㅛ", "answers": ["yo"] },
    { "letter": "ㅜ", "answers": ["u"] },
    { "letter": "ㅠ", "answers": ["yu"] },
    { "letter": "ㅡ", "answers": ["eu"] },
    { "letter": "ㅣ", "answers": ["i"] },
    { "letter": "ㄲ", "answers": ["kk", "k"] },
    { "letter": "ㄸ", "answers": ["tt"] },
    { "letter": "ㅃ", "answers": ["pp"] },
    { "letter": "ㅉ", "answers": ["jj"] },
    { "letter": "ㅆ", "answers": ["ss", "t"] },
    { "letter": "ㅢ", "answers": ["ui"] },
    { "letter": "ㅚ", "answers": ["oe"] },
    { "letter": "ㅐ", "answers": ["ae"] },
    { "letter": "ㅟ", "answers": ["ye"] },
    { "letter": "ㅔ", "answers": ["e"] },
    { "letter": "ㅒ", "answers": ["yae"] },
    { "letter": "ㅖ", "answers": ["ye"] },
    { "letter": "ㅘ", "answers": ["wa"] },
    { "letter": "ㅝ", "answers": ["wo"] },
    { "letter": "ㅙ", "answers": ["wae"] },
    { "letter": "ㅞ", "answers": ["we"] },
  ]
};

module.exports = KOREAN;