const LETTERGUESS = {
	"footer": "Write a language the letter is from.",
	"sets": [
    { "letter": "Á (á)", "answers": ["Spanish", "Galician", "Portuguese", "Occitan", "Catalan", "Dutch", "Icelandic", "Faroese", "Czech", "Slovak", "Hungarian", "Irish", "Tetum", "Pinyin"] },
	{ "letter": "À (à)", "answers": ["Portuguese", "Occitan", "French", "Italian", "Scottish Gaelic", "Malagasy", "Maltese", "Pinyin"] },
	{ "letter": "Â (â)", "answers": ["Portuguese", "French", "Walloon", "Romanian", "Norwegian", "Breton", "Vietnamese"] },
	{ "letter": "Ă (ă)", "answers": ["Romanian", "Vietnamese", "Pinyin"] },
	{ "letter": "Ä (ä)", "answers": ["German", "Dutch", "Luxembourgish", "Swedish", "Slovak", "Finnish", "Estonian", "Turkmen"] },
	{ "letter": "Æ (æ)", "answers": ["French", "Icelandic", "Faroese", "Norwegian", "Danish", "Greenlandic"] },
	{ "letter": "Ã (ā)", "answers": ["Portuguese", "Aromanian"] },
	{ "letter": "Å (å)", "answers": ["Walloon", "Norwegian", "Swedish", "Danish", "Finnish", "Greenlandic"] },
	{ "letter": "Ą (ą)", "answers": ["Polish", "Lithuanian"] },
	{ "letter": "Ā (ā)", "answers": ["Latvian", "Tongan", "Niuean", "Samoan", "Hawaiian", "Tahitian", "Māori", "Pinyin"] },
	{ "letter": "BH (bh)", "answers": ["Scottish Gaelic"] },
	{ "letter": "Ç (ç)", "answers": ["Galician", "Portuguese", "Occitan", "Catalan", "French", "Walloon", "Sardinian", "Albanian", "Basque", "Turkish", "Azerbaijani", "Turkmen"] },
	{ "letter": "Č (č)", "answers": ["Czech", "Slovak", "Slovene", "Croatian", "Bosnian", "Montenegrin", "Serbian", "Lithuanian", "Latvian"] },
	{ "letter": "Ć (ć)", "answers": ["Polish", "Croatian", "Bosnian", "Montenegrin", "Serbian"] },
	{ "letter": "Ċ (ċ)", "answers": ["Maltese"] },
	{ "letter": "Ĉ (ĉ)", "answers": ["Esperanto"] },
	{ "letter": "CH (ch)", "answers": ["Czech", "Slovak", "Welsh", "Breton", "Scottish Gaelic", "Uzbek"] },
	{ "letter": "C'H (c'h)", "answers": ["Breton"] },
	{ "letter": "CS (cs)", "answers": ["Hungarian"] },
	{ "letter": "Ð (ð)", "answers": ["Icelandic", "Faroese"] },
	{ "letter": "Đ (đ)", "answers": ["Croatian", "Bosnian", "Montenegrin", "Serbian", "Vietnamese"] },
	{ "letter": "Ď (ď)", "answers": ["Czech", "Slovak"] },
	{ "letter": "DD (dd)", "answers": ["Welsh"] },
	{ "letter": "DH (dh)", "answers": ["Aromanian", "Albanian", "Scottish Gaelic"] },
	{ "letter": "DZ (dz)", "answers": ["Aromanian", "Slovak", "Hungarian"] },
	{ "letter": "DŽ (dž)", "answers": ["Slovak", "Croatian", "Bosnian", "Montenegrin", "Serbian"] },
	{ "letter": "DZS (dzs)", "answers": ["Hungarian"] },
	{ "letter": "É (é)", "answers": ["Spanish", "Galician", "Portuguese", "Occitan", "Catalan", "French", "Walloon", "Italian", "Dutch", "Luxembourgish", "Icelandic", "Norwegian", "Swedish", "Czech", "Slovak", "Hungarian", "Irish", "Tetum", "Pinyin"] },
	{ "letter": "È (è)", "answers": ["Portuguese", "Occitan", "Catalan", "French", "Walloon", "Italian", "Norwegian", "Scottish Gaelic", "Malagasy", "Maltese", "Pinyin"] },
	{ "letter": "Ê (ê)", "answers": ["Portuguese", "French", "Walloon", "Norwegian", "Māori", "Vietnamese", "Pinyin"] },
	{ "letter": "Ě (ě)", "answers": ["Czech", "Pinyin"] },
	{ "letter": "Ë (ë)", "answers": ["French", "Walloon", "Dutch", "Luxembourgish", "Albanian"] },
	{ "letter": "Ę (ę)", "answers": ["Polish", "Lithuanian"] },
	{ "letter": "Ė (ė)", "answers": ["Lithuanian"] },
	{ "letter": "Ē (ē)", "answers": ["Latvian", "Tongan", "Niuean", "Samoan", "Hawaiian", "Tahitian", "Māori", "Pinyin"] },
	{ "letter": "E̊ (e̊)", "answers": ["Walloon"] },
	{ "letter": "Ə (ə)", "answers": ["Azerbaijani"] },
	{ "letter": "FF (ff)", "answers": ["Welsh"] },
	{ "letter": "FH (fh)", "answers": ["Scottish Gaelic"] },
	{ "letter": "Ģ (ģ)", "answers": ["Latvian"] },
	{ "letter": "Ğ (ğ)", "answers": ["Turkish", "Azerbaijani"] },
	{ "letter": "Ġ (ġ)", "answers": ["Maltese"] },
	{ "letter": "Ĝ (ĝ)", "answers": ["Esperanto"] },
	{ "letter": "GH (gh)", "answers": ["Scottish Gaelic"] },
	{ "letter": "GĦ (għ)", "answers": ["Maltese"] },
	{ "letter": "GJ (gj)", "answers": ["Albanian"] },
	{ "letter": "GY (gy)", "answers": ["Hungarian"] },
	{ "letter": "Gʻ (gʻ)", "answers": ["Uzbek"] },
	{ "letter": "Ħ (ħ)", "answers": ["Maltese"] },
	{ "letter": "Ĥ (ĥ)", "answers": ["Esperanto"] },
	{ "letter": "Ḥ (ḥ)", "answers": ["Asturian"] },
	{ "letter": "Í (í)", "answers": ["Spanish", "Galician", "Portuguese", "Occitan", "Catalan", "Dutch", "Icelandic", "Faroese", "Czech", "Slovak", "Hungarian", "Irish", "Tetum", "Pinyin"] },
	{ "letter": "Ì (ì)", "answers": ["Portuguese", "Italian", "Scottish Gaelic", "Malagasy", "Maltese", "Pinyin"] },
	{ "letter": "Ĭ (ĭ)", "answers": ["Pinyin"] },
	{ "letter": "Î (î)", "answers": ["French", "Walloon", "Italian", "Romanian", "Breton"] },
	{ "letter": "Ï (ï)", "answers": ["Occitan", "Catalan", "French", "Dutch"] },
	{ "letter": "I (ı)", "answers": ["Turkish", "Azerbaijani"] },
	{ "letter": "İ (i)", "answers": ["Turkish", "Azerbaijani"] },
	{ "letter": "Į (į)", "answers": ["Lithuanian"] },
	{ "letter": "Ī (ī)", "answers": ["Latvian", "Tongan", "Niuean", "Samoan", "Hawaiian", "Tahitian", "Māori", "Pinyin"] },
	{ "letter": "IE (ie)", "answers": ["Maltese"] },
	{ "letter": "IJ (ij)", "answers": ["Dutch"] },
	{ "letter": "Ĵ (ĵ)", "answers": ["Esperanto"] },
	{ "letter": "Ķ (ķ)", "answers": ["Latvian"] },
	{ "letter": "Ļ (ļ)", "answers": ["Latvian"] },
	{ "letter": "Ł (ł)", "answers": ["Polish"] },
	{ "letter": "Ĺ (ĺ)", "answers": ["Slovak"] },
	{ "letter": "Ľ (ľ)", "answers": ["Slovak"] },
	{ "letter": "LJ (lj)", "answers": ["Aromanian", "Croatian", "Bosnian", "Montenegrin", "Serbian"] },
	{ "letter": "LL (ll)", "answers": ["Albanian", "Welsh", "Scottish Gaelic"] },
	{ "letter": " ḶḶ (ḷḷ)", "answers": ["Asturian"] },
	{ "letter": "L·L (l·l)", "answers": ["Catalan"] },
	{ "letter": "LY (ly)", "answers": ["Hungarian"] },
	{ "letter": "MH (mh)", "answers": ["Scottish Gaelic"] },
	{ "letter": "Ñ (ñ)", "answers": ["Spanish", "Asturian", "Galician", "Breton", "Basque", "Filipino", "Tetum"] },
	{ "letter": "Ņ (ņ)", "answers": ["Latvian"] },
	{ "letter": "Ń (ń)", "answers": ["Polish"] },
	{ "letter": "Ň (ň)", "answers": ["Czech", "Slovak", "Turkmen"] },
	{ "letter": "N̈ (n̈)", "answers": ["Malagasy"] },
	{ "letter": "NG (ng)", "answers": ["Welsh", "Scottish Gaelic", "Uzbek", "Filipino", "Tongan", "Māori"] },
	{ "letter": "N·H (n·h)", "answers": ["Occitan"] },
	{ "letter": "NJ (nj)", "answers": ["Aromanian", "Croatian", "Bosnian", "Montenegrin", "Serbian", "Albanian"] },
	{ "letter": "NN (nn)", "answers": ["Scottish Gaelic"] },
	{ "letter": "NY (ny)", "answers": ["Hungarian"] },
	{ "letter": "Ó (ó)", "answers": ["Spanish", "Galician", "Portuguese", "Occitan", "Catalan", "Italian", "Dutch", "Icelandic", "Faroese", "Norwegian", "Polish", "Czech", "Slovak", "Hungarian", "Irish", "Tetum", "Pinyin"] },
	{ "letter": "Ò (ò)", "answers": ["Portuguese", "Occitan", "Catalan", "Italian", "Norwegian", "Scottish Gaelic", "Malagasy", "Maltese", "Pinyin"] },
	{ "letter": "Ô (ô)", "answers": ["Portuguese", "French", "Walloon", "Norwegian", "Slovak", "Breton", "Malagasy", "Vietnamese"] },
	{ "letter": "Ö (ö)", "answers": ["Walloon", "German", "Dutch", "Icelandic", "Faroese", "Swedish", "Finnish", "Estonian", "Hungarian", "Turkish", "Azerbaijani", "Turkmen"] },
	{ "letter": "Õ (õ)", "answers": ["Portuguese", "Faroese", "Estonian"] },
	{ "letter": "Œ (œ)", "answers": ["French"] },
	{ "letter": "Ø (ø)", "answers": ["Faroese", "Norwegian", "Danish", "Greenlandic"] },
	{ "letter": "Ő (ő)", "answers": ["Hungarian"] },
	{ "letter": "Ō (ō)", "answers": ["Tongan", "Niuean", "Samoan", "Hawaiian", "Tahitian", "Māori", "Pinyin"] },
	{ "letter": "Oʻ (oʻ)", "answers": ["Uzbek"] },
	{ "letter": "Ơ (ơ)", "answers": ["Vietnamese"] },
	{ "letter": "PH (ph)", "answers": ["Welsh", "Scottish Gaelic"] },
	{ "letter": "Ř (ř)", "answers": ["Czech"] },
	{ "letter": "Ŕ (ŕ)", "answers": ["Slovak"] },
	{ "letter": "RH (rh)", "answers": ["Welsh"] },
	{ "letter": "RR (rr)", "answers": ["Albanian", "Scottish Gaelic"] },
	{ "letter": "ẞ (ß)", "answers": ["German"] },
	{ "letter": "Ș (ș)", "answers": ["Romanian", "Welsh"] },
	{ "letter": "Š (š)", "answers": ["Czech", "Slovak", "Slovene", "Croatian", "Bosnian", "Montenegrin", "Serbian", "Lithuanian", "Latvian", "Finnish", "Estonian"] },
	{ "letter": "Ś (ś)", "answers": ["Polish", "Montenegrin"] },
	{ "letter": "Ş (ş)", "answers": ["Turkish", "Azerbaijani", "Turkmen"] },
	{ "letter": "Ŝ (ŝ)", "answers": ["Esperanto"] },
	{ "letter": "SH (sh)", "answers": ["Aromanian", "Albanian", "Scottish Gaelic", "Uzbek"] },
	{ "letter": "S·H (s·h)", "answers": ["Occitan"] },
	{ "letter": "SZ (sz)", "answers": ["Hungarian"] },
	{ "letter": "Ť (ť)", "answers": ["Czech", "Slovak"] },
	{ "letter": "Ț (ț)", "answers": ["Romanian"] },
	{ "letter": "TH (th)", "answers": ["Aromanian", "Albanian", "Welsh", "Scottish Gaelic"] },
	{ "letter": "TS (ts)", "answers": ["Aromanian"] },
	{ "letter": "TY (ty)", "answers": ["Hungarian"] },
	{ "letter": "TZ (tz)", "answers": ["Sardinian"] },
	{ "letter": "Ú (ú)", "answers": ["Spanish", "Galician", "Portuguese", "Occitan", "Catalan", "Dutch", "Icelandic", "Faroese", "Czech", "Slovak", "Hungarian", "Tetum", "Pinyin"] },
	{ "letter": "Ù (ù)", "answers": ["Portuguese", "Catalan", "French", "Italian", "Breton", "Scottish Gaelic", "Maltese", "Pinyin"] },
	{ "letter": "Û (û)", "answers": ["French", "Walloon", "Breton"] },
	{ "letter": "Ü (ü)", "answers": ["Spanish", "Portuguese", "Occitan", "Catalan", "French", "German", "Dutch", "Estonian", "Hungarian", "Breton", "Turkish", "Azerbaijani", "Turkmen"] },
	{ "letter": "Ű (ű)", "answers": ["Hungarian"] },
	{ "letter": "Ų (ų)", "answers": ["Lithuanian"] },
	{ "letter": "Ū (ū)", "answers": ["Lithuanian", "Latvian", "Tongan", "Niuean", "Samoan", "Hawaiian", "Tahitian", "Māori", "Pinyin"] },
	{ "letter": "Ů (ů)", "answers": ["Czech"] },
	{ "letter": "Ŭ (ŭ)", "answers": ["Esperanto", "Pinyin"] },
	{ "letter": "Ư (ư)", "answers": ["Vietnamese"] },
	{ "letter": "WH (wh)", "answers": ["Māori"] },
	{ "letter": "XH (xh)", "answers": ["Albanian"] },
	{ "letter": "Ÿ (ÿ)", "answers": ["French"] },
	{ "letter": "Ý (ý)", "answers": ["Dutch", "Icelandic", "Faroese", "Czech", "Slovak", "Turkmen"] },
	{ "letter": "Ž (ž)", "answers": ["Czech", "Slovak", "Slovene", "Croatian", "Bosnian", "Montenegrin", "Serbian", "Lithuanian", "Latvian", "Finnish", "Estonian", "Turkmen"] },
	{ "letter": "Ź (ź)", "answers": ["Polish", "Montenegrin"] },
	{ "letter": "Ż (ż)", "answers": ["Polish", "Maltese"] },
	{ "letter": "ZH (zh)", "answers": ["Albanian"] },
	{ "letter": "ZS (zs)", "answers": ["Hungarian"] },
	{ "letter": "Þ (þ)", "answers": ["Icelandic"] },
	{ "letter": "ʻ", "answers": ["Tongan", "Samoan", "Hawaiian", "Tahitian"] },
	{ "letter": "'", "answers": ["Uzbek"] },
  ]
};

module.exports = LETTERGUESS;