const THAI = {
	"footer": "Write the Latin transliteration of the given Thai consonant letter.",
	"sets": [
    { "letter": "ก", "answers": ["k"] },
    { "letter": "ข", "answers": ["kh", "k"] },
    { "letter": "ฃ", "answers": ["kh", "k"] },
    { "letter": "ค", "answers": ["kh", "k"] },
    { "letter": "ฅ", "answers": ["kh", "k"] },
    { "letter": "ฆ", "answers": ["kh", "k"] },
    { "letter": "ง", "answers": ["ng"] },
    { "letter": "จ", "answers": ["ch", "t"] },
    { "letter": "ฉ", "answers": ["ch'"] },
    { "letter": "ช", "answers": ["ch'", "t"] },
    { "letter": "ซ", "answers": ["s", "t"] },
    { "letter": "ฌ", "answers": ["ch'"] },
    { "letter": "ญ", "answers": ["y", "n"] },
    { "letter": "ฎ", "answers": ["d", "t"] },
    { "letter": "ฏ", "answers": ["t"] },
    { "letter": "ฐ", "answers": ["th", "t"] },
    { "letter": "ฑ", "answers": ["th", "d", "t"] },
    { "letter": "ฒ", "answers": ["th", "t"] },
    { "letter": "ณ", "answers": ["n"] },
    { "letter": "ด", "answers": ["d", "t"] },
    { "letter": "ต", "answers": ["t"] },
    { "letter": "ถ", "answers": ["th", "t"] },
    { "letter": "ท", "answers": ["th", "t"] },
    { "letter": "ธ", "answers": ["th", "t"] },
    { "letter": "น", "answers": ["n"] },
    { "letter": "บ", "answers": ["b", "p"] },
    { "letter": "ป", "answers": ["p"] },
    { "letter": "ผ", "answers": ["ph"] },
    { "letter": "ฝ", "answers": ["f"] },
    { "letter": "พ", "answers": ["ph", "p"] },
    { "letter": "ฟ", "answers": ["f", "p"] },
    { "letter": "ภ", "answers": ["ph", "p"] },
    { "letter": "ม", "answers": ["m"] },
    { "letter": "ย", "answers": ["y", "n"] },
    { "letter": "ร", "answers": ["r", "n"] },
    { "letter": "ล", "answers": ["l", "n"] },
    { "letter": "ว", "answers": ["w"] },
    { "letter": "ศ", "answers": ["s", "t"] },
    { "letter": "ษ", "answers": ["s", "t"] },
    { "letter": "ส", "answers": ["s", "t"] },
    { "letter": "ห", "answers": ["h"] },
    { "letter": "ฬ", "answers": ["l", "n"] },
    { "letter": "อ", "answers": ["-"] },
    { "letter": "ฮ", "answers": ["h"] },
  ]
};

module.exports = THAI;