const USCAPITALS = {
	"footer": "Write the capital of the given US state.",
	"sets": [
    { "letter": "Alabama", "answers": ["Montgomery"] },
    { "letter": "Alaska", "answers": ["Juneau"] },
    { "letter": "Arizona", "answers": ["Phoenix"] },
    { "letter": "Arkansas", "answers": ["Little Rock"] },
    { "letter": "California", "answers": ["Sacramento"] },
    { "letter": "Colorado", "answers": ["Denver"] },
    { "letter": "Connecticut", "answers": ["Hartford"] },
    { "letter": "Delaware", "answers": ["Dover"] },
    { "letter": "Florida", "answers": ["Tallahassee"] },
    { "letter": "Georgia", "answers": ["Atlanta"] },
    { "letter": "Hawaii", "answers": ["Honolulu"] },
    { "letter": "Idaho", "answers": ["Boise"] },
    { "letter": "Illinois", "answers": ["Springfield"] },
    { "letter": "Indiana", "answers": ["Indianapolis"] },
    { "letter": "Iowa", "answers": ["Des Moines"] },
    { "letter": "Kansas", "answers": ["Topeka"] },
    { "letter": "Kentucky", "answers": ["Frankfort"] },
    { "letter": "Louisiana", "answers": ["Baton Rouge"] },
    { "letter": "Maine", "answers": ["Augusta"] },
    { "letter": "Maryland", "answers": ["Annapolis"] },
    { "letter": "Massachusetts", "answers": ["Boston"] },
    { "letter": "Michigan", "answers": ["Lansing"] },
    { "letter": "Minnesota", "answers": ["Saint Paul", "St. Paul", "St Paul"] },
    { "letter": "Mississippi", "answers": ["Jackson"] },
    { "letter": "Missouri", "answers": ["Jefferson City"] },
    { "letter": "Montana", "answers": ["Helena"] },
    { "letter": "Nebraska", "answers": ["Lincoln"] },
    { "letter": "Nevada", "answers": ["Carson City"] },
    { "letter": "New Hampshire", "answers": ["Concord"] },
    { "letter": "New Jersey", "answers": ["Trenton"] },
    { "letter": "New Mexico", "answers": ["Santa Fe"] },
    { "letter": "New York", "answers": ["Albany"] },
    { "letter": "North Carolina", "answers": ["Raleigh"] },
    { "letter": "North Dakota", "answers": ["Bismarck"] },
    { "letter": "Ohio", "answers": ["Columbus"] },
    { "letter": "Oklahoma", "answers": ["Oklahoma City"] },
    { "letter": "Oregon", "answers": ["Salem"] },
    { "letter": "Pennsylvania", "answers": ["Harrisburg"] },
    { "letter": "Rhode Island", "answers": ["Providence"] },
    { "letter": "South Carolina", "answers": ["Columbia"] },
    { "letter": "South Dakota", "answers": ["Pierre"] },
    { "letter": "Tennessee", "answers": ["Nashville"] },
    { "letter": "Texas", "answers": ["Austin"] },
    { "letter": "Utah", "answers": ["Salt Lake City"] },
    { "letter": "Vermont", "answers": ["Montpelier"] },
    { "letter": "Virginia", "answers": ["Richmond"] },
    { "letter": "Washington", "answers": ["Olympia"] },
    { "letter": "West Virginia", "answers": ["Charleston"] },
    { "letter": "Wisconsin", "answers": ["Madison"] },
    { "letter": "Wyoming", "answers": ["Cheyenne"] },
  ]
};

module.exports = USCAPITALS;