const USFLAGS = {
  "title": "Guess the state",
  "footer": "Write the US state whose flag this is.",
  "sets": [
    { "letter": "https://i.imgur.com/MNIwSpt.png", "answers": ["Alabama", "AL"] },
    { "letter": "https://i.imgur.com/0NqEghR.png", "answers": ["Alaska", "AK"] },
    { "letter": "https://i.imgur.com/DcvZaVU.png", "answers": ["Arizona", "AZ"] },
    { "letter": "https://i.imgur.com/rJaG7vt.png", "answers": ["Arkansas", "AR"] },
    { "letter": "https://i.imgur.com/dyuT6JL.png", "answers": ["California", "CA"] },
    { "letter": "https://i.imgur.com/bGcRZ4u.png", "answers": ["Colorado", "CO"] },
    { "letter": "https://i.imgur.com/mcSIgHf.png", "answers": ["Connecticut", "CT"] },
    { "letter": "https://i.imgur.com/BQUO2kv.png", "answers": ["Delaware", "DE"] },
    { "letter": "https://i.imgur.com/GKhGohy.png", "answers": ["Florida", "FL"] },
    { "letter": "https://i.imgur.com/zSecYaD.png", "answers": ["Georgia", "GA"] },
    { "letter": "https://i.imgur.com/n4qDBu6.png", "answers": ["Hawaii", "HI"] },
    { "letter": "https://i.imgur.com/2vMlawb.png", "answers": ["Idaho", "ID"] },
    { "letter": "https://i.imgur.com/Qr0Oi0j.png", "answers": ["Illinois", "IL"] },
    { "letter": "https://i.imgur.com/Jq5o79G.png", "answers": ["Indiana", "IN"] },
    { "letter": "https://i.imgur.com/BA5HNeK.png", "answers": ["Iowa", "IA"] },
    { "letter": "https://i.imgur.com/SAAVqsW.png", "answers": ["Kansas", "KS"] },
    { "letter": "https://i.imgur.com/sk92VpL.png", "answers": ["Kentucky", "KY"] },
    { "letter": "https://i.imgur.com/Kj96f1N.png", "answers": ["Louisiana", "LA"] },
    { "letter": "https://i.imgur.com/aS2qNQN.png", "answers": ["Maine", "ME"] },
    { "letter": "https://i.imgur.com/QM7dkYT.png", "answers": ["Maryland", "MD"] },
    { "letter": "https://i.imgur.com/MfRqjeX.png", "answers": ["Massachusetts", "MA"] },
    { "letter": "https://i.imgur.com/jja8j52.png", "answers": ["Michigan", "MI"] },
    { "letter": "https://i.imgur.com/15AQlRk.png", "answers": ["Minnesota", "MN"] },
    { "letter": "https://i.imgur.com/oQHyQws.png", "answers": ["Mississippi", "MS"] },
    { "letter": "https://i.imgur.com/1HHr5oG.png", "answers": ["Missouri", "MO"] },
    { "letter": "https://i.imgur.com/HaAZj6Y.png", "answers": ["Montana", "MT"] },
    { "letter": "https://i.imgur.com/SnksqBw.png", "answers": ["Nebraska", "NE"] },
    { "letter": "https://i.imgur.com/hjRvn52.png", "answers": ["Nevada", "NV"] },
    { "letter": "https://i.imgur.com/lThE9Di.png", "answers": ["New Hampshire", "NH"] },
    { "letter": "https://i.imgur.com/6DLT65I.png", "answers": ["New Jersey", "NJ"] },
    { "letter": "https://i.imgur.com/tLClqdC.png", "answers": ["New Mexico", "NM"] },
    { "letter": "https://i.imgur.com/GdqyZW4.png", "answers": ["New York", "NY"] },
    { "letter": "https://i.imgur.com/ikmFTSm.png", "answers": ["North Carolina", "NC"] },
    { "letter": "https://i.imgur.com/5CddkJS.png", "answers": ["North Dakota", "ND"] },
    { "letter": "https://i.imgur.com/tAXAMtl.png", "answers": ["Ohio", "OH"] },
    { "letter": "https://i.imgur.com/HrJCht0.png", "answers": ["Oklahoma", "OK"] },
    { "letter": "https://i.imgur.com/wUcJHlk.png", "answers": ["Oregon", "OR"] },
    { "letter": "https://i.imgur.com/flmu3BW.png", "answers": ["Pennsylvania", "PA"] },
    { "letter": "https://i.imgur.com/X6OM4IZ.png", "answers": ["Rhode Island", "RI"] },
    { "letter": "https://i.imgur.com/SQdhcHE.png", "answers": ["South Carolina", "SC"] },
    { "letter": "https://i.imgur.com/r3wmwS3.png", "answers": ["South Dakota", "SD"] },
    { "letter": "https://i.imgur.com/PbBa8k8.png", "answers": ["Tennessee", "TN"] },
    { "letter": "https://i.imgur.com/pUoVP6z.png", "answers": ["Texas", "TX"] },
    { "letter": "https://i.imgur.com/o2DY27u.png", "answers": ["Utah", "UT"] },
    { "letter": "https://i.imgur.com/p2eVrQy.png", "answers": ["Vermont", "VT"] },
    { "letter": "https://i.imgur.com/t5FGBGC.png", "answers": ["Virginia", "VA"] },
    { "letter": "https://i.imgur.com/aHDtXXq.png", "answers": ["Washington", "WA"] },
    { "letter": "https://i.imgur.com/k1AG8hs.png", "answers": ["West Virginia", "WV"] },
    { "letter": "https://i.imgur.com/dLUvQ6u.png", "answers": ["Wisconsin", "WI"] },
    { "letter": "https://i.imgur.com/Rpe0mLT.png", "answers": ["Wyoming", "WY"] },
  ]
};

module.exports = USFLAGS;