const USSHIELDS = {
	"title": "Guess the state",
  "footer": "Write the state/territory the highway shield is from.",
  "sets": [
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Alabama_3.svg/480px-Alabama_3.svg.png", "answers": ["Alabama", "AL"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Alaska_1_shield.svg/480px-Alaska_1_shield.svg.png", "answers": ["Alaska", "AK"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Arizona_87.svg/480px-Arizona_87.svg.png", "answers": ["Arizona", "AZ"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Arkansas_7.svg/480px-Arkansas_7.svg.png", "answers": ["Arkansas", "AR"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/California_1.svg/461px-California_1.svg.png", "answers": ["California", "CA"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Colorado_14.svg/480px-Colorado_14.svg.png", "answers": ["Colorado", "CO"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Connecticut_Highway_15.svg/480px-Connecticut_Highway_15.svg.png", "answers": ["Connecticut", "CT"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Elongated_circle_1.svg/480px-Elongated_circle_1.svg.png", "answers": ["Delaware", "DE"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Florida_5.svg/480px-Florida_5.svg.png", "answers": ["Florida", "FL"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Georgia_11.svg/480px-Georgia_11.svg.png", "answers": ["Georgia", "GA"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/HI-11.svg/480px-HI-11.svg.png", "answers": ["Hawaii", "HI"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Idaho_75.svg/480px-Idaho_75.svg.png", "answers": ["Idaho", "ID"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Illinois_1.svg/480px-Illinois_1.svg.png", "answers": ["Illinois", "IL"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Indiana_37.svg/480px-Indiana_37.svg.png", "answers": ["Indiana", "IN"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Circle_sign_3.svg/480px-Circle_sign_3.svg.png", "answers": ["Iowa", "IA"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/K-4.svg/480px-K-4.svg.png", "answers": ["Kansas", "KS"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Elongated_circle_80.svg/480px-Elongated_circle_80.svg.png", "answers": ["Kentucky", "KY"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Louisiana_1_%282008%29.svg/480px-Louisiana_1_%282008%29.svg.png", "answers": ["Louisiana", "LA"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Maine_11.svg/480px-Maine_11.svg.png", "answers": ["Maine", "ME"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/MD_Route_2.svg/480px-MD_Route_2.svg.png", "answers": ["Maryland", "MD"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/MA_Route_28.svg/480px-MA_Route_28.svg.png", "answers": ["Massachusetts", "MA"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/M-28.svg/480px-M-28.svg.png", "answers": ["Michigan", "MI"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/MN-1.svg/480px-MN-1.svg.png", "answers": ["Minnesota", "MN"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Circle_sign_15.svg/480px-Circle_sign_15.svg.png", "answers": ["Mississippi", "MS"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/MO-5.svg/480px-MO-5.svg.png", "answers": ["Missouri", "MO"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/MT-200.svg/600px-MT-200.svg.png", "answers": ["Montana", "MT"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/N-92.svg/480px-N-92.svg.png", "answers": ["Nebraska", "NE"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Nevada_318.svg/480px-Nevada_318.svg.png", "answers": ["Nevada", "NV"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/NH_Route_16.svg/480px-NH_Route_16.svg.png", "answers": ["New Hampshire", "NH"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Circle_sign_47.svg/480px-Circle_sign_47.svg.png", "answers": ["New Jersey", "NJ"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/New_Mexico_120.svg/480px-New_Mexico_120.svg.png", "answers": ["New Mexico", "NM"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/NY-17.svg/480px-NY-17.svg.png", "answers": ["New York", "NY"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/NC_24.svg/480px-NC_24.svg.png", "answers": ["North Carolina", "NC"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/ND-200_%282015%29.svg/600px-ND-200_%282015%29.svg.png", "answers": ["North Dakota", "ND"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/OH-7.svg/480px-OH-7.svg.png", "answers": ["Ohio", "OH"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Oklahoma_State_Highway_3.svg/480px-Oklahoma_State_Highway_3.svg.png", "answers": ["Oklahoma", "OK"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/OR_140.svg/600px-OR_140.svg.png", "answers": ["Oregon", "OR"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/PA-18.svg/480px-PA-18.svg.png", "answers": ["Pennsylvania", "PA"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Rhode_Island_138.svg/600px-Rhode_Island_138.svg.png", "answers": ["Rhode Island", "RI"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/South_Carolina_9.svg/600px-South_Carolina_9.svg.png", "answers": ["South Carolina", "SC"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/SD_20.svg/480px-SD_20.svg.png", "answers": ["South Dakota", "SD"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Tennessee_1.svg/600px-Tennessee_1.svg.png", "answers": ["Tennessee", "TN"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Texas_6.svg/480px-Texas_6.svg.png", "answers": ["Texas", "TX"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Utah_24.svg/480px-Utah_24.svg.png", "answers": ["Utah", "UT"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Vermont_30.svg/480px-Vermont_30.svg.png", "answers": ["Vermont", "VT"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Virginia_40.svg/480px-Virginia_40.svg.png", "answers": ["Virginia", "VA"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/WA-20.svg/480px-WA-20.svg.png", "answers": ["Washington", "WA"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/WV-20.svg/480px-WV-20.svg.png", "answers": ["West Virginia", "WV"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/WIS_35.svg/480px-WIS_35.svg.png", "answers": ["Wisconsin", "WI"] },
    { "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/WY-59.svg/478px-WY-59.svg.png", "answers": ["Wyoming", "WY"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/American_Samoa_Highway_001.svg/480px-American_Samoa_Highway_001.svg.png", "answers": ["American Samoa", "AS"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/DC-295.svg/384px-DC-295.svg.png", "answers": ["District of Columbia", "DC", "D.C.", "Washington DC", "Washington D.C."] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Guam_Route_1.svg/343px-Guam_Route_1.svg.png", "answers": ["Guam", "GU"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Northern_Mariana_Islands_30.svg/480px-Northern_Mariana_Islands_30.svg.png", "answers": ["Northern Mariana Islands", "Northern Marianas", "NMI", "MP"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/PR_primary_1.svg/480px-PR_primary_1.svg.png", "answers": ["Puerto Rico", "PR"] },
	{ "letter": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Circle_sign_10.svg/480px-Circle_sign_10.svg.png", "answers": ["US Virgin Islands", "Virgin Islands", "VI", "USVI"] },
  ]
};

module.exports = USSHIELDS;