const CHINESE4 = {
	"footer": "Write the Chinese character in pinyin or translate it.",
	"sets": [
    {"letter": "爱情 / 愛情", "answers": ["ai4qing2","àiqíng","love",] },
    {"letter": "暗 / 暗", "answers": ["an4","àn","dark",] },
    {"letter": "安排 / 安排", "answers": ["an1pai2","ānpái","plan","to plan","to arrange",] },
    {"letter": "安全 / 安全", "answers": ["an1quan2","ānquán","safety","safe","secure",] },
    {"letter": "按时 / 按時", "answers": ["an4shi2","ànshí","on time","on schedule",] },
    {"letter": "按照 / 按照", "answers": ["an4zhao4","ànzhào","according to",] },
    {"letter": "抱 / 抱", "answers": ["bao4","bào","to hug","to embrace","to hold",] },
    {"letter": "报道 / 報道", "answers": ["bao4dao4","bàodào","report","to report",] },
    {"letter": "保护 / 保護", "answers": ["bao3hu4","bǎohù","protection","to protect","to safeguard",] },
    {"letter": "包括 / 包括", "answers": ["bao1kuo4","bāokuò","to include","to consist of",] },
    {"letter": "报名 / 報名", "answers": ["bao4ming2","bàomíng","to sign up","to register",] },
    {"letter": "抱歉 / 抱歉", "answers": ["bao4qian4","bàoqiàn","sorry","my apologies",] },
    {"letter": "保证 / 保證", "answers": ["bao3zheng4","bǎozhèng","guarantee","to guarantee","to ensure","to assure",] },
    {"letter": "倍 / 倍", "answers": ["bei4","bèi","Measure word for times","-fold",] },
    {"letter": "笨 / 笨", "answers": ["ben4","bèn","stupid","foolish",] },
    {"letter": "本来 / 本來", "answers": ["ben3lai2","běnlái","original","originally","at first",] },
    {"letter": "笔记本 / 筆記本", "answers": ["bi3ji4ben3","bǐjìběn","notebook",] },
    {"letter": "毕业 / 畢業", "answers": ["bi4ye4","bìyè","to graduate","to finish school",] },
    {"letter": "遍 / 遍", "answers": ["bian4","biàn","all over","Measure word for a time",] },
    {"letter": "表达 / 表達", "answers": ["biao3da2","biǎodá","to express","to convey",] },
    {"letter": "表格 / 表格", "answers": ["biao3ge2","biǎogé","form","table",] },
    {"letter": "表扬 / 表揚", "answers": ["biao3yang2","biǎoyáng","to praise","to commend",] },
    {"letter": "标准 / 標準", "answers": ["biao1zhun3","biāozhǔn","standard","norm","standard",] },
    {"letter": "饼干 / 餅乾", "answers": ["bing3gan1","bǐnggān","buscuit","cookie",] },
    {"letter": "并且 / 並且", "answers": ["bing4qie3","bìngqiě","and","besides","moreover",] },
    {"letter": "博士 / 博士", "answers": ["bo2shi4","bóshì","doctor","PhD","Ph.D.",] },
    {"letter": "不但 / 不但", "answers": ["bu4dan4","búdàn","not only",] },
    {"letter": "不得不 / 不得不", "answers": ["bu4de2bu4","bùdébù","to have to","cannot but",] },
    {"letter": "部分 / 部分", "answers": ["bu4fen5","bùfen","part","section",] },
    {"letter": "不管 / 不管", "answers": ["bu4guan3","bùguǎn","regardless of","no matter what/how",] },
    {"letter": "不过 / 不過", "answers": ["bu4guo4","búguò","only","just","no more than","but","however",] },
    {"letter": "不仅 / 不僅", "answers": ["bu4jin3","bùjǐn","not only","not just",] },
    {"letter": "擦 / 擦", "answers": ["ca1","cā","to wipe","to rub","to erase",] },
    {"letter": "猜 / 猜", "answers": ["cai1","cāi","to guess",] },
    {"letter": "材料 / 材料", "answers": ["cai2liao4","cáiliào","material","data","stuff",] },
    {"letter": "参观 / 參觀", "answers": ["can1guan1","cānguān","to visit","to look around",] },
    {"letter": "差不多 / 差不多", "answers": ["cha4bu5duo1","chàbuduō","almost","more or less",] },
    {"letter": "尝 / 嘗", "answers": ["chang2","cháng","to taste","once",] },
    {"letter": "场 / 場", "answers": ["chang3","chǎng","field","place","Measure word","Measure word for events, happenings, etc.",] },
    {"letter": "长城 / 長城", "answers": ["chang2cheng2","Chángchéng","the Great Wall",] },
    {"letter": "长江 / 長江", "answers": ["chang2jiang1","Chángjiāng","Yangtze river",] },
    {"letter": "吵 / 吵", "answers": ["chao3","chǎo","to quarrel","noisy",] },
    {"letter": "超过 / 超過", "answers": ["chao1guo4","chāoguò","to surpass","to exceed",] },
    {"letter": "成功 / 成功", "answers": ["cheng2gong1","chénggōng","success","to succeed",] },
    {"letter": "诚实 / 誠實", "answers": ["cheng2shi2","chéngshí","honest","truthful",] },
    {"letter": "成熟 / 成熟", "answers": ["cheng2shu2","chéngshú","mature",] },
    {"letter": "成为 / 成為", "answers": ["cheng2wei2","chéngwéi","to become","to turn into",] },
    {"letter": "乘坐 / 乘坐", "answers": ["cheng2zuo4","chéngzuò","to ride in a vehicle","to ride",] },
    {"letter": "吃惊 / 吃驚", "answers": ["chi1jing1","chījīng","to be startled","to be shocked","to be amazed",] },
    {"letter": "重新 / 重新", "answers": ["chong2xin1","chóngxīn","again",] },
    {"letter": "抽烟 / 抽煙", "answers": ["chou1yan1","chōuyān","to smoke",] },
    {"letter": "出差 / 出差", "answers": ["chu1chai1","chūchāi","to go on a business trip",] },
    {"letter": "出发 / 出發", "answers": ["chu1fa1","chūfā","to leave","to set out",] },
    {"letter": "出生 / 出生", "answers": ["chu1sheng1","chūshēng","to be born",] },
    {"letter": "传真 / 傳真", "answers": ["chuan2zhen1","chuánzhēn","fax",] },
    {"letter": "窗户 / 窗戶", "answers": ["chuang1hu5","chuānghu","window",] },
    {"letter": "词典 / 詞典", "answers": ["ci2dian3","cídiǎn","dictionary",] },
    {"letter": "从来 / 從來", "answers": ["cong2lai2","cónglái","always","ever since","at all times",] },
    {"letter": "粗心 / 粗心", "answers": ["cu1xin1","cūxīn","careless","thoughtless",] },
    {"letter": "答案 / 答案", "answers": ["da2an4","dáàn","answer","solution",] },
    {"letter": "打扮 / 打扮", "answers": ["da3ban5","dǎban","style of dressing","to decorate","to dress up",] },
    {"letter": "大概 / 大概", "answers": ["da4gai4","dàgài","probably","roughly",] },
    {"letter": "打扰 / 打擾", "answers": ["da3rao3","dǎrǎo","to disturb",] },
    {"letter": "大使馆 / 大使館", "answers": ["da4shi3guan3","dàshǐguǎn","embassy",] },
    {"letter": "打印 / 打印", "answers": ["da3yin4","dǎyìn","to print","to seal","to stamp",] },
    {"letter": "大约 / 大約", "answers": ["da4yue1","dàyuē","approximately",] },
    {"letter": "打折 / 打折", "answers": ["da3zhe2","dǎzhé","to give discount",] },
    {"letter": "打针 / 打針", "answers": ["da3zhen1","dǎzhēn","to inject",] },
    {"letter": "戴 / 戴", "answers": ["dai4","dài","to put on","to wear","to respect","to support",] },
    {"letter": "代表 / 代表", "answers": ["dai4biao3","dàibiǎo","representative","to represent",] },
    {"letter": "大夫 / 大夫", "answers": ["dai4fu5","dàifu","doctor",] },
    {"letter": "代替 / 代替", "answers": ["dai4ti4","dàitì","replacement","to replace","to substitute","instead of",] },
    {"letter": "当 / 當", "answers": ["dang4","dāng","to act as","to administer","should","ought","equal","when","during",] },
    {"letter": "当地 / 當地", "answers": ["dang1di4","dāngdì","locality","local",] },
    {"letter": "当时 / 當時", "answers": ["dang1shi2","dāngshí","at that time","then",] },
    {"letter": "刀 / 刀", "answers": ["dao1","dāo","knife",] },
    {"letter": "到处 / 到處", "answers": ["dao4chu4","dàochù","everywhere","at all places",] },
    {"letter": "到底 / 到底", "answers": ["dao4di3","dàodǐ","finally","in the end",] },
    {"letter": "道歉 / 道歉", "answers": ["dao4qian4","dàoqiàn","to apologize",] },
    {"letter": "导游 / 導遊", "answers": ["dao3you2","dǎoyóu","tour guide",] },
    {"letter": "得意 / 得意", "answers": ["de2yi4","déyì","pleased with oneself",] },
    {"letter": "得 / 得", "answers": ["dei3","děi","to have to",] },
    {"letter": "等 / 等", "answers": ["deng3","děng","etc.","and so on",] },
    {"letter": "底 / 底", "answers": ["di3","dǐ","background","end","bottom","base",] },
    {"letter": "地球 / 地球", "answers": ["di4qiu2","dìqiú","earth","globe",] },
    {"letter": "地址 / 地址", "answers": ["di4zhi3","dìzhǐ","address",] },
    {"letter": "掉 / 掉", "answers": ["diao4","diào","to fall","to drop","to lose","to turn",] },
    {"letter": "调查 / 調查", "answers": ["diao4cha2","diàochá","investigation","survey","to investigate","to survey",] },
    {"letter": "丢 / 丟", "answers": ["diu1","diū","to lose","to throw",] },
    {"letter": "动作 / 動作", "answers": ["dong4zuo4","dòngzuò","movement",] },
    {"letter": "堵车 / 堵車", "answers": ["du3che1","dǔchē","traffic jam",] },
    {"letter": "肚子 / 肚子", "answers": ["du4zi5","dùzi","belly","abdomen",] },
    {"letter": "断 / 斷", "answers": ["duan4","duàn","to cut off","to break","to judge","to decide","absolutely","definitely",] },
    {"letter": "对 / 對", "answers": ["dui4","duì","for","to","towards",] },
    {"letter": "对话 / 對話", "answers": ["dui4hua4","duìhuà","dialog",] },
    {"letter": "对面 / 對面", "answers": ["dui4mian4","duìmiàn","opposite",] },
    {"letter": "顿 / 頓", "answers": ["dun4","dùn","pause","to stop","to pause","to arrange",] },
    {"letter": "朵 / 朵", "answers": ["duo3","duǒ","Measure word","Measure word for flowers, clouds, etc.",] },
    {"letter": "而 / 而", "answers": ["er2","ér","and","but","yet",] },
    {"letter": "儿童 / 兒童", "answers": ["er2tong2","értóng","child",] },
    {"letter": "发 / 發", "answers": ["fa1","fā","to send out","to issue","to develop",] },
    {"letter": "法律 / 法律", "answers": ["fa3lü4","fǎlǜ","law",] },
    {"letter": "发生 / 發生", "answers": ["fa1sheng1","fāshēng","to happen","to occur","to take place",] },
    {"letter": "发展 / 發展", "answers": ["fa1zhan3","fāzhǎn","development","growth","to develop","to grow",] },
    {"letter": "反对 / 反對", "answers": ["fan3dui4","fǎnduì","to fight against","to oppose",] },
    {"letter": "烦恼 / 煩惱", "answers": ["fan2nao3","fánnǎo","worries","worried","troubled",] },
    {"letter": "范围 / 範圍", "answers": ["fan4wei2","fànwéi","scope limit","range",] },
    {"letter": "翻译 / 翻譯", "answers": ["fan1yi4","fānyì","translation","translator","to translate",] },
    {"letter": "反映 / 反映", "answers": ["fan3ying4","fǎnyìng","reflection","to reflect","to mirror",] },
    {"letter": "方法 / 方法", "answers": ["fang1fa3","fāngfǎ","method","way",] },
    {"letter": "方面 / 方面", "answers": ["fang1mian4","fāngmiàn","aspect","respect",] },
    {"letter": "放弃 / 放棄", "answers": ["fang4qi4","fàngqì","to give up",] },
    {"letter": "放暑假 / 放暑假", "answers": ["fang4","fàngshǔjià","to take summer vacation",] },
    {"letter": "访问 / 訪問", "answers": ["fang3wen4","fǎngwèn","visit","to visit","to interview",] },
    {"letter": "方向 / 方向", "answers": ["fang1xiang4","fāngxiàng","direction","orientation",] },
    {"letter": "份 / 份", "answers": ["fen4","fèn","part","share","portion","copy","Measure word","Measure word for newspapers, papers, reports, contracts",] },
    {"letter": "分之 / 分之", "answers": ["fen1zhi1","fēnzhī","used for fractions and percentages",] },
    {"letter": "丰富 / 豐富", "answers": ["feng1fu4","fēngfù","rich","plentiful",] },
    {"letter": "风景 / 風景", "answers": ["feng1jing3","fēngjǐng","scenery","landscape",] },
    {"letter": "否则 / 否則", "answers": ["fou3ze2","fǒuzé","otherwise",] },
    {"letter": "富 / 富", "answers": ["fu4","fù","rich",] },
    {"letter": "符合 / 符合", "answers": ["fu2he2","fúhé","to accord with","to conform to",] },
    {"letter": "父亲 / 父親", "answers": ["fu4qin1","fùqīn","father",] },
    {"letter": "复印 / 複印", "answers": ["fu4yin4","fùyìn","to copy","to photocopy","to make a copy",] },
    {"letter": "复杂 / 複雜", "answers": ["fu4za2","fùzá","complicated","complex",] },
    {"letter": "负责 / 負責", "answers": ["fu4ze2","fùzé","to be responsible for",] },
    {"letter": "改变 / 改變", "answers": ["gai3bian4","gǎibiàn","to change",] },
    {"letter": "干 / 干", "answers": ["gan4","gàn","to do","to work",] },
    {"letter": "干杯 / 乾杯", "answers": ["gan1bei1","gānbēi","Cheers",] },
    {"letter": "感动 / 感動", "answers": ["gan3dong4","gǎndòng","to move somebody","to touch","to touch emotionally",] },
    {"letter": "感觉 / 感覺", "answers": ["gan3jue2","gǎnjué","feeling","sense","to feel",] },
    {"letter": "感情 / 感情", "answers": ["gan3qing2","gǎnqíng","emotion","feeling",] },
    {"letter": "感谢 / 感謝", "answers": ["gan3xie4","gǎnxiè","gratitude","to thank","to be grateful",] },
    {"letter": "干燥 / 乾燥", "answers": ["gan1zao4","gānzào","dry",] },
    {"letter": "刚刚 / 剛剛", "answers": ["gang1gang5","gānggāng","just now","a moment ago",] },
    {"letter": "高级 / 高級", "answers": ["gao1ji2","gāojí","high level","high grade","advanced",] },
    {"letter": "各 / 各", "answers": ["ge4","gè","each","every",] },
    {"letter": "个子 / 個子", "answers": ["ge4zi5","gèzi","height","stature",] },
    {"letter": "工具 / 工具", "answers": ["gong1ju4","gōngjù","tool","utensil",] },
    {"letter": "公里 / 公里", "answers": ["gong1li3","gōnglǐ","kilometer","km",] },
    {"letter": "共同 / 共同", "answers": ["gong4tong2","gòngtóng","common","joint","together",] },
    {"letter": "工资 / 工資", "answers": ["gong1zi1","gōngzī","salary","wages",] },
    {"letter": "够 / 夠", "answers": ["gou4","gòu","to reach","to be enough","be enough","enough",] },
    {"letter": "购物 / 購物", "answers": ["gou4wu4","gòuwù","to go shopping",] },
    {"letter": "孤单 / 孤單", "answers": ["gu1dan1","gūdān","lone","lonely",] },
    {"letter": "估计 / 估計", "answers": ["gu1ji4","gūjì","to estimate",] },
    {"letter": "顾客 / 顧客", "answers": ["gu4ke4","gùkè","client","customer",] },
    {"letter": "鼓励 / 鼓勵", "answers": ["gu3li4","gǔlì","to encourage","to urge",] },
    {"letter": "故意 / 故意", "answers": ["gu4yi4","gùyì","on purpose","deliberately",] },
    {"letter": "鼓掌 / 鼓掌", "answers": ["gu3zhang3","gǔzhǎng","to applaud",] },
    {"letter": "挂 / 掛", "answers": ["gua4","guà","to hang","to hang up",] },
    {"letter": "关键 / 關鍵", "answers": ["guan1jian4","guānjiàn","key","crucial point",] },
    {"letter": "管理 / 管理", "answers": ["guan3li3","guǎnlǐ","management","to manage",] },
    {"letter": "观众 / 觀眾", "answers": ["guan1zhong4","guānzhòng","audience","spectators",] },
    {"letter": "逛 / 逛", "answers": ["guang4","guàng","to stroll",] },
    {"letter": "光 / 光", "answers": ["guang1","guāng","light","ray","naked","only","merely",] },
    {"letter": "广播 / 廣播", "answers": ["guang3bo1","guǎngbō","broadcasting","to broadcast",] },
    {"letter": "广告 / 廣告", "answers": ["guang3gao4","guǎnggào","advertisement","to advertise",] },
    {"letter": "规定 / 規定", "answers": ["gui1ding4","guīdìng","regulations","provision","to fix","to stipulate",] },
    {"letter": "过 / 過", "answers": ["guo5","guò","to pass","to cross","to spend time",] },
    {"letter": "过程 / 過程", "answers": ["guo4cheng2","guòchéng","process","course",] },
    {"letter": "国际 / 國際", "answers": ["guo2ji4","guójì","international",] },
    {"letter": "果然 / 果然", "answers": ["guo3ran2","guǒrán","as expected",] },
    {"letter": "害羞 / 害羞", "answers": ["hai4xiu1","hàixiū","shy",] },
    {"letter": "海洋 / 海洋", "answers": ["hai3yang2","hǎiyáng","ocean",] },
    {"letter": "汗 / 汗", "answers": ["han4","hàn","sweat",] },
    {"letter": "寒假 / 寒假", "answers": ["han2jia4","hánjià","winter vacation",] },
    {"letter": "航班 / 航班", "answers": ["hang2ban1","hángbān","scheduled flight","flight number",] },
    {"letter": "好处 / 好處", "answers": ["hao3chu3","hǎochu","benefit","advantage",] },
    {"letter": "号码 / 號碼", "answers": ["hao4ma3","hàomǎ","number",] },
    {"letter": "好像 / 好像", "answers": ["hao3xiang4","hǎoxiàng","to seem","to be like","look like",] },
    {"letter": "合格 / 合格", "answers": ["he2ge2","hégé","qualified",] },
    {"letter": "合适 / 合適", "answers": ["he2shi4","héshì","suitable","appropriate",] },
    {"letter": "盒子 / 盒子", "answers": ["he2zi5","hézi","box","case",] },
    {"letter": "厚 / 厚", "answers": ["hou4","hòu","thick","deep",] },
    {"letter": "后悔 / 後悔", "answers": ["hou4hui3","hòuhuǐ","to regret","to repent",] },
    {"letter": "后来 / 後來", "answers": ["hou4lai2","hòulái","afterwards","later",] },
    {"letter": "猴子 / 猴子", "answers": ["hou2zi5","hóuzi","monkey",] },
    {"letter": "忽然 / 忽然", "answers": ["hu1ran2","hūrán","suddenly",] },
    {"letter": "护士 / 護士", "answers": ["hu4shi5","hùshi","nurse",] },
    {"letter": "互相 / 互相", "answers": ["hu4xiang1","hùxiāng","each other",] },
    {"letter": "怀疑 / 懷疑", "answers": ["huai2yi2","huáiyí","doubt","suspicion","to doubt","to suspect",] },
    {"letter": "回忆 / 回憶", "answers": ["hui2yi4","huíyì","recollection","to recall","to recollect",] },
    {"letter": "火 / 火", "answers": ["huo3","huǒ","fire",] },
    {"letter": "获得 / 獲得", "answers": ["huo4de2","huòdé","to obtain","to acquire",] },
    {"letter": "活动 / 活動", "answers": ["huo2dong4","huódòng","activity","to move about","active",] },
    {"letter": "活泼 / 活潑", "answers": ["huo2po5","huópō","lively","vivid",] },
    {"letter": "寄 / 寄", "answers": ["ji4","jì","to send","to mail",] },
    {"letter": "基础 / 基礎", "answers": ["ji1chu3","jīchǔ","base","foundation","basis",] },
    {"letter": "激动 / 激動", "answers": ["ji1dong4","jīdòng","to excite","exciting",] },
    {"letter": "集合 / 集合", "answers": ["ji2he2","jíhé","congregation","to gather","to assemble",] },
    {"letter": "计划 / 計劃", "answers": ["ji4hua4","jìhuà","plan","project","program","to plan",] },
    {"letter": "积极 / 積極", "answers": ["ji1ji2","jījí","positive","active",] },
    {"letter": "积累 / 積累", "answers": ["ji1lei3","jīlěi","accumulation","to accumulate",] },
    {"letter": "极其 / 極其", "answers": ["ji2qi2","jíqí","extremely",] },
    {"letter": "既然 / 既然", "answers": ["ji4ran2","jìrán","this being the case",] },
    {"letter": "及时 / 及時", "answers": ["ji2shi2","jíshí","in time","without delay",] },
    {"letter": "即使 / 即使", "answers": ["ji2shi3","jíshǐ","even if","even thoug",] },
    {"letter": "技术 / 技術", "answers": ["ji4shu4","jìshù","technology","skill","technique",] },
    {"letter": "继续 / 繼續", "answers": ["ji4xu4","jìxù","continuation","to continue","to go on",] },
    {"letter": "记者 / 記者", "answers": ["ji4zhe3","jìzhě","reporter","journalist",] },
    {"letter": "假 / 假", "answers": ["jia3","jiǎ","fake","FALSE",] },
    {"letter": "加班 / 加班", "answers": ["jia1ban1","jiābān","to work overtime",] },
    {"letter": "价格 / 價格", "answers": ["jia4ge2","jiàgé","price",] },
    {"letter": "家具 / 傢具", "answers": ["jia1ju4","jiājù","furniture",] },
    {"letter": "加油站 / 加油站", "answers": ["jia1you2zhan4","jiāyóuzhàn","gas station",] },
    {"letter": "坚持 / 堅持", "answers": ["jian1chi2","jiānchí","to stick to","to persist in","to insist on",] },
    {"letter": "减肥 / 減肥", "answers": ["jian3fei2","jiǎnféi","to lose weight",] },
    {"letter": "减少 / 減少", "answers": ["jian3shao3","jiǎnshǎo","to reduce","to decrease",] },
    {"letter": "降低 / 降低", "answers": ["jiang4di1","jiàngdī","to reduce","to lower",] },
    {"letter": "奖金 / 獎金", "answers": ["jiang3jin1","jiǎngjīn","premium","award money","bonus",] },
    {"letter": "将来 / 將來", "answers": ["jiang1lai2","jiānglái","future","in the future",] },
    {"letter": "交 / 交", "answers": ["jiao1","jiāo","to hand over","to intersect","to associate with",] },
    {"letter": "骄傲 / 驕傲", "answers": ["jiao1ao4","jiāoào","to be proud of sth.","arrogant","conceited",] },
    {"letter": "交流 / 交流", "answers": ["jiao1liu2","jiāoliú","communication","exchange","to exchange","to communicate",] },
    {"letter": "教授 / 教授", "answers": ["jiao4shou4","jiàoshòu","professor","to instruct","to lecture on",] },
    {"letter": "交通 / 交通", "answers": ["jiao1tong1","jiāotōng","traffic",] },
    {"letter": "教育 / 教育", "answers": ["jiao4yu4","jiàoyù","educatione","to teach",] },
    {"letter": "饺子 / 餃子", "answers": ["jiao3zi5","jiǎozi","dumpling",] },
    {"letter": "结果 / 結果", "answers": ["jie2guo3","jiéguǒ","result","outcome","finally","at last",] },
    {"letter": "解释 / 解釋", "answers": ["jie3shi4","jiěshì","explanation","to explain",] },
    {"letter": "接受 / 接受", "answers": ["jie1shou4","jiēshòu","to accept","to receive",] },
    {"letter": "节约 / 節約", "answers": ["jie2yue1","jiéyuē","to economize","to conserve",] },
    {"letter": "尽管 / 儘管", "answers": ["jin3guan3","jǐnguǎn","unhesitatingly","in spite of","although","despite",] },
    {"letter": "进行 / 進行", "answers": ["jin4xing2","jìnxíng","to be in progress","be underway",] },
    {"letter": "紧张 / 緊張", "answers": ["jin3zhang1","jǐnzhāng","nervous","tense","in short supply",] },
    {"letter": "禁止 / 禁止", "answers": ["jin4zhi3","jìnzhǐ","to prohibit","to forbid","to ban",] },
    {"letter": "精彩 / 精彩", "answers": ["jing1cai3","jīngcǎi","brilliant","excellent","splendid",] },
    {"letter": "警察 / 警察", "answers": ["jing3cha2","jǐngchá","police",] },
    {"letter": "经济 / 經濟", "answers": ["jing1ji4","jīngjì","economy",] },
    {"letter": "京剧 / 京劇", "answers": ["jing1ju4","jīngjù","Beijing Opera",] },
    {"letter": "经历 / 經歷", "answers": ["jing1li4","jīnglì","experience","to experience",] },
    {"letter": "竟然 / 竟然", "answers": ["jing4ran2","jìngrán","unexpectedly",] },
    {"letter": "精神 / 精神", "answers": ["jing1shen5","jīngshén","spirit","mind",] },
    {"letter": "经验 / 經驗", "answers": ["jing1yan4","jīngyàn","experience","to experience",] },
    {"letter": "竞争 / 競爭", "answers": ["jing4zheng1","jìngzhēng","competition","to compete",] },
    {"letter": "镜子 / 鏡子", "answers": ["jing4zi5","jìngzi","mirror",] },
    {"letter": "究竟 / 究竟", "answers": ["jiu1jing4","jiūjìng","after all","actually",] },
    {"letter": "举办 / 舉辦", "answers": ["ju3ban4","jǔbàn","to hold","to conduct",] },
    {"letter": "拒绝 / 拒絕", "answers": ["ju4jue2","jùjué","to refuse","to decline",] },
    {"letter": "距离 / 距離", "answers": ["ju4li2","jùlí","distance","to be apart from",] },
    {"letter": "开玩笑 / 開玩笑", "answers": ["kai1wan2xiao4","kāiwánxiào","to play a joke","to make fun of",] },
    {"letter": "看法 / 看法", "answers": ["kan4fa3","kànfǎ","view","opinion",] },
    {"letter": "考虑 / 考慮", "answers": ["kao3lü4","kǎolǜ","consideration","to think over","to consider",] },
    {"letter": "棵 / 棵", "answers": ["ke1","kē","Measure word","Measure word for trees, plants, etc.",] },
    {"letter": "可怜 / 可憐", "answers": ["ke3lian2","kělián","pitiful","poor","pathetic",] },
    {"letter": "可是 / 可是", "answers": ["ke3shi4","kěshì","but",] },
    {"letter": "咳嗽 / 咳嗽", "answers": ["ke2sou5","késou","cough","to cough",] },
    {"letter": "可惜 / 可惜", "answers": ["ke3xi1","kěxī","it is a pity","what a pity",] },
    {"letter": "科学 / 科學", "answers": ["ke1xue2","kēxué","science","scientific",] },
    {"letter": "肯定 / 肯定", "answers": ["ken3ding4","kěndìng","to affirm","to confirm","certain","definite","certainly","definitely",] },
    {"letter": "恐怕 / 恐怕", "answers": ["kong3pa4","kǒngpà","I'm afraid that",] },
    {"letter": "空气 / 空氣", "answers": ["kong1qi4","kōngqì","air","atmosphere",] },
    {"letter": "苦 / 苦", "answers": ["ku3","kǔ","bitter","miserable",] },
    {"letter": "宽 / 寬", "answers": ["kuan1","kuān","wide","broad",] },
    {"letter": "困 / 困", "answers": ["kun4","kùn","sleepy","tired",] },
    {"letter": "困难 / 困難", "answers": ["kun4nan5","kùnnan","difficulty","problem","difficult",] },
    {"letter": "扩大 / 擴大", "answers": ["kuo4da4","kuòdà","to expand","to enlarge",] },
    {"letter": "辣 / 辣", "answers": ["la4","là","spicy",] },
    {"letter": "拉 / 拉", "answers": ["la1","lā","to pull",] },
    {"letter": "垃圾桶 / 垃圾桶", "answers": ["la1ji1tong3","lājītǒng","rubbish bin",] },
    {"letter": "来不及 / 來不及", "answers": ["lai2bu5ji2","láibují","there's not enough time",] },
    {"letter": "来得及 / 來得及", "answers": ["lai2de5ji2","láidejí","there is still time to do sth.",] },
    {"letter": "懒 / 懶", "answers": ["lan3","lǎn","lazy",] },
    {"letter": "浪费 / 浪費", "answers": ["lang4fei4","làngfèi","to waste",] },
    {"letter": "浪漫 / 浪漫", "answers": ["lang4man4","làngmàn","romantic",] },
    {"letter": "老虎 / 老虎", "answers": ["lao3hu3","lǎohǔ","tiger",] },
    {"letter": "冷静 / 冷靜", "answers": ["leng3jing4","lěngjìng","calm","cool-headed","quite",] },
    {"letter": "理发 / 理髮", "answers": ["li3fa4","lǐfà","to have a haircut",] },
    {"letter": "厉害 / 厲害", "answers": ["li4hai5","lìhai","awesome","terrible","strict","severe","difficult to deal with",] },
    {"letter": "理解 / 理解", "answers": ["li3jie3","lǐjiě","comprehension","understanding","to comprehend","to understand",] },
    {"letter": "礼貌 / 禮貌", "answers": ["li3mao4","lǐmào","politeness","courtesy",] },
    {"letter": "力气 / 力氣", "answers": ["li4qi5","lìqi","strength",] },
    {"letter": "例如 / 例如", "answers": ["li4ru2","lìrú","for example",] },
    {"letter": "理想 / 理想", "answers": ["li3xiang3","lǐxiǎng","ideal","dream",] },
    {"letter": "俩 / 倆", "answers": ["lia3","liǎ","two","two people",] },
    {"letter": "连 / 連", "answers": ["lian2","lián","to link","to join","to connect","even",] },
    {"letter": "联系 / 聯繫", "answers": ["lian2xi4","liánxì","contact","connection","to contact",] },
    {"letter": "亮 / 亮", "answers": ["liang4","liàng","to shine","to show","to reveal","bright","clear","shiny",] },
    {"letter": "凉快 / 涼快", "answers": ["liang2kuai5","liángkuai","pleasantly cool",] },
    {"letter": "聊天 / 聊天", "answers": ["liao2tian1","liáotiān","to chat",] },
    {"letter": "另外 / 另外", "answers": ["ling4wai4","lìngwài","in addition","morover","furthermore",] },
    {"letter": "留 / 留", "answers": ["liu2","liú","to keep","to remain","to stay","to leave a message","to leave something",] },
    {"letter": "流泪 / 流淚", "answers": ["liu2lei4","liúlèi","to shed tears",] },
    {"letter": "流利 / 流利", "answers": ["liu2li4","liúlì","fluent",] },
    {"letter": "流行 / 流行", "answers": ["liu2xing2","liúxíng","to spread","popular","fashionable",] },
    {"letter": "留学 / 留學", "answers": ["liu2xue2","liúxué","to study abroad",] },
    {"letter": "律师 / 律師", "answers": ["lü4shi1","lǜshī","lawyer",] },
    {"letter": "乱 / 亂", "answers": ["luan4","luàn","disorder","to cause disorder","in a mess","confused",] },
    {"letter": "麻烦 / 麻煩", "answers": ["ma2fan5","máfan","to trouble sb.","troublesome",] },
    {"letter": "马虎 / 馬虎", "answers": ["ma3hu5","mǎhu","careless","negligent","casual",] },
    {"letter": "满 / 滿", "answers": ["man3","mǎn","to fill","to satisfy","full","satisfied",] },
    {"letter": "毛巾 / 毛巾", "answers": ["mao2jin1","máojīn","towel",] },
    {"letter": "美丽 / 美麗", "answers": ["mei3li4","měilì","beautiful",] },
    {"letter": "梦 / 夢", "answers": ["meng4","mèng","dream",] },
    {"letter": "密码 / 密碼", "answers": ["mi4ma3","mìmǎ","password",] },
    {"letter": "免费 / 免費", "answers": ["mian3fei4","miǎnfèi","free","free of charge",] },
    {"letter": "民族 / 民族", "answers": ["min2zu2","mínzú","nationality","ethnic group",] },
    {"letter": "目的 / 目的", "answers": ["mu4di4","mùdì","purpose","aim",] },
    {"letter": "母亲 / 母親", "answers": ["mu3qin1","mǔqīn","mother",] },
    {"letter": "耐心 / 耐心", "answers": ["nai4xin1","nàixīn","patience","patient",] },
    {"letter": "难道 / 難道", "answers": ["nan2dao4","nándào","don't tell me ...","is it possible that ...",] },
    {"letter": "难受 / 難受", "answers": ["nan2shou4","nánshòu","to be difficult to bear",] },
    {"letter": "内 / 內", "answers": ["nei4","nèi","inside","inner",] },
    {"letter": "内容 / 內容", "answers": ["nei4rong2","nèiróng","content","substance",] },
    {"letter": "能力 / 能力", "answers": ["neng2li4","nénglì","ability","capability",] },
    {"letter": "年龄 / 年齡", "answers": ["nian2ling2","niánlíng","age",] },
    {"letter": "弄 / 弄", "answers": ["nong4","nòng","to do","to make",] },
    {"letter": "农村 / 農村", "answers": ["nong2cun1","nóngcūn","village","rural area",] },
    {"letter": "暖和 / 暖和", "answers": ["nuan3huo5","nuǎnhuo","warm",] },
    {"letter": "偶尔 / 偶爾", "answers": ["ou3er3","ǒuěr","occasionally",] },
    {"letter": "排列 / 排列", "answers": ["pai2lie4","páiliè","arrangement","permutation","to arrange","to put in order",] },
    {"letter": "判断 / 判斷", "answers": ["pan4duan4","pànduàn","decision","judgement","to decide","to judge",] },
    {"letter": "陪 / 陪", "answers": ["pei2","péi","to accompany",] },
    {"letter": "皮肤 / 皮膚", "answers": ["pi2fu1","pífū","skin",] },
    {"letter": "批评 / 批評", "answers": ["pi1ping2","pīpíng","criticism","to criticize",] },
    {"letter": "脾气 / 脾氣", "answers": ["pi2qi5","píqi","temperament","temper",] },
    {"letter": "骗 / 騙", "answers": ["pian4","piàn","to cheat","to swindle",] },
    {"letter": "篇 / 篇", "answers": ["pian1","piān","Measure word","Measure word for chapters, articles, etc.",] },
    {"letter": "乒乓球 / 乒乓球", "answers": ["ping1pang1qiu2","pīngpāngqiú","table tennis",] },
    {"letter": "平时 / 平時", "answers": ["ping2shi2","píngshí","in peacetime","normally",] },
    {"letter": "瓶子 / 瓶子", "answers": ["ping2zi5","píngzi","bottle",] },
    {"letter": "破 / 破", "answers": ["po4","pò","to break","to destroy","broken","damaged",] },
    {"letter": "普遍 / 普遍", "answers": ["pu3bian4","pǔbiàn","universal","general",] },
    {"letter": "其次 / 其次", "answers": ["qi2ci4","qícì","next","secondary","secondly",] },
    {"letter": "起飞 / 起飛", "answers": ["qi3fei1","qǐfēi","to take off",] },
    {"letter": "气候 / 氣候", "answers": ["qi4hou4","qìhòu","climate","atmosphere",] },
    {"letter": "起来 / 起來", "answers": ["qi5lai5","qǐlái","to stand up","to get up",] },
    {"letter": "其中 / 其中", "answers": ["qi2zhong1","qízhōng","among","in",] },
    {"letter": "千万 / 千萬", "answers": ["qian1wan4","qiānwàn","10 million","countless","many","must","be sure to",] },
    {"letter": "签证 / 簽證", "answers": ["qian1zheng4","qiānzhèng","visa",] },
    {"letter": "墙 / 牆", "answers": ["qiang2","qiáng","wall",] },
    {"letter": "桥 / 橋", "answers": ["qiao2","qiáo","bridge",] },
    {"letter": "敲 / 敲", "answers": ["qiao1","qiāo","to knock",] },
    {"letter": "巧克力 / 巧克力", "answers": ["qiao3ke4li4","qiǎokèlì","chocolate",] },
    {"letter": "亲戚 / 親戚", "answers": ["qin1qi5","qīnqi","relatives",] },
    {"letter": "轻 / 輕", "answers": ["qing1","qīng","light","small in number","unimportant",] },
    {"letter": "请假 / 請假", "answers": ["qing3jia4","qǐngjià","to ask for leave",] },
    {"letter": "请客 / 請客", "answers": ["qing3ke4","qǐngkè","to invite sb. for dinner",] },
    {"letter": "情况 / 情況", "answers": ["qing2kuang4","qíngkuàng","circumstance","situation",] },
    {"letter": "轻松 / 輕鬆", "answers": ["qing1song1","qīngsōng","relaxed","easy",] },
    {"letter": "穷 / 窮", "answers": ["qiong2","qióng","poor",] },
    {"letter": "取 / 取", "answers": ["qu3","qǔ","to take","to get",] },
    {"letter": "区别 / 區別", "answers": ["qu1bie2","qūbié","difference","to distinguish",] },
    {"letter": "全部 / 全部", "answers": ["quan2bu4","quánbù","whole","entire","complete",] },
    {"letter": "却 / 卻", "answers": ["que4","què","but","yet",] },
    {"letter": "缺点 / 缺點", "answers": ["que1dian3","quēdiǎn","weakness","shortcoming",] },
    {"letter": "缺少 / 缺少", "answers": ["que1shao3","quēshǎo","lack","shortage","to lack","to be short of",] },
    {"letter": "确实 / 確實", "answers": ["que4shi2","quèshí","indeed","really","for sure","indeed",] },
    {"letter": "群 / 群", "answers": ["qun2","qún","Measure word","Measure word for group, crowd, etc.",] },
    {"letter": "然而 / 然而", "answers": ["ran2er2","ránér","however","but",] },
    {"letter": "热闹 / 熱鬧", "answers": ["re4nao5","rènao","lively","busy",] },
    {"letter": "任何 / 任何", "answers": ["ren4he2","rènhé","any","whichever","whatever",] },
    {"letter": "人民币 / 人民幣", "answers": ["ren2min2bi4","rénmínbì","RMB","Chinese Yuan",] },
    {"letter": "任务 / 任務", "answers": ["ren4wu5","rènwu","mission","task",] },
    {"letter": "扔 / 扔", "answers": ["reng1","rēng","to throw","to throw away",] },
    {"letter": "仍然 / 仍然", "answers": ["reng2ran2","réngrán","still","yet",] },
    {"letter": "日记 / 日記", "answers": ["ri4ji4","rìjì","diary",] },
    {"letter": "入口 / 入口", "answers": ["ru4kou3","rùkǒu","entrance",] },
    {"letter": "软 / 軟", "answers": ["ruan3","ruǎn","soft",] },
    {"letter": "散步 / 散步", "answers": ["san4bu4","sànbù","to take/to go for a walk",] },
    {"letter": "森林 / 森林", "answers": ["sen1lin2","sēnlín","forest",] },
    {"letter": "沙发 / 沙發", "answers": ["sha1fa1","shāfā","sofa",] },
    {"letter": "商量 / 商量", "answers": ["shang1liang5","shāngliang","to consult","to discuss",] },
    {"letter": "伤心 / 傷心", "answers": ["shang1xin1","shāngxīn","sad","grievous","brokenhearted",] },
    {"letter": "稍微 / 稍微", "answers": ["shao1wei1","shāowēi","a little bit",] },
    {"letter": "社会 / 社會", "answers": ["she4hui4","shèhuì","society",] },
    {"letter": "深 / 深", "answers": ["shen1","shēn","deep","dark",] },
    {"letter": "申请 / 申請", "answers": ["shen1qing3","shēnqǐng","application","to apply for",] },
    {"letter": "甚至 / 甚至", "answers": ["shen4zhi4","shènzhì","even",] },
    {"letter": "剩 / 剩", "answers": ["sheng4","shèng","to remain",] },
    {"letter": "省 / 省", "answers": ["sheng3","shěng","province","to save","to omit",] },
    {"letter": "生活 / 生活", "answers": ["sheng1huo2","shēnghuó","lif","to live",] },
    {"letter": "生命 / 生命", "answers": ["sheng1ming4","shēngmìng","life",] },
    {"letter": "试 / 試", "answers": ["shi4","shì","experiment","examination","test","to test","to attempt",] },
    {"letter": "失败 / 失敗", "answers": ["shi1bai4","shībài","defeat","failure","to lose","to be defeated",] },
    {"letter": "市场 / 市場", "answers": ["shi4chang3","shìchǎng","market",] },
    {"letter": "十分 / 十分", "answers": ["shi2fen1","shífēn","very","completely","fully","utterly","absolutely",] },
    {"letter": "师傅 / 師傅", "answers": ["shi1fu5","shīfu","master","teacher","used to respectfully address older men",] },
    {"letter": "适合 / 適合", "answers": ["shi4he2","shìhé","to fit","to suit",] },
    {"letter": "实际 / 實際", "answers": ["shi2ji4","shíjì","reality","practice","realistic","practical",] },
    {"letter": "世纪 / 世紀", "answers": ["shi4ji4","shìjì","century",] },
    {"letter": "食品 / 食品", "answers": ["shi2pin3","shípǐn","food",] },
    {"letter": "湿润 / 濕潤", "answers": ["shi1run4","shīrùn","moist","humid",] },
    {"letter": "失望 / 失望", "answers": ["shi1wang4","shīwàng","disappointment","to lose hope","disappointed",] },
    {"letter": "适应 / 適應", "answers": ["shi4ying4","shìyìng","to fit","to suit","to adabt",] },
    {"letter": "使用 / 使用", "answers": ["shi3yong4","shǐyòng","to use",] },
    {"letter": "实在 / 實在", "answers": ["shi2zai4","shízài","real","TRUE","really","in fact",] },
    {"letter": "狮子 / 獅子", "answers": ["shi1zi5","shīzi","lion",] },
    {"letter": "收 / 收", "answers": ["shou1","shōu","to accept","to receive",] },
    {"letter": "受不了 / 受不了", "answers": ["shou4bu4liao3","shòubùliǎo","unbearable",] },
    {"letter": "受到 / 受到", "answers": ["shou4dao4","shòudào","to receive","to suffer",] },
    {"letter": "首都 / 首都", "answers": ["shou3du1","shǒudū","capital city",] },
    {"letter": "售货员 / 售貨員", "answers": ["shou4huo4yuan2","shòuhuòyuán","salesperson",] },
    {"letter": "收入 / 收入", "answers": ["shou1ru4","shōurù","income","revenue","to take in",] },
    {"letter": "收拾 / 收拾", "answers": ["shou1shi5","shōushi","to put in order","to tidy up","to punish",] },
    {"letter": "首先 / 首先", "answers": ["shou3xian1","shǒuxiān","first of all",] },
    {"letter": "输 / 輸", "answers": ["shu1","shū","to transport","to lose","to be beaten",] },
    {"letter": "数量 / 數量", "answers": ["shu4liang4","shùliàng","amount","quantity",] },
    {"letter": "熟悉 / 熟悉", "answers": ["shu2xi1","shúxī","to be familiar with",] },
    {"letter": "数字 / 數字", "answers": ["shu4zi4","shùzì","figure","number",] },
    {"letter": "帅 / 帥", "answers": ["shuai4","shuài","handsome","smart (for men)","smart",] },
    {"letter": "顺便 / 順便", "answers": ["shun4bian4","shùnbiàn","on the way","in passing by",] },
    {"letter": "顺利 / 順利", "answers": ["shun4li4","shùnlì","smoothly",] },
    {"letter": "顺序 / 順序", "answers": ["shun4xu4","shùnxù","sequence","order",] },
    {"letter": "说明 / 說明", "answers": ["shuo1ming2","shuōmíng","explanation","illustration","to explain","to illustrate",] },
    {"letter": "硕士 / 碩士", "answers": ["shuo4shi4","shuòshì","master's degree",] },
    {"letter": "死 / 死", "answers": ["si3","sǐ","death","to die","dead",] },
    {"letter": "速度 / 速度", "answers": ["su4du4","sùdù","speed",] },
    {"letter": "塑料袋 / 塑料袋", "answers": ["su4liao4dai4","sùliàodài","plastic bag",] },
    {"letter": "算 / 算", "answers": ["suan4","suàn","to calculate",] },
    {"letter": "酸 / 酸", "answers": ["suan1","suān","sour",] },
    {"letter": "随便 / 隨便", "answers": ["sui2bian4","suíbiàn","random","as one wishes",] },
    {"letter": "随着 / 隨着", "answers": ["sui2zhe5","suízhe","along with","in the wake of",] },
    {"letter": "孙子 / 孫子", "answers": ["sun1zi5","sūnzi","grandson",] },
    {"letter": "所有 / 所有", "answers": ["suo3you3","suǒyǒu","to possess","to own","all",] },
    {"letter": "台 / 台", "answers": ["tai2","tái","desk","platform","Measure word","Measure word for vehicles, machines, etc.",] },
    {"letter": "抬 / 抬", "answers": ["tai2","tái","to lift up","to raise","to carry",] },
    {"letter": "态度 / 態度", "answers": ["tai4du5","tàidu","manner","attitude",] },
    {"letter": "谈 / 談", "answers": ["tan2","tán","to talk",] },
    {"letter": "弹钢琴 / 彈鋼琴", "answers": ["tan2gang1qin2","tángāngqín","to play the piano",] },
    {"letter": "趟 / 趟", "answers": ["tang4","tàng","Measure word","Measure word for number of trips or runs made",] },
    {"letter": "躺 / 躺", "answers": ["tang3","tǎng","to lie down","to recline","to lie",] },
    {"letter": "汤 / 湯", "answers": ["shang1","tāng","soup",] },
    {"letter": "讨论 / 討論", "answers": ["tao3lun4","tǎolùn","discussion","to discuss",] },
    {"letter": "讨厌 / 討厭", "answers": ["tao3yan4","tǎoyàn","to hate","disgusting","nasty",] },
    {"letter": "特点 / 特點", "answers": ["te4dian3","tèdiǎn","characteristic feature",] },
    {"letter": "提供 / 提供", "answers": ["ti2gong1","tígōng","to offer","to supply","to provide",] },
    {"letter": "提前 / 提前", "answers": ["ti2qian2","tíqián","to bring forward","to advance",] },
    {"letter": "提醒 / 提醒", "answers": ["ti2xing3","tíxǐng","to remind","to call attention to",] },
    {"letter": "填空 / 填空", "answers": ["tian2kong4","tiánkòng","to fill in","to fill out",] },
    {"letter": "条件 / 條件", "answers": ["tiao2jian4","tiáojiàn","condition","circumstances",] },
    {"letter": "挺 / 挺", "answers": ["ting3","tǐng","to stick out","to stand straight","quite","very","rather",] },
    {"letter": "停止 / 停止", "answers": ["ting2zhi3","tíngzhǐ","to stop","to halt",] },
    {"letter": "通过 / 通過", "answers": ["tong1guo4","tōngguò","to pass through","to get through","via","by",] },
    {"letter": "同情 / 同情", "answers": ["tong2qing2","tóngqíng","sympathy","compassion","to sympathize",] },
    {"letter": "通知 / 通知", "answers": ["tong1zhi1","tōngzhī","notice","to notify","to inform",] },
    {"letter": "推 / 推", "answers": ["tui1","tuī","to push",] },
    {"letter": "推迟 / 推遲", "answers": ["tui1chi2","tuīchí","to postpone","to defer",] },
    {"letter": "脱 / 脫", "answers": ["tuo1","tuō","to take off","to shed",] },
    {"letter": "袜子 / 襪子", "answers": ["wa4zi5","wàzi","socks","stockings",] },
    {"letter": "完全 / 完全", "answers": ["wan2quan2","wánquán","complete","whole","entire",] },
    {"letter": "往 / 往", "answers": ["wang3","wǎng","to go","towards","to",] },
    {"letter": "网球 / 網球", "answers": ["wang3qiu2","wǎngqiú","tennis",] },
    {"letter": "往往 / 往往", "answers": ["wang3wang3","wǎngwǎng","often",] },
    {"letter": "网站 / 網站", "answers": ["wang3zhan4","wǎngzhàn","website",] },
    {"letter": "味道 / 味道", "answers": ["wei4dao5","wèidào","taste","flavour",] },
    {"letter": "危险 / 危險", "answers": ["wei1xian3","wēixiǎn","danger","dangerous",] },
    {"letter": "温度 / 溫度", "answers": ["wen1du4","wēndù","temperature",] },
    {"letter": "文章 / 文章", "answers": ["wen2zhang1","wénzhāng","article","essay",] },
    {"letter": "握手 / 握手", "answers": ["wo4shou3","wòshǒu","to shake hands",] },
    {"letter": "无 / 無", "answers": ["wu2","wú","not",] },
    {"letter": "误会 / 誤會", "answers": ["wu4hui4","wùhuì","misunderstanding","to misunderstand",] },
    {"letter": "无聊 / 無聊", "answers": ["wu2liao2","wúliáo","boring","bored",] },
    {"letter": "无论 / 無論", "answers": ["wu2lun4","wúlùn","no matter how/what",] },
    {"letter": "污染 / 污染", "answers": ["wu1ran3","wūrǎn","pollution","contamination","to pollute","to contaminate",] },
    {"letter": "西红柿 / 西紅柿", "answers": ["xi1hong2shi4","xīhóngshì","tomato",] },
    {"letter": "洗衣机 / 洗衣機", "answers": ["xi3yi1ji1","xǐyījī","washing machine",] },
    {"letter": "吸引 / 吸引", "answers": ["xi1yin3","xīyǐn","to attract",] },
    {"letter": "咸 / 咸", "answers": ["xian2","xián","salty",] },
    {"letter": "现代 / 現代", "answers": ["xian4dai4","xiàndài","modern times","the contemporary age",] },
    {"letter": "羡慕 / 羨慕", "answers": ["xian4mu4","xiànmù","to envy","to admire",] },
    {"letter": "限制 / 限制", "answers": ["xian4zhi4","xiànzhì","restriction","limit","to restrict","to limit",] },
    {"letter": "响 / 響", "answers": ["xiang3","xiǎng","sound","noise","to make a sound","loud","noisy",] },
    {"letter": "香 / 香", "answers": ["xiang1","xiāng","fragrang",] },
    {"letter": "相反 / 相反", "answers": ["xiang1fan3","xiāngfǎn","opposite","contrary",] },
    {"letter": "详细 / 詳細", "answers": ["xiang2xi4","xiángxì","detailed",] },
    {"letter": "效果 / 效果", "answers": ["xiao4guo3","xiàoguǒ","effect","result",] },
    {"letter": "笑话 / 笑話", "answers": ["xiao4hua4","xiàohua","joke",] },
    {"letter": "小说 / 小說", "answers": ["xiao3shuo1","xiǎoshuō","novel","fiction",] },
    {"letter": "消息 / 消息", "answers": ["xiao1xi5","xiāoxi","news","information",] },
    {"letter": "辛苦 / 辛苦", "answers": ["xin1ku3","xīnkǔ","hard","toilsome",] },
    {"letter": "心情 / 心情", "answers": ["xin1qing2","xīnqíng","mood","state of mind",] },
    {"letter": "信任 / 信任", "answers": ["xin4ren4","xìnrèn","trust","to trust",] },
    {"letter": "信心 / 信心", "answers": ["xin4xin1","xìnxīn","confidence","faith",] },
    {"letter": "信用卡 / 信用卡", "answers": ["xin4yong4ka3","xìnyòngkǎ","credit card",] },
    {"letter": "行 / 行", "answers": ["xing2","xíng","to walk","to go","capable","competent","OK",] },
    {"letter": "醒 / 醒", "answers": ["xing3","xǐng","to wake up",] },
    {"letter": "性别 / 性別", "answers": ["xing4bie2","xìngbié","gender","sex",] },
    {"letter": "兴奋 / 興奮", "answers": ["xing1fen4","xīngfèn","excitement","excited",] },
    {"letter": "幸福 / 幸福", "answers": ["xing4fu2","xìngfú","happiness","happy",] },
    {"letter": "性格 / 性格", "answers": ["xing4ge2","xìnggé","nature","temperament","character",] },
    {"letter": "修 / 修", "answers": ["xiu1","xiū","to mend","to repair",] },
    {"letter": "许多 / 許多", "answers": ["xu3duo1","xǔduō","many","a lot of",] },
    {"letter": "血 / 血", "answers": ["xue4","xuè","blood",] },
    {"letter": "呀 / 呀", "answers": ["ya5","ya","expressing surprise or doubt",] },
    {"letter": "牙膏 / 牙膏", "answers": ["ya2gao1","yágāo","toothpaste",] },
    {"letter": "压力 / 壓力", "answers": ["ya1li4","yālì","preassure",] },
    {"letter": "亚洲 / 亞洲", "answers": ["ya4zhou1","Yàzhōu","Asia",] },
    {"letter": "盐 / 鹽", "answers": ["yan2","yán","salt",] },
    {"letter": "演出 / 演出", "answers": ["yan3chu1","yǎnchū","performance","show","to perform","to put ona show",] },
    {"letter": "严格 / 嚴格", "answers": ["yan2ge2","yángé","strict","rigorous",] },
    {"letter": "研究生 / 研究生", "answers": ["yan2jiu1sheng1","yánjiūshēng","graduate","postgraduate or research student",] },
    {"letter": "演员 / 演員", "answers": ["yan3yuan2","yǎnyuán","performer","actor",] },
    {"letter": "严重 / 嚴重", "answers": ["yan2zhong4","yánzhòng","grave","serious","critical",] },
    {"letter": "养成 / 養成", "answers": ["yang3cheng2","yǎngchéng","to cultivate","to form","to acquire",] },
    {"letter": "阳光 / 陽光", "answers": ["yang2guang1","yángguāng","sunshine",] },
    {"letter": "样子 / 樣子", "answers": ["yang4zi5","yàngzi","appearance","manner",] },
    {"letter": "邀请 / 邀請", "answers": ["yao1qing3","yāoqǐng","invitation","to invite",] },
    {"letter": "钥匙 / 鑰匙", "answers": ["yao4shi5","yàoshi","key",] },
    {"letter": "页 / 頁", "answers": ["ye4","yè","page","leaf","pages",] },
    {"letter": "也许 / 也許", "answers": ["ye3xu3","yěxǔ","perhaps","maybe",] },
    {"letter": "叶子 / 葉子", "answers": ["ye4zi5","yèzi","leaf",] },
    {"letter": "亿 / 億", "answers": ["yi4","yì","100 million",] },
    {"letter": "以 / 以", "answers": ["yi3","yǐ","because of","so as to","in order to",] },
    {"letter": "意见 / 意見", "answers": ["yi4jian4","yìjiàn","opinion","view","objection",] },
    {"letter": "一切 / 一切", "answers": ["yi1qie4","yíqiè","all","everything",] },
    {"letter": "艺术 / 藝術", "answers": ["yi4shu4","yìshù","art",] },
    {"letter": "因此 / 因此", "answers": ["yin1ci3","yīncǐ","thus","consequently",] },
    {"letter": "饮料 / 飲料", "answers": ["yin3liao4","yǐnliào","drink","beverage",] },
    {"letter": "引起 / 引起", "answers": ["yin3qi3","yǐnqǐ","to give rise to","to lead to",] },
    {"letter": "印象 / 印象", "answers": ["yin4xiang4","yìnxiàng","impression",] },
    {"letter": "赢 / 贏", "answers": ["ying2","yíng","to win","to beat",] },
    {"letter": "硬 / 硬", "answers": ["ying4","yìng","hard","stiff","firm",] },
    {"letter": "勇敢 / 勇敢", "answers": ["yong3gan3","yǒnggǎn","brave","courageous",] },
    {"letter": "永远 / 永遠", "answers": ["yong3yuan3","yǒngyuǎn","forever","ever",] },
    {"letter": "由 / 由", "answers": ["you2","yóu","due to","because of","by","from",] },
    {"letter": "优点 / 優點", "answers": ["you1dian3","yōudiǎn","merit","advantage","strong point",] },
    {"letter": "友好 / 友好", "answers": ["you3hao3","yǒuhǎo","friendly",] },
    {"letter": "幽默 / 幽默", "answers": ["you1mo4","yōumò","humor","humorous",] },
    {"letter": "尤其 / 尤其", "answers": ["you2qi2","yóuqí","especially","particularly",] },
    {"letter": "有趣 / 有趣", "answers": ["you3qu4","yǒuqù","interesting",] },
    {"letter": "优秀 / 優秀", "answers": ["you1xiu4","yōuxiù","outstanding","excellent",] },
    {"letter": "友谊 / 友誼", "answers": ["you3yi4","yǒuyì","friendship",] },
    {"letter": "由于 / 由於", "answers": ["you2yu2","yóuyú","due to","because of",] },
    {"letter": "与 / 與", "answers": ["yu3","yǔ","and","with",] },
    {"letter": "语法 / 語法", "answers": ["yu3fa3","yǔfǎ","grammar",] },
    {"letter": "愉快 / 愉快", "answers": ["yu2kuai4","yúkuài","happy","cheerful",] },
    {"letter": "羽毛球 / 羽毛球", "answers": ["yu3mao2qiu2","yǔmáoqiú","badminton",] },
    {"letter": "于是 / 於是", "answers": ["yu2shi4","yúshì","as a result","consequently",] },
    {"letter": "预习 / 預習", "answers": ["yu4xi2","yùxí","to prepare for","to prepare for a lesson",] },
    {"letter": "语言 / 語言", "answers": ["yu3yan2","yǔyán","language",] },
    {"letter": "圆 / 圓", "answers": ["yuan2","yuán","circle","circular","round",] },
    {"letter": "原来 / 原來", "answers": ["yuan2lai2","yuánlái","former","original","as it turns out",] },
    {"letter": "原谅 / 原諒", "answers": ["yuan2liang4","yuánliàng","to excuse","to forgive",] },
    {"letter": "原因 / 原因", "answers": ["yuan2yin1","yuányīn","reason","cause",] },
    {"letter": "阅读 / 閱讀", "answers": ["yue4du2","yuèdú","reading","to read",] },
    {"letter": "约会 / 約會", "answers": ["yue1hui4","yuēhuì","appointment","engagement","date",] },
    {"letter": "允许 / 允許", "answers": ["yun3xu3","yǔnxǔ","to permit","to allow",] },
    {"letter": "杂志 / 雜誌", "answers": ["za2zhi4","zázhì","magazine",] },
    {"letter": "咱们 / 咱們", "answers": ["zan2men5","zánmen","we","us",] },
    {"letter": "暂时 / 暫時", "answers": ["zan4shi2","zànshí","temporary",] },
    {"letter": "脏 / 臟", "answers": ["zang1","zāng","dirty",] },
    {"letter": "责任 / 責任", "answers": ["ze2ren4","zérèn","duty","responsibility",] },
    {"letter": "增加 / 增加", "answers": ["zeng1jia1","zēngjiā","to increase","to raise",] },
    {"letter": "增长 / 增長", "answers": ["zeng1zhang3","zēngzhǎng","increase","growth","to increase","to grow",] },
    {"letter": "窄 / 窄", "answers": ["zhai3","zhǎi","narrow",] },
    {"letter": "招聘 / 招聘", "answers": ["zhao1pin4","zhāopìn","recruitment","job advertisement","to recruit",] },
    {"letter": "真正 / 真正", "answers": ["zhen1zheng4","zhēnzhèng","genuine","real","TRUE",] },
    {"letter": "正常 / 正常", "answers": ["zheng4chang2","zhèngcháng","regular","normal","ordinary",] },
    {"letter": "正好 / 正好", "answers": ["zheng4hao3","zhènghǎo","just right","just at the right time",] },
    {"letter": "整理 / 整理", "answers": ["zheng3li3","zhěnglǐ","to arrange","to tidy up",] },
    {"letter": "证明 / 證明", "answers": ["zheng4ming2","zhèngmíng","proof","certificate","testimonial","to prove","to testify",] },
    {"letter": "整齐 / 整齊", "answers": ["zheng3qi2","zhěngqí","neat","tidy","in good order",] },
    {"letter": "正确 / 正確", "answers": ["zheng4que4","zhèngquè","correct","proper",] },
    {"letter": "正式 / 正式", "answers": ["zheng4shi4","zhèngshì","formal","official",] },
    {"letter": "指 / 指", "answers": ["zhi3","zhǐ","finger","to point at or to","to indicate",] },
    {"letter": "之 / 之", "answers": ["zhi1","zhī","I","he","she it","...","similar to 的",] },
    {"letter": "只 / 只", "answers": ["zhi3","zhī","Measure word","Measure word for birds and animals, a pair of things, parts of the body, etc.",] },
    {"letter": "支持 / 支持", "answers": ["zhi1chi2","zhīchí","support","backing","to support","to back",] },
    {"letter": "值得 / 值得", "answers": ["zhi2de5","zhídé","to be worth","to deserve",] },
    {"letter": "只好 / 只好", "answers": ["zhi3hao3","zhǐhǎo","have to",] },
    {"letter": "直接 / 直接", "answers": ["zhi2jie1","zhíjiē","direct","immediate",] },
    {"letter": "质量 / 質量", "answers": ["zhi4liang4","zhìliàng","quality",] },
    {"letter": "至少 / 至少", "answers": ["zhi4shao3","zhìshǎo","at least",] },
    {"letter": "知识 / 知識", "answers": ["zhi1shi5","zhīshi","knowledge",] },
    {"letter": "植物 / 植物", "answers": ["zhi2wu4","zhíwù","plant",] },
    {"letter": "只要 / 只要", "answers": ["zhi3yao4","zhǐyào","if only","as long as",] },
    {"letter": "职业 / 職業", "answers": ["zhi2ye4","zhíyè","occupation","profession",] },
    {"letter": "制造 / 製造", "answers": ["zhi4zao4","zhìzào","to make","to manufacture",] },
    {"letter": "重点 / 重點", "answers": ["zhong4dian3","zhòngdiǎn","emphasis","focal point","priority",] },
    {"letter": "重视 / 重視", "answers": ["zhong4shi4","zhòngshì","to value","to attach importance to",] },
    {"letter": "中文 / 中文", "answers": ["zhong1wen2","Zhōngwén","Chinese language",] },
    {"letter": "周围 / 周圍", "answers": ["zhou1wei2","zhōuwéi","surroundings","environment","around","about",] },
    {"letter": "猪 / 豬", "answers": ["zhu1","zhū","pig",] },
    {"letter": "主动 / 主動", "answers": ["zhu3dong4","zhǔdòng","to take the initiative","active",] },
    {"letter": "祝贺 / 祝賀", "answers": ["zhu4he4","zhùhè","congratulations","to congratulate",] },
    {"letter": "逐渐 / 逐漸", "answers": ["zhu2jian4","zhújiàn","gradually",] },
    {"letter": "著名 / 著名", "answers": ["zhu4ming2","zhùmíng","famous","well-known",] },
    {"letter": "主意 / 主意", "answers": ["zhu3yi5","zhǔyi","idea","plan","decision",] },
    {"letter": "赚 / 賺", "answers": ["zuan4","zhuàn","to earn","to make a profit",] },
    {"letter": "专门 / 專門", "answers": ["zhuan1men2","zhuānmén","special","specialized","specialized",] },
    {"letter": "专业 / 專業", "answers": ["zhuan1ye4","zhuānyè","speciality","major","field of study",] },
    {"letter": "撞 / 撞", "answers": ["zhuang4","zhuàng","to hit","to bump against","to collide","to run into",] },
    {"letter": "准确 / 準確", "answers": ["zhun3que4","zhǔnquè","accurate","precise","exact",] },
    {"letter": "准时 / 準時", "answers": ["zhun3shi2","zhǔnshí","on time","punctual",] },
    {"letter": "自然 / 自然", "answers": ["zi4ran2","zìrán","nature","natural",] },
    {"letter": "仔细 / 仔細", "answers": ["zi3xi4","zǐxì","careful","attentive","cautious",] },
    {"letter": "总结 / 總結", "answers": ["zong3jie2","zǒngjié","summary","to sum up",] },
    {"letter": "租 / 租", "answers": ["zu1","zū","to rent","to hire",] },
    {"letter": "组成 / 組成", "answers": ["zu3cheng2","zǔchéng","composition","to form","to compose","to constitute",] },
    {"letter": "组织 / 組織", "answers": ["zu3zhi1","zǔzhī","organisation","to organize",] },
    {"letter": "嘴 / 嘴", "answers": ["zui3","zuǐ","mouth",] },
    {"letter": "最好 / 最好", "answers": ["zui4hao3","zuìhǎo","it would be best","had better",] },
    {"letter": "最后 / 最後", "answers": ["zui4hou4","zuìhòu","finally","at last",] },
    {"letter": "尊重 / 尊重", "answers": ["zun1zhong4","zūnzhòng","respect","esteem","to respect","to honor",] },
    {"letter": "座 / 座", "answers": ["zuo4","zuò","seat","Measure word","Measure word for cities, buildings, mountains, etc.",] },
    {"letter": "做生意 / 做生意", "answers": ["zuo4sheng1yi4","zuòshēngyi","to do business",] },
    {"letter": "座位 / 座位", "answers": ["zuo4wei4","zuòwèi","seat","place",] },
    {"letter": "作者 / 作者", "answers": ["zuo4zhe3","zuòzhě","author","writer",] }
  ]
};

module.exports = CHINESE4;