const CHINESE1 = {
	"footer": "Write the Chinese character in pinyin or translate it.",
	"sets": [
    {"letter": "爱 / 愛", "answers": ["ai4","ài","to love"] },
    {"letter": "八 / 八", "answers": ["ba1","bā","8","eight"] },
    {"letter": "爸爸 / 爸爸", "answers": ["ba4ba5","bàba","dad","father"] },
    {"letter": "北京 / 北京", "answers": ["bei3jing1","Běijīng","Beijing"] },
    {"letter": "杯子 / 杯子", "answers": ["bei1zi5","bēizi","cup","glass"] },
    {"letter": "本 / 本", "answers": ["ben3","běn","Measure word for books","root","basis","foundation","origin","capital"] },
    {"letter": "不 / 不", "answers": ["bu4","bù","no","not"] },
    {"letter": "不客气 / 不客氣", "answers": ["bu4ke4qi5","búkèqi","you are welcome","don't mention it","my pleasure","you're welcome"] },
    {"letter": "菜 / 菜", "answers": ["cai4","cài","dish","vegetable"] },
    {"letter": "茶 / 茶", "answers": ["cha2","chá","tea"] },
    {"letter": "吃 / 吃", "answers": ["chi1","chī","to eat"] },
    {"letter": "出租车 / 出租車", "answers": ["chu1zu1che1","chūzūchē","taxi"] },
    {"letter": "大 / 大", "answers": ["da4","dà","big","great"] },
    {"letter": "打电话 / 打電話", "answers": ["da3dian4hua4","dǎdiànhuà","to make a phone call"] },
    {"letter": "的 / 的", "answers": ["de5","de","to form an attribute"] },
    {"letter": "点 / 點", "answers": ["dian3","diǎn","point","dot","to nod","to click","a little","a bit"] },
    {"letter": "电脑 / 電腦", "answers": ["dian4nao3","diànnǎo","computer"] },
    {"letter": "电视 / 電視", "answers": ["dian4shi4","diànshì","TV","television"] },
    {"letter": "电影 / 電影", "answers": ["dian4ying3","diànyǐng","movie","film"] },
    {"letter": "东西 / 東西", "answers": ["dong1xi5","dōngxi","thing"] },
    {"letter": "都 / 都", "answers": ["dou1","dōu","all","both","all","both"] },
    {"letter": "读 / 讀", "answers": ["du2","dú","to read aloud"] },
    {"letter": "对不起 / 對不起", "answers": ["dui4bu5qi3","duìbuqǐ","sorry","I'm sorry"] },
    {"letter": "多 / 多", "answers": ["duo1","duō","much","many"] },
    {"letter": "多少 / 多少", "answers": ["duo1shao5","duōshao","how many","how much"] },
    {"letter": "二 / 二", "answers": ["er4","èr","2","two"] },
    {"letter": "儿子 / 兒子", "answers": ["er2zi5","érzi","son"] },
    {"letter": "饭馆 / 飯館", "answers": ["fan4guan3","fànguǎn","restaurant"] },
    {"letter": "飞机 / 飛機", "answers": ["fei1ji1","fēijī","airplane"] },
    {"letter": "分钟 / 分鐘", "answers": ["fen1zhong1","fēnzhōng","minute"] },
    {"letter": "高兴 / 高興", "answers": ["gao1xing4","gāoxìng","happy","glad","cheerful"] },
    {"letter": "个 / 個", "answers": ["ge4","gè","Measure word"] },
    {"letter": "工作 / 工作", "answers": ["gong1zuo4","gōngzuò","job","to work"] },
    {"letter": "狗 / 狗", "answers": ["gou3","gǒu","dog"] },
    {"letter": "汉语 / 漢語", "answers": ["han4yu3","hànyǔ","Chinese language"] },
    {"letter": "好 / 好", "answers": ["hao3","hǎo","good","nice"] },
    {"letter": "和 / 和", "answers": ["huo2","hé","with","and"] },
    {"letter": "喝 / 喝", "answers": ["he1","hē","to drink"] },
    {"letter": "很 / 很", "answers": ["hen3","hěn","very","quite"] },
    {"letter": "后面 / 後面", "answers": ["hou4mian4","hòumiàn","rear","back","behind"] },
    {"letter": "回 / 回", "answers": ["hui2","huí","to return","to answer","to reply"] },
    {"letter": "会 / 會", "answers": ["hui4","huì","meeting","conference","can","to be able to"] },
    {"letter": "火车站 / 火車站", "answers": ["huo3che1zhan4","huǒchēzhàn","train station"] },
    {"letter": "几 / 幾", "answers": ["ji3","jǐ","how many","several"] },
    {"letter": "家 / 家", "answers": ["jia1","jiā","family","home","household"] },
    {"letter": "叫 / 叫", "answers": ["jiao4","jiào","to be called","to call","to shout"] },
    {"letter": "今天 / 今天", "answers": ["jin1tian1","jīntiān","today"] },
    {"letter": "九 / 九", "answers": ["jiu3","jiǔ","9","nine"] },
    {"letter": "开 / 開", "answers": ["kai1","kāi","to open","to start","to drive"] },
    {"letter": "看 / 看", "answers": ["kan4","kàn","to see","to watch","to look at"] },
    {"letter": "看见 / 看見", "answers": ["kan4jian4","kànjiàn","to see","to catch sight of"] },
    {"letter": "块 / 塊", "answers": ["kuai4","kuài","Measure","for a piece"] },
    {"letter": "来 / 來", "answers": ["lai2","lái","to come","to arrive","ever since"] },
    {"letter": "老师 / 老師", "answers": ["lao3shi1","lǎoshī","teacher"] },
    {"letter": "了 / 了", "answers": ["le5","le","indicating past or change"] },
    {"letter": "冷 / 冷", "answers": ["leng3","lěng","cold"] },
    {"letter": "里 / 里", "answers": ["li3","lǐ","in","inside"] },
    {"letter": "零 / 零", "answers": ["ling2","líng","0","zero"] },
    {"letter": "六 / 六", "answers": ["liu4","liù","6","six"] },
    {"letter": "吗 / 嗎", "answers": ["ma5","ma","to form a question"] },
    {"letter": "妈妈 / 媽媽", "answers": ["ma1ma5","māma","mother","mom"] },
    {"letter": "买 / 買", "answers": ["mai3","mǎi","to buy"] },
    {"letter": "猫 / 貓", "answers": ["mao1","māo","cat"] },
    {"letter": "没 / 沒", "answers": ["mei2","méi","not"] },
    {"letter": "没关系 / 沒關係", "answers": ["mei2guan1xi5","méiguānxi","it doesn't matter","no problem"] },
    {"letter": "米饭 / 米飯", "answers": ["mi3fan4","mǐfàn","rice"] },
    {"letter": "明天 / 明天", "answers": ["ming2tian1","míngtiān","tomorrow"] },
    {"letter": "名字 / 名字", "answers": ["ming2zi5","míngzi","name"] },
    {"letter": "那 / 那", "answers": ["na4","nà","that"] },
    {"letter": "哪 / 哪", "answers": ["nei3","nǎ","which"] },
    {"letter": "呢 / 呢", "answers": ["ne5","ne","to build a question based on already mentioned subjects"] },
    {"letter": "能 / 能", "answers": ["neng2","néng","to be able to"] },
    {"letter": "你 / 你", "answers": ["ni3","nǐ","you"] },
    {"letter": "年 / 年", "answers": ["nian2","nián","year"] },
    {"letter": "女儿 / 女兒", "answers": ["nü3er2","nǚér","daughter"] },
    {"letter": "朋友 / 朋友", "answers": ["peng2you5","péngyou","friend"] },
    {"letter": "漂亮 / 漂亮", "answers": ["piao4liang5","piàoliang","pretty","beautiful"] },
    {"letter": "苹果 / 蘋果", "answers": ["ping2guo3","píngguǒ","apple"] },
    {"letter": "七 / 七", "answers": ["qi1","qī","7","seven"] },
    {"letter": "钱 / 錢", "answers": ["qian2","qián","money"] },
    {"letter": "前面 / 前面", "answers": ["qian2mian4","qiánmiàn","ahead","in front"] },
    {"letter": "请 / 請", "answers": ["qing3","qǐng","to ask","to invite","please"] },
    {"letter": "去 / 去", "answers": ["qu4","qù","to go"] },
    {"letter": "热 / 熱", "answers": ["re4","rè","hot","warm"] },
    {"letter": "人 / 人", "answers": ["ren2","rén","person","people",] },
    {"letter": "认识 / 認識", "answers": ["ren4shi5","rènshi","understanding","knowledge","awareness","to know","to recognize","to understand"] },
    {"letter": "日 / 日", "answers": ["ri4","rì","day","sun"] },
    {"letter": "三 / 三", "answers": ["san1","sān","3","three"] },
    {"letter": "上 / 上", "answers": ["shang4","shàng","to go up","to attend","to climb","on","upon","previous"] },
    {"letter": "商店 / 商店", "answers": ["shang1dian4","shāngdiàn","shop","store"] },
    {"letter": "上午 / 上午", "answers": ["shang4wu3","shàngwǔ","morning"] },
    {"letter": "少 / 少", "answers": ["shao4","shǎo","few","little"] },
    {"letter": "谁 / 誰", "answers": ["shei2","shéi","who"] },
    {"letter": "什么 / 什麼", "answers": ["shen2me5","shénme","what"] },
    {"letter": "十 / 十", "answers": ["shi2","shí","10","ten"] },
    {"letter": "是 / 是", "answers": ["shi4","shì","is","to be"] },
    {"letter": "时候 / 時候", "answers": ["shi2hou5","shíhou","time","moment","period"] },
    {"letter": "书 / 書", "answers": ["shu1","shū","book"] },
    {"letter": "水 / 水", "answers": ["shui3","shuǐ","water"] },
    {"letter": "水果 / 水果", "answers": ["shui3guo3","shuǐguǒ","fruit"] },
    {"letter": "睡觉 / 睡覺", "answers": ["shui4jiao4","shuìjiào","to sleep","to go to bed"] },
    {"letter": "说话 / 說話", "answers": ["shuo1hua4","shuōhuà","to speak","to talk","to gossip"] },
    {"letter": "四 / 四", "answers": ["si4","sì","4","four"] },
    {"letter": "岁 / 歲", "answers": ["sui4","suì","years old"] },
    {"letter": "他 / 他", "answers": ["ta1","tā","he"] },
    {"letter": "她 / 她", "answers": ["ta1","tā","she"] },
    {"letter": "太 / 太", "answers": ["tai4","tài","too","extremely"] },
    {"letter": "天气 / 天氣", "answers": ["tian1qi4","tiānqì","weather"] },
    {"letter": "听 / 聽", "answers": ["ting1","tīng","to listen","to hear","to obey"] },
    {"letter": "同学 / 同學", "answers": ["tong2xue2","tóngxué","classmate"] },
    {"letter": "喂 / 喂", "answers": ["wei4","wèi","to feed","to breed","hello"] },
    {"letter": "我 / 我", "answers": ["wo3","wǒ","I"] },
    {"letter": "我们 / 我們", "answers": ["wo3men5","wǒmen","we"] },
    {"letter": "五 / 五", "answers": ["wu3","wǔ","5","five"] },
    {"letter": "喜欢 / 喜歡", "answers": ["xi3huan5","xǐhuan","to like"] },
    {"letter": "下 / 下", "answers": ["xia4","xià","descend","fall","below","down","under"] },
    {"letter": "下午 / 下午", "answers": ["xia4wu3","xiàwǔ","afternoon"] },
    {"letter": "下雨 / 下雨", "answers": ["xia4yu3","xiàyǔ","to rain"] },
    {"letter": "先生 / 先生", "answers": ["xian1sheng5","xiānsheng","Mister","Mr","teacher"] },
    {"letter": "现在 / 現在", "answers": ["xian4zai4","xiànzài","now"] },
    {"letter": "想 / 想", "answers": ["xiang3","xiǎng","to think","to miss","to want"] },
    {"letter": "小 / 小", "answers": ["xiao3","xiǎo","small"] },
    {"letter": "小姐 / 小姐", "answers": ["xiao3jie5","xiǎojiě","Miss","young lady"] },
    {"letter": "写 / 寫", "answers": ["xie3","xiě","to write"] },
    {"letter": "些 / 些", "answers": ["xie1","xiē","some","few","several","a few"] },
    {"letter": "谢谢 / 謝謝", "answers": ["xie4xie5","xièxie","thanks"] },
    {"letter": "星期 / 星期", "answers": ["xing1qi1","xīngqī","week"] },
    {"letter": "学生 / 學生", "answers": ["xue2sheng5","xuésheng","student","pupil"] },
    {"letter": "学习 / 學習", "answers": ["xue2xi2","xuéxí","to study","to learn"] },
    {"letter": "学校 / 學校", "answers": ["xue2xiao4","xuéxiào","school"] },
    {"letter": "一 / 一", "answers": ["yi1","yī","1","one"] },
    {"letter": "衣服 / 衣服", "answers": ["yi1fu5","yīfu","clothes"] },
    {"letter": "医生 / 醫生", "answers": ["yi1sheng1","yīshēng","doctor"] },
    {"letter": "医院 / 醫院", "answers": ["yi1yuan4","yīyuàn","hospital"] },
    {"letter": "椅子 / 椅子", "answers": ["yi3zi5","yǐzi","chair"] },
    {"letter": "有 / 有", "answers": ["you3","yǒu","to have","to exist","to be"] },
    {"letter": "月 / 月", "answers": ["yue4","yuè","month","moon"] },
    {"letter": "在 / 在", "answers": ["zai4","zài","at","on","in","for action in progress"] },
    {"letter": "再见 / 再見", "answers": ["zai4jian4","zàijiàn","goodbye","see you"] },
    {"letter": "怎么 / 怎麼", "answers": ["zen3me5","zěnme","how"] },
    {"letter": "怎么样 / 怎麼樣", "answers": ["zen3me5yang4","zěnmeyàng","how is","how are","how about that"] },
    {"letter": "这 / 這", "answers": ["zhe4","zhè","this"] },
    {"letter": "中国 / 中國", "answers": ["zhong1guo2","Zhōngguó","China"] },
    {"letter": "中午 / 中午", "answers": ["zhong1wu3","zhōngwǔ","noon","midday"] },
    {"letter": "住 / 住", "answers": ["zhu4","zhù","to live","to stay","to reside"] },
    {"letter": "桌子 / 桌子", "answers": ["zhuo1zi5","zhuōzi","table"] },
    {"letter": "字 / 字", "answers": ["zi4","zì","word","character"] },
    {"letter": "做 / 做", "answers": ["zuo4","zuò","to do","to make"] },
    {"letter": "坐 / 坐", "answers": ["zuo4","zuò","to sit","to take"] },
    {"letter": "昨天 / 昨天", "answers": ["zuo2tian1","zuótiān","yesterday"] },
  ]
};

module.exports = CHINESE1;