const CHINESE2 = {
	"footer": "Write the Chinese character in pinyin or translate it.",
	"sets": [
    {"letter": "吧 / 吧", "answers": ["ba5","ba","indicating suggestion",] },
    {"letter": "白 / 白", "answers": ["bai2","bái","white","blank","free of charge",] },
    {"letter": "百 / 百", "answers": ["bai3","bǎi","100","hundred","one hundred",] },
    {"letter": "帮助 / 幫助", "answers": ["bang1zhu4","bāngzhù","assistance","help","to help",] },
    {"letter": "报纸 / 報紙", "answers": ["bao4zhi3","bàozhǐ","newspaper",] },
    {"letter": "比 / 比", "answers": ["bi3","bǐ","than","used for comparison",] },
    {"letter": "别 / 別", "answers": ["bie4","bié","to leave","to distinguish","other",] },
    {"letter": "长 / 長", "answers": ["chang2","cháng","length","long",] },
    {"letter": "唱歌 / 唱歌", "answers": ["chang4ge1","chànggē","to sing",] },
    {"letter": "出 / 出", "answers": ["chu1","chū","to go out","to exceed","to happen",] },
    {"letter": "船 / 船", "answers": ["chuan2","chuán","boat","ship",] },
    {"letter": "穿 / 穿", "answers": ["chuan1","chuān","to wear",] },
    {"letter": "次 / 次", "answers": ["ci4","cì","order","sequence","time",] },
    {"letter": "从 / 從", "answers": ["zong4","cóng","from",] },
    {"letter": "错 / 錯", "answers": ["cuo4","cuò","mistake","error","wrong",] },
    {"letter": "大家 / 大家", "answers": ["da4jia1","dàjiā","everybody","all","everyone",] },
    {"letter": "打篮球 / 打籃球", "answers": ["da3lan2qiu2","dǎlánqiú","play basketball",] },
    {"letter": "但是 / 但是", "answers": ["dan4shi4","dànshì","but","however",] },
    {"letter": "到 / 到", "answers": ["dao4","dào","to arrive","to reach","to",] },
    {"letter": "得 / 得", "answers": ["de2","de","used to link verb with adjective",] },
    {"letter": "等 / 等", "answers": ["deng3","děng","to wait",] },
    {"letter": "弟弟 / 弟弟", "answers": ["di4di5","dìdi","younger brother",] },
    {"letter": "第一 / 第一", "answers": ["di4yi1","dìyī","first","number one",] },
    {"letter": "懂 / 懂", "answers": ["dong3","dǒng","to understand","to know",] },
    {"letter": "对 / 對", "answers": ["dui4","duì","right","correct",] },
    {"letter": "房间 / 房間", "answers": ["fang2jian1","fángjiān","room",] },
    {"letter": "非常 / 非常", "answers": ["fei1chang2","fēicháng","very",] },
    {"letter": "服务员 / 服務員", "answers": ["fu2wu4yuan2","fúwùyuán","waiter","service personnel",] },
    {"letter": "高 / 高", "answers": ["gao1","gāo","high","tall",] },
    {"letter": "告诉 / 告訴", "answers": ["gao4su5","gàosu","to tell",] },
    {"letter": "哥哥 / 哥哥", "answers": ["ge1ge5","gēge","older brother",] },
    {"letter": "给 / 給", "answers": ["gei3","gěi","to give",] },
    {"letter": "公共汽车 / 公共汽車", "answers": ["gong1gong4qi4che1","gōnggòngqìchē","bus",] },
    {"letter": "公斤 / 公斤", "answers": ["gong1jin1","gōngjīn","kilogram","kg",] },
    {"letter": "公司 / 公司", "answers": ["gong1si1","gōngsī","company",] },
    {"letter": "贵 / 貴", "answers": ["gui4","guì","expensive",] },
    {"letter": "过 / 過", "answers": ["guo5","guo","indicating action in the past",] },
    {"letter": "还 / 還", "answers": ["hai2","hái","still",] },
    {"letter": "孩子 / 孩子", "answers": ["hai2zi5","háizi","child",] },
    {"letter": "号 / 號", "answers": ["hao4","hào","number","day of month",] },
    {"letter": "好吃 / 好吃", "answers": ["hao4chi1","hǎochī","tasty","delicious",] },
    {"letter": "黑 / 黑", "answers": ["hei1","hēi","black","dark",] },
    {"letter": "红 / 紅", "answers": ["hong2","hóng","dividend","red","popular",] },
    {"letter": "欢迎 / 歡迎", "answers": ["huan1ying2","huānyíng","welcome",] },
    {"letter": "回答 / 回答", "answers": ["hui2da2","huídá","answer","to answer","to reply",] },
    {"letter": "机场 / 機場", "answers": ["ji1chang3","jīchǎng","airport",] },
    {"letter": "鸡蛋 / 雞蛋", "answers": ["ji1dan4","jīdàn","egg","chicken egg",] },
    {"letter": "件 / 件", "answers": ["jian4","jiàn","Measure word",] },
    {"letter": "教室 / 教室", "answers": ["jiao4shi4","jiàoshì","classroom",] },
    {"letter": "姐姐 / 姐姐", "answers": ["jie3jie5","jiějie","older sister",] },
    {"letter": "介绍 / 介紹", "answers": ["jie4shao4","jièshào","to introduce","to recommend",] },
    {"letter": "进 / 進", "answers": ["jin4","jìn","to advance","to enter",] },
    {"letter": "近 / 近", "answers": ["jin4","jìn","near","close",] },
    {"letter": "就 / 就", "answers": ["jiu4","jiù","only","already","with regard to",] },
    {"letter": "觉得 / 覺得", "answers": ["jue2de5","juéde","to think","to feel",] },
    {"letter": "咖啡 / 咖啡", "answers": ["ka1fei1","kāfēi","coffee",] },
    {"letter": "开始 / 開始", "answers": ["kai1shi3","kāishǐ","beginning","to begin",] },
    {"letter": "考试 / 考試", "answers": ["kao3shi4","kǎoshì","exam",] },
    {"letter": "课 / 課", "answers": ["ke4","kè","class","lesson","course",] },
    {"letter": "可能 / 可能", "answers": ["ke3neng2","kěnéng","might","maybe","can",] },
    {"letter": "可以 / 可以", "answers": ["ke3yi3","kěyǐ","can","may","to be able to",] },
    {"letter": "快 / 快", "answers": ["kuai4","kuài","quick","rapid","soon",] },
    {"letter": "快乐 / 快樂", "answers": ["kuai4le4","kuàilè","happy",] },
    {"letter": "累 / 累", "answers": ["lei4","lèi","tired",] },
    {"letter": "离 / 離", "answers": ["chi1","lí","to leave","to be away from",] },
    {"letter": "两 / 兩", "answers": ["liang3","liǎng","two","some","Measure word for vehicles",] },
    {"letter": "路 / 路", "answers": ["lu4","lù","road","path",] },
    {"letter": "旅游 / 旅遊", "answers": ["lü3you2","lǚyóu","trip","jorney","to travel",] },
    {"letter": "卖 / 賣", "answers": ["mai4","mài","to sell",] },
    {"letter": "慢 / 慢", "answers": ["man4","màn","slow",] },
    {"letter": "忙 / 忙", "answers": ["mang2","máng","busy",] },
    {"letter": "每 / 每", "answers": ["mei3","měi","each","per","all",] },
    {"letter": "妹妹 / 妹妹", "answers": ["mei4mei5","mèimei","younger sister",] },
    {"letter": "门 / 門", "answers": ["men2","mén","door",] },
    {"letter": "男人 / 男人", "answers": ["nan2ren2","nánrén","man","men",] },
    {"letter": "您 / 您", "answers": ["nin2","nín","you",] },
    {"letter": "牛奶 / 牛奶", "answers": ["niu2nai3","niúnǎi","cow milk",] },
    {"letter": "女人 / 女人", "answers": ["nü3ren5","nǚrén","woman",] },
    {"letter": "旁边 / 旁邊", "answers": ["pang2bian1","pángbiān","beside","aside",] },
    {"letter": "跑步 / 跑步", "answers": ["pao3bu4","pǎobù","to run",] },
    {"letter": "便宜 / 便宜", "answers": ["pian2yi5","piányi","cheap","inexpensive",] },
    {"letter": "票 / 票", "answers": ["piao4","piào","ticket",] },
    {"letter": "起床 / 起床", "answers": ["qi3chuang2","qǐchuáng","to get up","to get out of bed",] },
    {"letter": "妻子 / 妻子", "answers": ["qi1zi5","qīzi","wife",] },
    {"letter": "千 / 千", "answers": ["qian1","qiān","1000","thousand","one thousand",] },
    {"letter": "晴 / 晴", "answers": ["qing2","qíng","clear","sunny",] },
    {"letter": "去年 / 去年", "answers": ["qu4nian2","qùnián","last year",] },
    {"letter": "让 / 讓", "answers": ["rang4","ràng","to permit","to let somebody do something",] },
    {"letter": "上班 / 上班", "answers": ["shang4ban1","shàngbān","to go to work","to start work",] },
    {"letter": "身体 / 身體", "answers": ["shen1ti3","shēntǐ","body","health",] },
    {"letter": "生病 / 生病", "answers": ["sheng1bing4","shēngbìng","to get sick",] },
    {"letter": "生日 / 生日", "answers": ["sheng1ri4","shēngrì","birthday",] },
    {"letter": "时间 / 時間", "answers": ["shi2jian1","shíjiān","time","period",] },
    {"letter": "事情 / 事情", "answers": ["shi4qing5","shìqing","thing","affair","matter",] },
    {"letter": "手表 / 手錶", "answers": ["shou3biao3","shǒubiǎo","wrist watch",] },
    {"letter": "手机 / 手機", "answers": ["shou3ji1","shǒujī","mobile phone",] },
    {"letter": "送 / 送", "answers": ["song4","sòng","to deliver","to escort","to give",] },
    {"letter": "所以 / 所以", "answers": ["suo3yi3","suǒyǐ","therefore","as a result","so",] },
    {"letter": "它 / 它", "answers": ["ta1","tā","it",] },
    {"letter": "题 / 題", "answers": ["ti2","tí","topic","problem","to inscribe",] },
    {"letter": "踢足球 / 踢足球", "answers": ["ti1zu2qiu2","tīzúqiú","to play football",] },
    {"letter": "跳舞 / 跳舞", "answers": ["tiao4wu3","tiàowǔ","to dance",] },
    {"letter": "外 / 外", "answers": ["wai4","wài","foreign","external","outside",] },
    {"letter": "完 / 完", "answers": ["wan2","wán","to finish",] },
    {"letter": "玩 / 玩", "answers": ["wan2","wán","to play","to have fun",] },
    {"letter": "晚上 / 晚上", "answers": ["wan3shang5","wǎnshang","evening",] },
    {"letter": "为什么 / 為什麼", "answers": ["wei4shen2me5","wèishénme","why",] },
    {"letter": "问 / 問", "answers": ["wen4","wèn","to ask",] },
    {"letter": "问题 / 問題", "answers": ["wen4ti2","wèntí","problem","question",] },
    {"letter": "洗 / 洗", "answers": ["xi3","xǐ","to wash",] },
    {"letter": "西瓜 / 西瓜", "answers": ["xi1gua1","xīguā","watermelon",] },
    {"letter": "希望 / 希望", "answers": ["xi1wang4","xīwàng","hope","to hope","to wish",] },
    {"letter": "向 / 向", "answers": ["xiang4","xiàng","direction","to face","to turn towards",] },
    {"letter": "笑 / 笑", "answers": ["xiao4","xiào","smile","to smile","to laugh",] },
    {"letter": "小时 / 小時", "answers": ["xiao3shi2","xiǎoshí","hour",] },
    {"letter": "新 / 新", "answers": ["xin1","xīn","new",] },
    {"letter": "姓 / 姓", "answers": ["xing4","xìng","surname",] },
    {"letter": "休息 / 休息", "answers": ["xiu1xi5","xiūxi","rest","to rest",] },
    {"letter": "雪 / 雪", "answers": ["xue3","xuě","snow",] },
    {"letter": "眼睛 / 眼睛", "answers": ["yan3jing5","yǎnjing","eye",] },
    {"letter": "颜色 / 顏色", "answers": ["yan2se4","yánsè","colour",] },
    {"letter": "羊肉 / 羊肉", "answers": ["yang2rou4","yángròu","mutton",] },
    {"letter": "药 / 葯", "answers": ["yao4","yào","medicine","drug",] },
    {"letter": "要 / 要", "answers": ["yao4","yào","to want to","going to",] },
    {"letter": "也 / 也", "answers": ["ye3","yě","also",] },
    {"letter": "已经 / 已經", "answers": ["yi3jing1","yǐjīng","already",] },
    {"letter": "一起 / 一起", "answers": ["yi1qi3","yìqǐ","together",] },
    {"letter": "意思 / 意思", "answers": ["yi4si5","yìsi","meaning","opinion","idea",] },
    {"letter": "阴 / 陰", "answers": ["yin1","yīn","cloudy","overcast",] },
    {"letter": "因为 / 因為", "answers": ["yin1wei4","yīnwèi","because",] },
    {"letter": "右边 / 右邊", "answers": ["you4bian5","yòubian","right","right side",] },
    {"letter": "游泳 / 游泳", "answers": ["you2yong3","yóuyǒng","swimming","to swim",] },
    {"letter": "鱼 / 魚", "answers": ["yu2","yú","fish",] },
    {"letter": "元 / 元", "answers": ["yuan2","yuán","Yuan","RMB","Renminbi",] },
    {"letter": "远 / 遠", "answers": ["yuan4","yuǎn","far","distant",] },
    {"letter": "运动 / 運動", "answers": ["yun4dong4","yùndòng","movement","sports","to move about",] },
    {"letter": "再 / 再", "answers": ["zai4","zài","again","once more",] },
    {"letter": "早上 / 早上", "answers": ["zao3shang5","zǎoshang","early morning",] },
    {"letter": "张 / 張", "answers": ["zhang1","zhāng","to open up","to spread","Measure word for pieces",] },
    {"letter": "丈夫 / 丈夫", "answers": ["zhang4fu5","zhàngfu","husband",] },
    {"letter": "找 / 找", "answers": ["zhao3","zhǎo","to look for","to seek",] },
    {"letter": "着 / 着", "answers": ["zhe5","zhe","indicating action in progress",] },
    {"letter": "真 / 真", "answers": ["zhen1","zhēn","real","TRUE","genuine",] },
    {"letter": "正在 / 正在", "answers": ["zheng4zai4","zhèngzài","in the process of","in course of",] },
    {"letter": "知道 / 知道", "answers": ["zhi1dao4","zhīdào","to know","to be aware of",] },
    {"letter": "准备 / 準備", "answers": ["zhun3bei4","zhǔnbèi","to prepare",] },
    {"letter": "自行车 / 自行車", "answers": ["zi4xing2che1","zìxíngchē","bicycle","bike",] },
    {"letter": "走 / 走", "answers": ["zou3","zǒu","to walk",] },
    {"letter": "最 / 最", "answers": ["zui4","zuì","most",] },
    {"letter": "左边 / 左邊", "answers": ["zuo3bian5","zuǒbian","left","left side",] },
  ]
};

module.exports = CHINESE2;