const CHINESE3 = {
	"footer": "Write the Chinese character in pinyin or translate it.",
	"sets": [
    {"letter": "啊 / 啊", "answers": ["a5","a","showing approval"] },
    {"letter": "阿姨 / 阿姨", "answers": ["a1yi2","āyí","aunt"] },
    {"letter": "矮 / 矮", "answers": ["ai3","ǎi","low","short"] },
    {"letter": "爱好 / 愛好", "answers": ["ai4hao4","àihào","hobby","interest","to like"] },
    {"letter": "安静 / 安靜", "answers": ["an1jing4","ānjìng","quiet","peaceful"] },
    {"letter": "把 / 把", "answers": ["ba3","bǎ","handle","to grasp","to hold","for ba-sentences","a bunch","Measure word for objects with handle"] },
    {"letter": "半 / 半", "answers": ["ban4","bàn","half"] },
    {"letter": "搬 / 搬", "answers": ["ban1","bān","to move","to shift"] },
    {"letter": "班 / 班", "answers": ["ban1","bān","class","team","squad","Measure word for groups","rankings","etc."] },
    {"letter": "办法 / 辦法", "answers": ["ban4fa3","bànfǎ","method","way","means"] },
    {"letter": "办公室 / 辦公室", "answers": ["ban4gong1shi4","bàngōngshì","office","bureau"] },
    {"letter": "帮忙 / 幫忙", "answers": ["bang1mang2","bāngmáng","to help","to do a favour"] },
    {"letter": "饱 / 飽", "answers": ["bao3","bǎo","full"] },
    {"letter": "包 / 包", "answers": ["bao1","bāo","bag","package","to cover","to wrap","to hold","to include"] },
    {"letter": "被 / 被", "answers": ["bei4","bèi","by"] },
    {"letter": "北方 / 北方", "answers": ["bei3fang1","běifāng","north","northern part of a country"] },
    {"letter": "比较 / 比較", "answers": ["bi3jiao4","bǐjiào","quite","rather","fairly","comparatively"] },
    {"letter": "比赛 / 比賽", "answers": ["bi3sai4","bǐsài","competition","match","to compete"] },
    {"letter": "必须 / 必須", "answers": ["bi4xu1","bìxū","to have to","to must"] },
    {"letter": "鼻子 / 鼻子", "answers": ["bi2zi5","bízi","nose"] },
    {"letter": "变化 / 變化", "answers": ["bian4hua4","biànhuà","change","variation","to change","to vary"] },
    {"letter": "表示 / 表示", "answers": ["biao3shi4","biǎoshì","to express","to show","to indicate"] },
    {"letter": "表演 / 表演", "answers": ["biao3yan3","biǎoyǎn","performance","to perform","to act"] },
    {"letter": "别人 / 別人", "answers": ["bie2ren5","biéren","others","other people"] },
    {"letter": "宾馆 / 賓館", "answers": ["bin1guan3","bīnguǎn","hotel"] },
    {"letter": "冰箱 / 冰箱", "answers": ["bing1xiang1","bīngxiāng","fridge","icebox"] },
    {"letter": "才 / 才", "answers": ["cai2","cái","ability","talent","just","only if"] },
    {"letter": "菜单 / 菜單", "answers": ["cai4dan1","càidān","menu"] },
    {"letter": "参加 / 參加", "answers": ["can1jia1","cānjiā","to attend","to take part","to join"] },
    {"letter": "草 / 草", "answers": ["cao4","cǎo","grass","straw"] },
    {"letter": "层 / 層", "answers": ["ceng2","céng","layer","floor","storey","story"] },
    {"letter": "差 / 差", "answers": ["cha4","chà","to lack","short of","poor"] },
    {"letter": "超市 / 超市", "answers": ["chao1shi4","chāoshì","supermarket"] },
    {"letter": "衬衫 / 襯衫", "answers": ["chen4shan1","chènshān","shirt","blouse"] },
    {"letter": "成绩 / 成績", "answers": ["cheng2ji4","chéngjì","score","achievement","grades"] },
    {"letter": "城市 / 城市", "answers": ["cheng2shi4","chéngshì","city","town"] },
    {"letter": "迟到 / 遲到", "answers": ["chi2dao4","chídào","to be late"] },
    {"letter": "厨房 / 廚房", "answers": ["chu2fang2","chúfáng","kitchen"] },
    {"letter": "除了 / 除了", "answers": ["chu2le5","chúle","except for","apart from","besides"] },
    {"letter": "出现 / 出現", "answers": ["chu1xian4","chūxiàn","to appear","to arise"] },
    {"letter": "春 / 春", "answers": ["chun1","chūn","spring"] },
    {"letter": "词语 / 詞語", "answers": ["ci2yu3","cíyǔ","word","expression"] },
    {"letter": "聪明 / 聰明", "answers": ["cong1ming5","cōngming","clever","intelligent","smart"] },
    {"letter": "打扫 / 打掃", "answers": ["da3sao3","dǎsǎo","to clean"] },
    {"letter": "打算 / 打算", "answers": ["da3suan4","dǎsuàn","plan","intention","to plan","to think of","to calculate"] },
    {"letter": "带 / 帶", "answers": ["dai4","dài","band","belt","area","region","to wear","to carry","to bring","to lead"] },
    {"letter": "蛋糕 / 蛋糕", "answers": ["dan4gao1","dàngāo","cake"] },
    {"letter": "担心 / 擔心", "answers": ["dan1xin1","dānxīn","to worry","worried","anxious"] },
    {"letter": "当然 / 當然", "answers": ["dang1ran2","dāngrán","certainly","of course"] },
    {"letter": "地 / 地", "answers": ["de5","de","used before a verb"] },
    {"letter": "灯 / 燈", "answers": ["deng1","dēng","lamp","light"] },
    {"letter": "低 / 低", "answers": ["di1","dī","low"] },
    {"letter": "地方 / 地方", "answers": ["di4fang5","dìfang","region","place","location"] },
    {"letter": "地铁 / 地鐵", "answers": ["di4tie3","dìtiě","subway"] },
    {"letter": "地图 / 地圖", "answers": ["di4tu2","dìtú","map"] },
    {"letter": "电梯 / 電梯", "answers": ["dian4ti1","diàntī","elevator"] },
    {"letter": "电子邮件 / 電子郵件", "answers": ["dian4zi3you2jian4","diànzǐyóujiàn","email"] },
    {"letter": "东 / 東", "answers": ["dong1","dōng","east"] },
    {"letter": "冬 / 冬", "answers": ["dong1","dōng","winter"] },
    {"letter": "动物 / 動物", "answers": ["dong4wu4","dòngwù","animal"] },
    {"letter": "段 / 段", "answers": ["duan4","duàn","Measure word","Measure word for paragraphs, segments, periods, stories"] },
    {"letter": "短 / 短", "answers": ["duan3","duǎn","short","brief"] },
    {"letter": "锻炼 / 鍛煉", "answers": ["duan4lian4","duànliàn","to exercise","to engage in physical exercise"] },
    {"letter": "多么 / 多麼", "answers": ["duo1me5","duōme","how","what"] },
    {"letter": "饿 / 餓", "answers": ["e4","è","hungry"] },
    {"letter": "耳朵 / 耳朵", "answers": ["er3duo5","ěrduo","ear"] },
    {"letter": "而且 / 而且", "answers": ["er2qie3","érqiě","moreover","in addition","furthermore"] },
    {"letter": "发烧 / 發燒", "answers": ["fa1shao1","fāshāo","to have fever"] },
    {"letter": "发现 / 發現", "answers": ["fa1xian4","fāxiàn","to discover","to find"] },
    {"letter": "放 / 放", "answers": ["fang4","fàng","to let go","to put","have a vacation"] },
    {"letter": "方便 / 方便", "answers": ["fang1bian4","fāngbiàn","convenient"] },
    {"letter": "放心 / 放心", "answers": ["fang4xin1","fàngxīn","to rest","to be at ease"] },
    {"letter": "分 / 分", "answers": ["fen1","fēn","minute","point","0.01 yuan","to divide","to distinguish"] },
    {"letter": "附近 / 附近", "answers": ["fu4jin4","fùjìn","vicinity","nearby","next to"] },
    {"letter": "复习 / 複習", "answers": ["fu4xi2","fùxí","revision","to revise"] },
    {"letter": "敢 / 敢", "answers": ["gan3","gǎn","to dare"] },
    {"letter": "干净 / 乾淨", "answers": ["gan1jing4","gānjìng","clean","tidy"] },
    {"letter": "感冒 / 感冒", "answers": ["gan3mao4","gǎnmào","common cold","to catch a cold"] },
    {"letter": "刚才 / 剛才", "answers": ["gang1cai2","gāngcái","just a moment ago"] },
    {"letter": "跟 / 跟", "answers": ["gen1","gēn","to follow","with","and"] },
    {"letter": "根据 / 根據", "answers": ["gen1ju4","gēnjù","basis","foundation","to base on","according to","based on"] },
    {"letter": "更 / 更", "answers": ["geng4","gèng","even more"] },
    {"letter": "公园 / 公園", "answers": ["gong1yuan2","gōngyuán","park"] },
    {"letter": "故事 / 故事", "answers": ["gu4shi5","gùshi","story","tale"] },
    {"letter": "刮风 / 颳風", "answers": ["gua1feng1","guāfēng","to be windy"] },
    {"letter": "关 / 關", "answers": ["guan1","guān","mountain pass","barrier","to close","to shut","to turn off"] },
    {"letter": "关系 / 關係", "answers": ["guan1xi5","guānxì","relationship","relation","to affect","to have to do with"] },
    {"letter": "关心 / 關心", "answers": ["guan1xin1","guānxīn","concern","to care for"] },
    {"letter": "关于 / 關於", "answers": ["guan1yu2","guānyú","concerning","with regards to","about"] },
    {"letter": "国家 / 國家", "answers": ["guo2jia1","guójiā","country","state","nation"] },
    {"letter": "过去 / 過去", "answers": ["guo4qu5","guòqù","to go over","to pass by","past","former"] },
    {"letter": "果汁 / 果汁", "answers": ["guo3zhi1","guǒzhī","fruit juice"] },
    {"letter": "害怕 / 害怕", "answers": ["hai4pa4","hàipà","to be afraid","to fear"] },
    {"letter": "还是 / 還是", "answers": ["hai2shi5","háishì","still","nevertheless","or"] },
    {"letter": "河 / 河", "answers": ["he2","hé","river"] },
    {"letter": "黑板 / 黑板", "answers": ["hei1ban3","hēibǎn","blackboard"] },
    {"letter": "护照 / 護照", "answers": ["hu4zhao4","hùzhào","passport"] },
    {"letter": "画 / 畫", "answers": ["hua4","huà","picture","painting","to draw","to paint"] },
    {"letter": "花 / 花", "answers": ["hua1","huā","flower","to spend"] },
    {"letter": "花园 / 花園", "answers": ["hua1yuan2","huāyuán","garden"] },
    {"letter": "坏 / 壞", "answers": ["huai4","huài","bad","broken","spoiled"] },
    {"letter": "还 / 還", "answers": ["hai2","huán","to give back","to return"] },
    {"letter": "换 / 換", "answers": ["huan4","huàn","to change","to exchange"] },
    {"letter": "环境 / 環境", "answers": ["huan2jing4","huánjìng","environment","surroundings"] },
    {"letter": "黄 / 黃", "answers": ["huang2","huáng","to fall through","yellow","pornographic"] },
    {"letter": "会议 / 會議", "answers": ["hui4yi4","huìyì","meeting","conference"] },
    {"letter": "或者 / 或者", "answers": ["huo4zhe3","huòzhě","or","possibly"] },
    {"letter": "极 / 極", "answers": ["ji2","jí","pole","extremely","highly"] },
    {"letter": "记得 / 記得", "answers": ["ji4de5","jìde","to remember"] },
    {"letter": "几乎 / 幾乎", "answers": ["ji1hu1","jīhū","almost","nearly"] },
    {"letter": "机会 / 機會", "answers": ["ji1hui4","jīhuì","opportunity","chance"] },
    {"letter": "季节 / 季節", "answers": ["ji4jie2","jìjié","season","period"] },
    {"letter": "检查 / 檢查", "answers": ["jian3cha2","jiǎnchá","inspection","to check","to inspect","to examine"] },
    {"letter": "简单 / 簡單", "answers": ["jian3dan1","jiǎndān","simple","uncomplicated"] },
    {"letter": "健康 / 健康", "answers": ["jian4kang1","jiànkāng","health","healthy"] },
    {"letter": "见面 / 見面", "answers": ["jian4mian4","jiànmiàn","to meet","to see sb."] },
    {"letter": "讲 / 講", "answers": ["jiang3","jiǎng","speech","lecture","to speak","to explain","to negotiate"] },
    {"letter": "脚 / 腳", "answers": ["jiao3","jiǎo","foot"] },
    {"letter": "角 / 角", "answers": ["jiao3","jiǎo","angle","corner","horn","0.1 yuan"] },
    {"letter": "教 / 教", "answers": ["jiao1","jiāo","to teach","to instruct"] },
    {"letter": "借 / 借", "answers": ["jie4","jiè","to lend","to borrow","to make use of"] },
    {"letter": "接 / 接", "answers": ["jie1","jiē","to receive","to meet","to connect","to catch"] },
    {"letter": "街道 / 街道", "answers": ["jie1dao4","jiēdào","street"] },
    {"letter": "结婚 / 結婚", "answers": ["jie2hun1","jiéhūn","marriage","wedding","to marry"] },
    {"letter": "解决 / 解決", "answers": ["jie3jue2","jiějué","to settle","to settle a dispute","to resolve","to solve"] },
    {"letter": "节目 / 節目", "answers": ["jie2mu4","jiémù","program","item"] },
    {"letter": "节日 / 節日", "answers": ["jie2ri4","jiérì","holiday","festival"] },
    {"letter": "结束 / 結束", "answers": ["jie2shu4","jiéshù","termination","end","to finish","to end","to conclude"] },
    {"letter": "经常 / 經常", "answers": ["jing1chang2","jīngcháng","often","frequently"] },
    {"letter": "经过 / 經過", "answers": ["jing1guo4","jīngguò","to pass","to go through","after","as a result of"] },
    {"letter": "经理 / 經理", "answers": ["jing1li3","jīnglǐ","manager","director"] },
    {"letter": "旧 / 舊", "answers": ["jiu4","jiù","old","used","worn"] },
    {"letter": "久 / 久", "answers": ["jiu3","jiǔ","long","long time"] },
    {"letter": "举行 / 舉行", "answers": ["ju3xing2","jǔxíng","to hold a meeting","to hold an event","to hold"] },
    {"letter": "句子 / 句子", "answers": ["ju4zi5","jùzi","sentence"] },
    {"letter": "决定 / 決定", "answers": ["jue2ding4","juédìng","decision","to decide"] },
    {"letter": "刻 / 刻", "answers": ["ke4","kè","to cut","to carve","quarter of an hour","quarter hour"] },
    {"letter": "渴 / 渴", "answers": ["ke3","kě","thirsty"] },
    {"letter": "可爱 / 可愛", "answers": ["ke3ai4","kěài","cute","lovely"] },
    {"letter": "客人 / 客人", "answers": ["ke4ren2","kèrén","guest","customer","visitor"] },
    {"letter": "空调 / 空調", "answers": ["kong1tiao2","kōngtiáo","air conditioning"] },
    {"letter": "口 / 口", "answers": ["kou3","kǒu","mouth","opening","a mouth full of"] },
    {"letter": "哭 / 哭", "answers": ["ku1","kū","to cry","to weep"] },
    {"letter": "裤子 / 褲子", "answers": ["ku4zi5","kùzi","trousers"] },
    {"letter": "筷子 / 筷子", "answers": ["kuai4zi5","kuàizi","chopsticks"] },
    {"letter": "蓝 / 藍", "answers": ["lan2","lán","blue"] },
    {"letter": "老 / 老", "answers": ["lao3","lǎo","old","always"] },
    {"letter": "离开 / 離開", "answers": ["li2kai1","líkāi","to depart","to leave"] },
    {"letter": "历史 / 歷史", "answers": ["li4shi3","lìshǐ","history"] },
    {"letter": "礼物 / 禮物", "answers": ["li3wu4","lǐwù","gift","present"] },
    {"letter": "脸 / 臉", "answers": ["lian3","liǎn","face"] },
    {"letter": "练习 / 練習", "answers": ["lian4xi2","liànxí","exercise","practice","to practice"] },
    {"letter": "辆 / 輛", "answers": ["liang4","liàng","Measure word for vehicles"] },
    {"letter": "了解 / 了解", "answers": ["liao3jie3","liǎojiě","to understand"] },
    {"letter": "邻居 / 鄰居", "answers": ["lin2ju1","línjū","neighbor"] },
    {"letter": "楼 / 樓", "answers": ["lou2","lóu","storied building","floor","story","storey"] },
    {"letter": "绿 / 綠", "answers": ["lü4","lǜ","green"] },
    {"letter": "马 / 馬", "answers": ["ma3","mǎ","horse"] },
    {"letter": "马上 / 馬上", "answers": ["ma3shang4","mǎshàng","immediately","at once"] },
    {"letter": "满意 / 滿意", "answers": ["man3yi4","mǎnyì","to satisfy","satisfied"] },
    {"letter": "帽子 / 帽子", "answers": ["mao4zi5","màozi","hat","cap"] },
    {"letter": "米 / 米", "answers": ["mi3","mǐ","rice","meter","metre"] },
    {"letter": "面包 / 麵包", "answers": ["mian4bao1","miànbāo","bread"] },
    {"letter": "面条 / 麵條", "answers": ["mian4tiao2","miàntiáo","noodles"] },
    {"letter": "明白 / 明白", "answers": ["ming2bai5","míngbai","to understand","clear","obvious"] },
    {"letter": "拿 / 拿", "answers": ["na2","ná","to hold","to seize"] },
    {"letter": "奶奶 / 奶奶", "answers": ["nai3nai5","nǎinai","grandmother","father's mother","paternal grandmother"] },
    {"letter": "南 / 南", "answers": ["nan2","nán","south"] },
    {"letter": "难 / 難", "answers": ["nan2","nán","difficult"] },
    {"letter": "难过 / 難過", "answers": ["nan2guo4","nánguò","to feel sorry","sad"] },
    {"letter": "年级 / 年級", "answers": ["nian2ji2","niánjí","grade","year"] },
    {"letter": "年轻 / 年輕", "answers": ["nian2qing1","niánqīng","young"] },
    {"letter": "鸟 / 鳥", "answers": ["niao3","niǎo","bird"] },
    {"letter": "努力 / 努力", "answers": ["nu3li4","nǔlì","great effort","to strive","to work/study hard","hard","hardworking"] },
    {"letter": "爬山 / 爬山", "answers": ["pa2shan1","páshān","hiking","to climb a mountain"] },
    {"letter": "盘子 / 盤子", "answers": ["pan2zi5","pánzi","tray","plate","dish"] },
    {"letter": "胖 / 胖", "answers": ["pang4","pàng","fat","plump"] },
    {"letter": "啤酒 / 啤酒", "answers": ["pi2jiu3","píjiǔ","beer"] },
    {"letter": "葡萄 / 葡萄", "answers": ["pu2tao5","pútao","grape"] },
    {"letter": "普通话 / 普通話", "answers": ["pu3tong1hua4","pǔtōnghuà","Mandarin"] },
    {"letter": "骑 / 騎", "answers": ["qi2","qí","to ride"] },
    {"letter": "奇怪 / 奇怪", "answers": ["qi2guai4","qíguài","strange"] },
    {"letter": "其实 / 其實", "answers": ["qi2shi2","qíshí","actually","in fact"] },
    {"letter": "其他 / 其他", "answers": ["qi2ta1","qítā","other","others"] },
    {"letter": "铅笔 / 鉛筆", "answers": ["qian1bi3","qiānbǐ","pencil"] },
    {"letter": "清楚 / 清楚", "answers": ["qing1chu5","qīngchu","clear","distinct"] },
    {"letter": "秋 / 秋", "answers": ["qiu1","qiū","autumn","fall"] },
    {"letter": "裙子 / 裙子", "answers": ["qun2zi5","qúnzi","skirt"] },
    {"letter": "然后 / 然後", "answers": ["ran2hou4","ránhòu","then","afterwards"] },
    {"letter": "热情 / 熱情", "answers": ["re4qing2","rèqíng","enthusiasm","passion","enthusiastic","passionate","cordial"] },
    {"letter": "认为 / 認為", "answers": ["ren4wei2","rènwéi","to think","to believe","to consider"] },
    {"letter": "认真 / 認真", "answers": ["ren4zhen1","rènzhēn","conscientious","earnest","serious"] },
    {"letter": "容易 / 容易", "answers": ["rong2yi4","róngyì","easy"] },
    {"letter": "如果 / 如果", "answers": ["ru2guo3","rúguǒ","if"] },
    {"letter": "伞 / 傘", "answers": ["san3","sǎn","umbrella"] },
    {"letter": "上网 / 上網", "answers": ["shang4wang3","shàngwǎng","to be on the internet"] },
    {"letter": "生气 / 生氣", "answers": ["sheng1qi4","shēngqì","to be/get angry","angry","mad"] },
    {"letter": "声音 / 聲音", "answers": ["sheng1yin1","shēngyīn","voice","sound"] },
    {"letter": "使 / 使", "answers": ["shi3","shǐ","envoy","messenger","to make","to cause","to use","to employ"] },
    {"letter": "世界 / 世界", "answers": ["shi4jie4","shìjiè","world"] },
    {"letter": "瘦 / 瘦", "answers": ["shou4","shòu","thin","slim"] },
    {"letter": "树 / 樹", "answers": ["shu4","shù","tree"] },
    {"letter": "舒服 / 舒服", "answers": ["shu1fu5","shūfu","comfortable"] },
    {"letter": "叔叔 / 叔叔", "answers": ["shu1shu5","shūshu","uncle"] },
    {"letter": "数学 / 數學", "answers": ["shu4xue2","shùxué","mathematics"] },
    {"letter": "刷牙 / 刷牙", "answers": ["shua1ya2","shuāyá","to brush teeth"] },
    {"letter": "双 / 雙", "answers": ["shuang1","shuāng","two","pair","both","a pair"] },
    {"letter": "水平 / 水平", "answers": ["shui3ping2","shuǐpíng","level","standard","horizontal"] },
    {"letter": "司机 / 司機", "answers": ["si1ji1","sījī","driver"] },
    {"letter": "虽然 / 雖然", "answers": ["sui1ran2","suīrán","although"] },
    {"letter": "太阳 / 太陽", "answers": ["tai4yang5","tàiyáng","sun"] },
    {"letter": "糖 / 糖", "answers": ["tang2","táng","sugar","sweets","candy"] },
    {"letter": "特别 / 特別", "answers": ["te4bie2","tèbié","special","particular"] },
    {"letter": "疼 / 疼", "answers": ["teng2","téng","pain","to ache","to hurt"] },
    {"letter": "提高 / 提高", "answers": ["ti2gao1","tígāo","to raise","to increase"] },
    {"letter": "体育 / 體育", "answers": ["ti3yu4","tǐyù","sports"] },
    {"letter": "甜 / 甜", "answers": ["tian2","tián","sweet"] },
    {"letter": "条 / 條", "answers": ["tiao2","tiáo","strip","clause","Measure word for long thin things"] },
    {"letter": "同事 / 同事", "answers": ["tong2shi4","tóngshì","colleague"] },
    {"letter": "同意 / 同意", "answers": ["tong2yi4","tóngyì","to agree","to consent","to approve"] },
    {"letter": "头发 / 頭髮", "answers": ["tou2fa5","tóufa","hair","head hair"] },
    {"letter": "突然 / 突然", "answers": ["tu1ran2","tūrán","sudden","abrupt","suddenly","unexpectedly"] },
    {"letter": "图书馆 / 圖書館", "answers": ["tu2shu1guan3","túshūguǎn","library"] },
    {"letter": "腿 / 腿", "answers": ["tui3","tuǐ","leg"] },
    {"letter": "万 / 萬", "answers": ["mo4","wàn","10000","ten thousand"] },
    {"letter": "碗 / 碗", "answers": ["wan3","wǎn","bowl"] },
    {"letter": "完成 / 完成", "answers": ["wan2cheng2","wánchéng","to complete","to accomplish"] },
    {"letter": "忘记 / 忘記", "answers": ["wang4ji4","wàngjì","to forget"] },
    {"letter": "为 / 為", "answers": ["wei4","wèi","to do","to act","to be","to become","for","for somebody"] },
    {"letter": "位 / 位", "answers": ["wei4","wèi","position","place","seat","Measure word for people"] },
    {"letter": "为了 / 為了", "answers": ["wei4le5","wèile","for","in order to"] },
    {"letter": "文化 / 文化", "answers": ["wen2hua4","wénhuà","culture"] },
    {"letter": "西 / 西", "answers": ["xi1","xī","west"] },
    {"letter": "习惯 / 習慣", "answers": ["xi2guan4","xíguàn","habit","usual practice","custom","to be/get used to"] },
    {"letter": "洗手间 / 洗手間", "answers": ["xi3shou3jian1","xǐshǒujiān","toilet"] },
    {"letter": "洗澡 / 洗澡", "answers": ["xi3zao3","xǐzǎo","to take a shower","to have a bath"] },
    {"letter": "夏 / 夏", "answers": ["xia4","xià","summer"] },
    {"letter": "先 / 先", "answers": ["xian1","xiān","early","former","first","before"] },
    {"letter": "像 / 像", "answers": ["xiang4","xiàng","picture","portrait","be/look like","to appear","to seem"] },
    {"letter": "香蕉 / 香蕉", "answers": ["xiang1jiao1","xiāngjiāo","banana"] },
    {"letter": "相同 / 相同", "answers": ["xiang1tong2","xiāngtóng","identical","same"] },
    {"letter": "相信 / 相信", "answers": ["xiang1xin4","xiāngxìn","to believe in","have faith in"] },
    {"letter": "小心 / 小心", "answers": ["xiao3xin1","xiǎoxīn","to be careful","careful","Take care"] },
    {"letter": "校长 / 校長", "answers": ["xiao4zhang3","xiàozhǎng","headmaster","university president"] },
    {"letter": "鞋 / 鞋", "answers": ["xie2","xié","shoe"] },
    {"letter": "信 / 信", "answers": ["xin4","xìn","letter","trust","to believe","to trust"] },
    {"letter": "新闻 / 新聞", "answers": ["xin1wen2","xīnwén","news"] },
    {"letter": "新鲜 / 新鮮", "answers": ["xin1xian1","xīnxiān","fresh"] },
    {"letter": "行李箱 / 行李箱", "answers": ["xing2li5xiang1","xínglixiāng","suitcase"] },
    {"letter": "兴趣 / 興趣", "answers": ["xing4qu4","xìngqù","interest"] },
    {"letter": "熊猫 / 熊貓", "answers": ["xiong2mao1","xióngmāo","panda"] },
    {"letter": "需要 / 需要", "answers": ["xu1yao4","xūyào","needs","to need","to want"] },
    {"letter": "选择 / 選擇", "answers": ["xuan3ze2","xuǎnzé","choice","option","to choose","to select"] },
    {"letter": "眼镜 / 眼鏡", "answers": ["yan3jing4","yǎnjìng","eyeglasses"] },
    {"letter": "要求 / 要求", "answers": ["yao1qiu2","yāoqiú","demand","requirement","to require","to demand"] },
    {"letter": "爷爷 / 爺爺", "answers": ["ye2ye5","yéye","grandfather","father's father","paternal grandfather"] },
    {"letter": "一般 / 一般", "answers": ["yi1ban1","yìbān","ordinary","general","common","in general","generally"] },
    {"letter": "一边 / 一邊", "answers": ["yi1bian1","yìbiān","one side","on the one hand"] },
    {"letter": "一定 / 一定", "answers": ["yi1ding4","yídìng","definite","fixed","given","surely","certainly"] },
    {"letter": "一共 / 一共", "answers": ["yi1gong4","yígòng","althogether"] },
    {"letter": "以后 / 以後", "answers": ["yi3hou4","yǐhòu","after","afterwards"] },
    {"letter": "一会儿 / 一會兒", "answers": ["yi1hui4r5","yíhuìr","a while","in a moment","a little while"] },
    {"letter": "以前 / 以前", "answers": ["yi3qian2","yǐqián","before","previous","formerly"] },
    {"letter": "以为 / 以為", "answers": ["yi3wei2","yǐwéi","to think","to be under the impression","to believe"] },
    {"letter": "一样 / 一樣", "answers": ["yi1yang4","yíyàng","alike","equal to","same"] },
    {"letter": "一直 / 一直", "answers": ["yi1zhi2","yīzhí","always","continuously","straight"] },
    {"letter": "银行 / 銀行", "answers": ["yin2hang2","yínháng","bank"] },
    {"letter": "音乐 / 音樂", "answers": ["yin1yue4","yīnyuè","music"] },
    {"letter": "应该 / 應該", "answers": ["ying1gai1","yīnggāi","should","ought to"] },
    {"letter": "影响 / 影響", "answers": ["ying3xiang3","yǐngxiǎng","influence","effect","to influence","to affect"] },
    {"letter": "用 / 用", "answers": ["yong4","yòng","to use","to employ","to apply"] },
    {"letter": "又 / 又", "answers": ["you4","yòu","again"] },
    {"letter": "有名 / 有名", "answers": ["you3ming2","yǒumíng","famous","well known"] },
    {"letter": "游戏 / 遊戲", "answers": ["you2xi4","yóuxì","game","play"] },
    {"letter": "遇到 / 遇到", "answers": ["yu4dao4","yùdào","to meet","to run into"] },
    {"letter": "愿意 / 願意", "answers": ["yuan4yi4","yuànyì","to be willing","be ready","to wish","to want"] },
    {"letter": "越 / 越", "answers": ["yue4","yuè","to exceed","to climb over","to surpass"] },
    {"letter": "月亮 / 月亮", "answers": ["yue4liang5","yuèliang","moon"] },
    {"letter": "云 / 雲", "answers": ["yun2","yún","cloud"] },
    {"letter": "站 / 站", "answers": ["zhan4","zhàn","station","stop","to stand","to stop","to halt"] },
    {"letter": "长 / 長", "answers": ["chang2","zhǎng","chief","head","to grow","to develop"] },
    {"letter": "照顾 / 照顧", "answers": ["zhao4gu5","zhàogù","to take care of","to look after"] },
    {"letter": "着急 / 着急", "answers": ["zhao2ji2","zháojí","to worry"] },
    {"letter": "照片 / 照片", "answers": ["zhao4pian4","zhàopiàn","photo","picture"] },
    {"letter": "照相机 / 照相機", "answers": ["zhao4xiang4ji1","zhàoxiàngjī","camera"] },
    {"letter": "只 / 只", "answers": ["zhi3","zhǐ","only","just","merely"] },
    {"letter": "种 / 種", "answers": ["zhong4","zhǒng","species","race","breed","type","kind","sort"] },
    {"letter": "中间 / 中間", "answers": ["zhong1jian1","zhōngjiān","between","in the middle","mid"] },
    {"letter": "重要 / 重要", "answers": ["zhong4yao4","zhòngyào","important"] },
    {"letter": "终于 / 終於", "answers": ["zhong1yu2","zhōngyú","at last","finally","eventually"] },
    {"letter": "周末 / 周末", "answers": ["zhou1mo4","zhōumò","weekend"] },
    {"letter": "祝 / 祝", "answers": ["zhu4","zhù","to wish","to express good wishes"] },
    {"letter": "主要 / 主要", "answers": ["zhu3yao4","zhǔyào","main","principal","major"] },
    {"letter": "注意 / 注意", "answers": ["zhu4yi4","zhùyì","to pay attention to"] },
    {"letter": "字典 / 字典", "answers": ["zi4dian3","zìdiǎn","dictionary","character book"] },
    {"letter": "自己 / 自己", "answers": ["zi4ji3","zìjǐ","oneself","self"] },
    {"letter": "总是 / 總是", "answers": ["zong3shi4","zǒngshì","always"] },
    {"letter": "最近 / 最近", "answers": ["zui4jin4","zuìjìn","recently","lately","soon"] },
    {"letter": "作业 / 作業", "answers": ["zuo4ye4","zuòyè","homework","task","work"] },
    {"letter": "作用 / 作用", "answers": ["zuo4yong4","zuòyòng","action","function","impact","effect","to affect"] },
  ]
};

module.exports = CHINESE3;