const CYRBALKAN = {
	"footer": "Write the Latin transliteration of the given Balkan Cyrillic letter.",
	"sets": [
    { "letter": "А а", "answers": ["a"] },
    { "letter": "Б б", "answers": ["b"] },
    { "letter": "В в", "answers": ["v"] },
    { "letter": "Г г", "answers": ["g"] },
    { "letter": "Д д", "answers": ["d"] },
    { "letter": "Ђ ђ (SR/MN)", "answers": ["đ", "dj", "d'", "dy"] },
    { "letter": "Е е", "answers": ["e"] },
    { "letter": "Ж ж", "answers": ["ž", "zh"] },
    { "letter": "З з", "answers": ["z"] },
    { "letter": "И и", "answers": ["i"] },
    { "letter": "Ј ј (SR/MN/MK)", "answers": ["j", "y"] },
    { "letter": "К к", "answers": ["k"] },
    { "letter": "Л л", "answers": ["l"] },
    { "letter": "Љ љ (SR/MN/MK)", "answers": ["lj", "l'", "ly"] },
    { "letter": "М м", "answers": ["m"] },
    { "letter": "Н н", "answers": ["n"] },
    { "letter": "Њ њ (SR/MN/MK)", "answers": ["nj", "n'", "ny"] },
    { "letter": "О о", "answers": ["o"] },
    { "letter": "П п", "answers": ["p"] },
    { "letter": "Р р", "answers": ["r"] },
    { "letter": "С с", "answers": ["s"] },
    { "letter": "Т т", "answers": ["t"] },
    { "letter": "Ћ ћ (SR/MN)", "answers": ["ć", "ch'", "t'", "ty"] },
    { "letter": "У у", "answers": ["u"] },
    { "letter": "Ф ф", "answers": ["f"] },
    { "letter": "Х х", "answers": ["h"] },
    { "letter": "Ц ц", "answers": ["c", "ts"] },
    { "letter": "Ч ч", "answers": ["č", "ch"] },
    { "letter": "Џ џ (SR/MN/MK)", "answers": ["dž", "j", "dzh"] },
    { "letter": "Ш ш", "answers": ["š", "sh"] },
    { "letter": "З́ з́ (MN)", "answers": ["ź", "z'", "zy", "zj"] },
    { "letter": "С́ с́ (MN)", "answers": ["ś", "s'", "sy", "sj"] },
    { "letter": "Ѓ ѓ (MK)", "answers": ["ǵ", "gj", "g'", "gy", "đ"] },
    { "letter": "Ѕ ѕ (MK)", "answers": ["dz"] },
    { "letter": "Ќ ќ (MK)", "answers": ["ḱ", "kj", "k'", "ky", "ć"] },
    { "letter": "Й й (BG)", "answers": ["y", "j"] },
    { "letter": "Щ щ (BG)", "answers": ["sht"] },
    { "letter": "Ъ ъ (BG)", "answers": ["a", "a'", "schwa"] },
    { "letter": "Ь ь (BG)", "answers": ["y", "'"] },
    { "letter": "Ю ю (BG)", "answers": ["yu", "iu"] },
    { "letter": "Я я (BG)", "answers": ["ya", "ia"] },
  ]
};

module.exports = CYRBALKAN;