const HINDI = {
	"footer": "Write the Latin transliteration of the given Devanagari letter.",
	"sets": [
    { "letter": "अ, प", "answers": ["a"] },
    { "letter": "इ, पि", "answers": ["i"] },
    { "letter": "उ, पु", "answers": ["u"] },
    { "letter": "ऋ, पृ", "answers": ["r", "ṛ"] },
    { "letter": "ऌ, पॢ", "answers": ["l", "ḷ"] },
    { "letter": "ए, पे", "answers": ["e"] },
    { "letter": "ओ, पो", "answers": ["o"] },
    { "letter": "अं, पं", "answers": ["a'", "aṃ"] },
    { "letter": "ॲ/ऍ, पॅ", "answers": ["ae", "ê"] },
    { "letter": "आ, पा", "answers": ["aa", "ā"] },
    { "letter": "ई, पी", "answers": ["ii", "ī"] },
    { "letter": "ऊ, पू", "answers": ["uu", "ū"] },
    { "letter": "ॠ, पॄ", "answers": ["ru", "ṝ"] },
    { "letter": "ॡ, पॣ", "answers": ["lu", "ḹ"] },
    { "letter": "ऐ, पै", "answers": ["e"] },
    { "letter": "औ, पौ", "answers": ["au'"] },
    { "letter": "अः, पः", "answers": ["aa", "aḥ"] },
    { "letter": "ऑ, पॉ", "answers": ["o", "ô"] },
    { "letter": "क", "answers": ["k"] },
    { "letter": "च", "answers": ["ch"] },
    { "letter": "ट", "answers": ["t", "ṭ"] },
    { "letter": "त", "answers": ["t"] },
    { "letter": "प", "answers": ["p"] },
    { "letter": "ख", "answers": ["kh"] },
    { "letter": "छ", "answers": ["ch'"] },
    { "letter": "ठ", "answers": ["th","ṭh"] },
    { "letter": "थ", "answers": ["th"] },
    { "letter": "फ", "answers": ["ph"] },
    { "letter": "ग", "answers": ["g"] },
    { "letter": "ज", "answers": ["j"] },
    { "letter": "ड", "answers": ["d", "ḍ"] },
    { "letter": "द", "answers": ["d"] },
    { "letter": "ब", "answers": ["b"] },
    { "letter": "घ", "answers": ["gh"] },
    { "letter": "झ", "answers": ["jh"] },
    { "letter": "ढ", "answers": ["dh", "ḍh"] },
    { "letter": "ध", "answers": ["dh"] },
    { "letter": "भ", "answers": ["bh"] },
    { "letter": "ङ", "answers": ["ng", "ṅ"] },
    { "letter": "ञ", "answers": ["n'", "ñ", "ny"] },
    { "letter": "ण", "answers": ["n", "ṇ"] },
    { "letter": "न", "answers": ["n"] },
    { "letter": "म", "answers": ["m"] },
    { "letter": "य", "answers": ["y"] },
    { "letter": "र", "answers": ["r"] },
    { "letter": "ल", "answers": ["l"] },
    { "letter": "व", "answers": ["v"] },
    { "letter": "श", "answers": ["sh", "ś"] },
    { "letter": "ष", "answers": ["sh", "ṣ"] },
    { "letter": "स", "answers": ["s"] },
    { "letter": "ह", "answers": ["h"] },
  ]
};

module.exports = HINDI;