const JPAREACODES = {
	"footer": "Write the Japanese prefecture which has this area code.",
	"sets": [
    { "letter": "011", "answers": ["Hokkaido"] },
    { "letter": "012", "answers": ["Hokkaido"] },
    { "letter": "013", "answers": ["Hokkaido"] },
    { "letter": "014", "answers": ["Hokkaido"] },
    { "letter": "015", "answers": ["Hokkaido"] },
    { "letter": "016", "answers": ["Hokkaido"] },
    { "letter": "017", "answers": ["Aomori"] },
    { "letter": "018", "answers": ["Akita"] },
    { "letter": "019", "answers": ["Iwate"] },
    { "letter": "023", "answers": ["Yamagata"] },
    { "letter": "022", "answers": ["Miyagi"] },
    { "letter": "024", "answers": ["Fukushima"] },
    { "letter": "025", "answers": ["Niigata"] },
    { "letter": "026", "answers": ["Nagano"] },
    { "letter": "027", "answers": ["Gunma"] },
    { "letter": "028", "answers": ["Tochigi"] },
    { "letter": "029", "answers": ["Ibaraki"] },
    { "letter": "03", "answers": ["Tokyo"] },
    { "letter": "042", "answers": ["Tokyo"] },
    { "letter": "043", "answers": ["Chiba"] },
    { "letter": "047", "answers": ["Chiba"] },
    { "letter": "048", "answers": ["Saitama"] },
    { "letter": "049", "answers": ["Saitama", "Tokyo Islands"] },
    { "letter": "044", "answers": ["Kanagawa"] },
    { "letter": "045", "answers": ["Kanagawa"] },
    { "letter": "046", "answers": ["Kanagawa"] },
    { "letter": "055", "answers": ["Yamanashi", "Shizuoka"] },
    { "letter": "054", "answers": ["Shizuoka"] },
    { "letter": "053", "answers": ["Shizuoka", "Aichi"] },
    { "letter": "056", "answers": ["Aichi"] },
    { "letter": "052", "answers": ["Aichi"] },
    { "letter": "057", "answers": ["Gifu"] },
    { "letter": "058", "answers": ["Gifu"] },
    { "letter": "059", "answers": ["Mie"] },
    { "letter": "076", "answers": ["Ishikawa", "Toyama"] },
    { "letter": "077", "answers": ["Fukui", "Kyoto", "Shiga"] },
    { "letter": "074", "answers": ["Nara", "Shiga"] },
    { "letter": "073", "answers": ["Wakayama"] },
    { "letter": "075", "answers": ["Kyoto"] },
    { "letter": "06", "answers": ["Osaka"] },
    { "letter": "072", "answers": ["Osaka"] },
    { "letter": "078", "answers": ["Hyogo"] },
    { "letter": "079", "answers": ["Hyogo"] },
    { "letter": "086", "answers": ["Okayama"] },
    { "letter": "085", "answers": ["Tottori", "Shimane"] },
    { "letter": "084", "answers": ["Hiroshima"] },
    { "letter": "082", "answers": ["Hiroshima", "Yamaguchi"] },
    { "letter": "083", "answers": ["Yamaguchi"] },
    { "letter": "087", "answers": ["Kagawa"] },
    { "letter": "088", "answers": ["Tokushima", "Kochi"] },
    { "letter": "089", "answers": ["Ehime"] },
    { "letter": "093", "answers": ["Fukuoka"] },
    { "letter": "094", "answers": ["Fukuoka"] },
    { "letter": "092", "answers": ["Fukuoka", "Iki Island", "Tsushima Island"] },
    { "letter": "095", "answers": ["Nagasaki", "Saga"] },
    { "letter": "096", "answers": ["Kumamoto"] },
    { "letter": "097", "answers": ["Oita"] },
    { "letter": "098", "answers": ["Miyazaki", "Okinawa"] },
    { "letter": "099", "answers": ["Kagoshima"] },
  ]
};

module.exports = JPAREACODES;