const KABUPATENS = {
	"footer": "Write the Indonesian province the given kabupaten is in.",
	"sets": [
    { "letter": "Aceh Barat", "answers": ["Aceh", "NAD"] },
    { "letter": "Aceh Barat Daya", "answers": ["Aceh", "NAD"] },
    { "letter": "Aceh Besar", "answers": ["Aceh", "NAD"] },
    { "letter": "Aceh Jaya", "answers": ["Aceh", "NAD"] },
    { "letter": "Aceh Selatan", "answers": ["Aceh", "NAD"] },
    { "letter": "Aceh Singkil", "answers": ["Aceh", "NAD"] },
    { "letter": "Aceh Tamiang", "answers": ["Aceh", "NAD"] },
    { "letter": "Aceh Tengah", "answers": ["Aceh", "NAD"] },
    { "letter": "Aceh Tenggara", "answers": ["Aceh", "NAD"] },
    { "letter": "Aceh Timur", "answers": ["Aceh", "NAD"] },
    { "letter": "Aceh Utara", "answers": ["Aceh", "NAD"] },
    { "letter": "Kota Banda Aceh", "answers": ["Aceh", "NAD"] },
    { "letter": "Bener Meriah", "answers": ["Aceh", "NAD"] },
    { "letter": "Bireuen", "answers": ["Aceh", "NAD"] },
    { "letter": "Gayo Lues", "answers": ["Aceh", "NAD"] },
    { "letter": "Kota Langsa", "answers": ["Aceh", "NAD"] },
    { "letter": "Kota Lhokseumawe", "answers": ["Aceh", "NAD"] },
    { "letter": "Nagan Raya", "answers": ["Aceh", "NAD"] },
    { "letter": "Pidie", "answers": ["Aceh", "NAD"] },
    { "letter": "Pidie Jaya", "answers": ["Aceh", "NAD"] },
    { "letter": "Kota Sabang", "answers": ["Aceh", "NAD"] },
    { "letter": "Simeulue", "answers": ["Aceh", "NAD"] },
    { "letter": "Kota Subulussalam", "answers": ["Aceh", "NAD"] },
    { "letter": "Badung", "answers": ["Bali"] },
    { "letter": "Bangli", "answers": ["Bali"] },
    { "letter": "Buleleng", "answers": ["Bali"] },
    { "letter": "Kota Denpasar", "answers": ["Bali"] },
    { "letter": "Gianyar", "answers": ["Bali"] },
    { "letter": "Jembrana", "answers": ["Bali"] },
    { "letter": "Karangasem", "answers": ["Bali"] },
    { "letter": "Klungkung", "answers": ["Bali"] },
    { "letter": "Tabanan", "answers": ["Bali"] },
    { "letter": "Kota Cilegon", "answers": ["Banten"] },
    { "letter": "Lebak", "answers": ["Banten"] },
    { "letter": "Pandeglang", "answers": ["Banten"] },
    { "letter": "Kota Serang", "answers": ["Banten"] },
    { "letter": "Serang", "answers": ["Banten"] },
    { "letter": "Kota Tangerang", "answers": ["Banten"] },
    { "letter": "Tangerang", "answers": ["Banten"] },
    { "letter": "Kota Tangerang Selatan", "answers": ["Banten"] },
    { "letter": "Kota Bengkulu", "answers": ["Bengkulu"] },
    { "letter": "Bengkulu Selatan", "answers": ["Bengkulu"] },
    { "letter": "Bengkulu Tengah", "answers": ["Bengkulu"] },
    { "letter": "Bengkulu Utara", "answers": ["Bengkulu"] },
    { "letter": "Kaur", "answers": ["Bengkulu"] },
    { "letter": "Kepahiang", "answers": ["Bengkulu"] },
    { "letter": "Lebong", "answers": ["Bengkulu"] },
    { "letter": "Muko Muko", "answers": ["Bengkulu"] },
    { "letter": "Rejang Lebong", "answers": ["Bengkulu"] },
    { "letter": "Seluma", "answers": ["Bengkulu"] },
    { "letter": "Bantul", "answers": ["Yogyakarta", "DI Yogyakarta"] },
    { "letter": "Gunung Kidul", "answers": ["Yogyakarta", "DI Yogyakarta"] },
    { "letter": "Kulon Progo", "answers": ["Yogyakarta", "DI Yogyakarta"] },
    { "letter": "Sleman", "answers": ["Yogyakarta", "DI Yogyakarta"] },
    { "letter": "Kota Yogyakarta", "answers": ["Yogyakarta", "DI Yogyakarta"] },
    { "letter": "Kota Jakarta Barat", "answers": ["Jakarta", "DKI Jakarta"] },
    { "letter": "Kota Jakarta Pusat", "answers": ["Jakarta", "DKI Jakarta"] },
    { "letter": "Kota Jakarta Selatan", "answers": ["Jakarta", "DKI Jakarta"] },
    { "letter": "Kota Jakarta Timur", "answers": ["Jakarta", "DKI Jakarta"] },
    { "letter": "Kota Jakarta Utara", "answers": ["Jakarta", "DKI Jakarta"] },
    { "letter": "Kepulauan Seribu", "answers": ["Jakarta", "DKI Jakarta"] },
    { "letter": "Boalemo", "answers": ["Gorontalo"] },
    { "letter": "Bone Bolango", "answers": ["Gorontalo"] },
    { "letter": "Gorontalo", "answers": ["Gorontalo"] },
    { "letter": "Kota Gorontalo", "answers": ["Gorontalo"] },
    { "letter": "Gorontalo Utara", "answers": ["Gorontalo"] },
    { "letter": "Pohuwato", "answers": ["Gorontalo"] },
    { "letter": "Batang Hari", "answers": ["Jambi"] },
    { "letter": "Bungo", "answers": ["Jambi"] },
    { "letter": "Kota Jambi", "answers": ["Jambi"] },
    { "letter": "Kerinci", "answers": ["Jambi"] },
    { "letter": "Merangin", "answers": ["Jambi"] },
    { "letter": "Muaro Jambi", "answers": ["Jambi"] },
    { "letter": "Sarolangun", "answers": ["Jambi"] },
    { "letter": "Kota Sungaipenuh", "answers": ["Jambi"] },
    { "letter": "Tanjung Jabung Barat", "answers": ["Jambi"] },
    { "letter": "Tanjung Jabung Timur", "answers": ["Jambi"] },
    { "letter": "Tebo", "answers": ["Jambi"] },
    { "letter": "Kota Bandung", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Bandung", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Bandung Barat", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Kota Banjar", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Kota Bekasi", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Bekasi", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Bogor", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Kota Bogor", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Ciamis", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Cianjur", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Kota Cimahi", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Kota Cirebon", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Cirebon", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Kota Depok", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Garut", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Indramayu", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Karawang", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Kuningan", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Majalengka", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Pangandaran", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Purwakarta", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Subang", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Kota Sukabumi", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Sukabumi", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Sumedang", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Kota Tasikmalaya", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Tasikmalaya", "answers": ["Jawa Barat", "West Java"] },
    { "letter": "Banjarnegara", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Banyumas", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Batang", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Blora", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Boyolali", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Brebes", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Cilacap", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Demak", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Grobogan", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Jepara", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Karanganyar", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Kebumen", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Kendal", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Klaten", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Kudus", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Magelang", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Kota Magelang", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Pati", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Pekalongan", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Kota Pekalongan", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Pemalang", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Purbalingga", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Purworejo", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Rembang", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Kota Salatiga", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Semarang", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Kota Semarang", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Sragen", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Sukoharjo", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Kota Surakarta", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Tegal", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Kota Tegal", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Temanggung", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Wonogiri", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Wonosobo", "answers": ["Jawa Tengah", "Central Java"] },
    { "letter": "Bangkalan", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Banyuwangi", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Kota Batu", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Blitar", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Kota Blitar", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Bojonegoro", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Bondowoso", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Gresik", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Jember", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Jombang", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Kediri", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Kota Kediri", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Lamongan", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Lumajang", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Madiun", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Kota Madiun", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Magetan", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Malang", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Kota Malang", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Mojokerto", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Kota Mojokerto", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Nganjuk", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Ngawi", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Pacitan", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Pamekasan", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Pasuruan", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Kota Pasuruan", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Ponorogo", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Probolinggo", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Kota Probolinggo", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Sampang", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Sidoarjo", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Situbondo", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Sumenep", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Kota Surabaya", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Trenggalek", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Tuban", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Tulungagung", "answers": ["Jawa Timur", "East Java"] },
    { "letter": "Bengkayang", "answers": ["Kalimantan Barat", "West Kalimantan"] },
    { "letter": "Kapuas Hulu", "answers": ["Kalimantan Barat", "West Kalimantan"] },
    { "letter": "Kayong Utara", "answers": ["Kalimantan Barat", "West Kalimantan"] },
    { "letter": "Ketapang", "answers": ["Kalimantan Barat", "West Kalimantan"] },
    { "letter": "Kubu Raya", "answers": ["Kalimantan Barat", "West Kalimantan"] },
    { "letter": "Landak", "answers": ["Kalimantan Barat", "West Kalimantan"] },
    { "letter": "Melawi", "answers": ["Kalimantan Barat", "West Kalimantan"] },
    { "letter": "Mempawah", "answers": ["Kalimantan Barat", "West Kalimantan"] },
    { "letter": "Kota Pontianak", "answers": ["Kalimantan Barat", "West Kalimantan"] },
    { "letter": "Sambas", "answers": ["Kalimantan Barat", "West Kalimantan"] },
    { "letter": "Sanggau", "answers": ["Kalimantan Barat", "West Kalimantan"] },
    { "letter": "Sekadau", "answers": ["Kalimantan Barat", "West Kalimantan"] },
    { "letter": "Kota Singkawang", "answers": ["Kalimantan Barat", "West Kalimantan"] },
    { "letter": "Sintang", "answers": ["Kalimantan Barat", "West Kalimantan"] },
    { "letter": "Balangan", "answers": ["Kalimantan Selatan", "South Kalimantan"] },
    { "letter": "Banjar", "answers": ["Kalimantan Selatan", "South Kalimantan"] },
    { "letter": "Kota Banjarbaru", "answers": ["Kalimantan Selatan", "South Kalimantan"] },
    { "letter": "Kota Banjarmasin", "answers": ["Kalimantan Selatan", "South Kalimantan"] },
    { "letter": "Barito Kuala", "answers": ["Kalimantan Selatan", "South Kalimantan"] },
    { "letter": "Hulu Sungai Selatan", "answers": ["Kalimantan Selatan", "South Kalimantan"] },
    { "letter": "Hulu Sungai Tengah", "answers": ["Kalimantan Selatan", "South Kalimantan"] },
    { "letter": "Hulu Sungai Utara", "answers": ["Kalimantan Selatan", "South Kalimantan"] },
    { "letter": "Kotabaru", "answers": ["Kalimantan Selatan", "South Kalimantan"] },
    { "letter": "Tabalong", "answers": ["Kalimantan Selatan", "South Kalimantan"] },
    { "letter": "Tanah Bumbu", "answers": ["Kalimantan Selatan", "South Kalimantan"] },
    { "letter": "Tanah Laut", "answers": ["Kalimantan Selatan", "South Kalimantan"] },
    { "letter": "Tapin", "answers": ["Kalimantan Selatan", "South Kalimantan"] },
    { "letter": "Barito Selatan", "answers": ["Kalimantan Tengah", "Central Kalimantan"] },
    { "letter": "Barito Timur", "answers": ["Kalimantan Tengah", "Central Kalimantan"] },
    { "letter": "Barito Utara", "answers": ["Kalimantan Tengah", "Central Kalimantan"] },
    { "letter": "Gunung Mas", "answers": ["Kalimantan Tengah", "Central Kalimantan"] },
    { "letter": "Kapuas", "answers": ["Kalimantan Tengah", "Central Kalimantan"] },
    { "letter": "Katingan", "answers": ["Kalimantan Tengah", "Central Kalimantan"] },
    { "letter": "Kotawaringin Barat", "answers": ["Kalimantan Tengah", "Central Kalimantan"] },
    { "letter": "Kotawaringin Timur", "answers": ["Kalimantan Tengah", "Central Kalimantan"] },
    { "letter": "Lamandau", "answers": ["Kalimantan Tengah", "Central Kalimantan"] },
    { "letter": "Murung Raya", "answers": ["Kalimantan Tengah", "Central Kalimantan"] },
    { "letter": "Kota Palangka Raya", "answers": ["Kalimantan Tengah", "Central Kalimantan"] },
    { "letter": "Pulang Pisau", "answers": ["Kalimantan Tengah", "Central Kalimantan"] },
    { "letter": "Seruyan", "answers": ["Kalimantan Tengah", "Central Kalimantan"] },
    { "letter": "Sukamara", "answers": ["Kalimantan Tengah", "Central Kalimantan"] },
    { "letter": "Kota Balikpapan", "answers": ["Kalimantan Timur", "East Kalimantan"] },
    { "letter": "Berau", "answers": ["Kalimantan Timur", "East Kalimantan"] },
    { "letter": "Kota Bontang", "answers": ["Kalimantan Timur", "East Kalimantan"] },
    { "letter": "Kutai Barat", "answers": ["Kalimantan Timur", "East Kalimantan"] },
    { "letter": "Kutai Kartanegara", "answers": ["Kalimantan Timur", "East Kalimantan"] },
    { "letter": "Kutai Timur", "answers": ["Kalimantan Timur", "East Kalimantan"] },
    { "letter": "Mahakam Ulu", "answers": ["Kalimantan Timur", "East Kalimantan"] },
    { "letter": "Paser", "answers": ["Kalimantan Timur", "East Kalimantan"] },
    { "letter": "Penajam Paser Utara", "answers": ["Kalimantan Timur", "East Kalimantan"] },
    { "letter": "Kota Samarinda", "answers": ["Kalimantan Timur", "East Kalimantan"] },
    { "letter": "Bulungan", "answers": ["Kalimantan Utara", "North Kalimantan"] },
    { "letter": "Malinau", "answers": ["Kalimantan Utara", "North Kalimantan"] },
    { "letter": "Nunukan", "answers": ["Kalimantan Utara", "North Kalimantan"] },
    { "letter": "Tana Tidung", "answers": ["Kalimantan Utara", "North Kalimantan"] },
    { "letter": "Kota Tarakan", "answers": ["Kalimantan Utara", "North Kalimantan"] },
    { "letter": "Bangka", "answers": ["Bangka Belitung Islands", "Kepulauan Bangka Belitung", "Bangka Belitung"] },
    { "letter": "Bangka Barat", "answers": ["Bangka Belitung Islands", "Kepulauan Bangka Belitung", "Bangka Belitung"] },
    { "letter": "Bangka Selatan", "answers": ["Bangka Belitung Islands", "Kepulauan Bangka Belitung", "Bangka Belitung"] },
    { "letter": "Bangka Tengah", "answers": ["Bangka Belitung Islands", "Kepulauan Bangka Belitung", "Bangka Belitung"] },
    { "letter": "Belitung", "answers": ["Bangka Belitung Islands", "Kepulauan Bangka Belitung", "Bangka Belitung"] },
    { "letter": "Belitung Timur", "answers": ["Bangka Belitung Islands", "Kepulauan Bangka Belitung", "Bangka Belitung"] },
    { "letter": "Kota Pangkal Pinang", "answers": ["Bangka Belitung Islands", "Kepulauan Bangka Belitung", "Bangka Belitung"] },
    { "letter": "Kota Batam", "answers": ["Riau Islands", "Kepulauan Riau"] },
    { "letter": "Bintan", "answers": ["Riau Islands", "Kepulauan Riau"] },
    { "letter": "Karimun", "answers": ["Riau Islands", "Kepulauan Riau"] },
    { "letter": "Kepulauan Anambas", "answers": ["Riau Islands", "Kepulauan Riau"] },
    { "letter": "Lingga", "answers": ["Riau Islands", "Kepulauan Riau"] },
    { "letter": "Natuna", "answers": ["Riau Islands", "Kepulauan Riau"] },
    { "letter": "Kota Tanjung Pinang", "answers": ["Riau Islands", "Kepulauan Riau"] },
    { "letter": "Kota Bandar Lampung", "answers": ["Lampung"] },
    { "letter": "Lampung Barat", "answers": ["Lampung"] },
    { "letter": "Lampung Selatan", "answers": ["Lampung"] },
    { "letter": "Lampung Tengah", "answers": ["Lampung"] },
    { "letter": "Lampung Timur", "answers": ["Lampung"] },
    { "letter": "Lampung Utara", "answers": ["Lampung"] },
    { "letter": "Mesuji", "answers": ["Lampung"] },
    { "letter": "Kota Metro", "answers": ["Lampung"] },
    { "letter": "Pesawaran", "answers": ["Lampung"] },
    { "letter": "Pesisir Barat", "answers": ["Lampung"] },
    { "letter": "Pringsewu", "answers": ["Lampung"] },
    { "letter": "Tanggamus", "answers": ["Lampung"] },
    { "letter": "Tulang Bawang", "answers": ["Lampung"] },
    { "letter": "Tulang Bawang Barat", "answers": ["Lampung"] },
    { "letter": "Way Kanan", "answers": ["Lampung"] },
    { "letter": "Kota Ambon", "answers": ["Maluku"] },
    { "letter": "Buru", "answers": ["Maluku"] },
    { "letter": "Buru Selatan", "answers": ["Maluku"] },
    { "letter": "Kepulauan Aru", "answers": ["Maluku"] },
    { "letter": "Kepulauan Tanimbar (Maluku Tenggara Barat)", "answers": ["Maluku"] },
    { "letter": "Maluku Barat Daya", "answers": ["Maluku"] },
    { "letter": "Maluku Tengah", "answers": ["Maluku"] },
    { "letter": "Maluku Tenggara", "answers": ["Maluku"] },
    { "letter": "Seram Bagian Barat", "answers": ["Maluku"] },
    { "letter": "Seram Bagian Timur", "answers": ["Maluku"] },
    { "letter": "Kota Tual", "answers": ["Maluku"] },
    { "letter": "Halmahera Barat", "answers": ["Maluku Utara", "North Maluku"] },
    { "letter": "Halmahera Selatan", "answers": ["Maluku Utara", "North Maluku"] },
    { "letter": "Halmahera Tengah", "answers": ["Maluku Utara", "North Maluku"] },
    { "letter": "Halmahera Timur", "answers": ["Maluku Utara", "North Maluku"] },
    { "letter": "Halmahera Utara", "answers": ["Maluku Utara", "North Maluku"] },
    { "letter": "Kepulauan Sula", "answers": ["Maluku Utara", "North Maluku"] },
    { "letter": "Pulau Morotai", "answers": ["Maluku Utara", "North Maluku"] },
    { "letter": "Pulau Taliabu", "answers": ["Maluku Utara", "North Maluku"] },
    { "letter": "Kota Ternate", "answers": ["Maluku Utara", "North Maluku"] },
    { "letter": "Kota Tidore Kepulauan", "answers": ["Maluku Utara", "North Maluku"] },
    { "letter": "Bima", "answers": ["Nusa Tenggara Barat", "NTB", "West Nusa Tenggara"] },
    { "letter": "Kota Bima", "answers": ["Nusa Tenggara Barat", "NTB", "West Nusa Tenggara"] },
    { "letter": "Dompu", "answers": ["Nusa Tenggara Barat", "NTB", "West Nusa Tenggara"] },
    { "letter": "Lombok Barat", "answers": ["Nusa Tenggara Barat", "NTB", "West Nusa Tenggara"] },
    { "letter": "Lombok Tengah", "answers": ["Nusa Tenggara Barat", "NTB", "West Nusa Tenggara"] },
    { "letter": "Lombok Timur", "answers": ["Nusa Tenggara Barat", "NTB", "West Nusa Tenggara"] },
    { "letter": "Lombok Utara", "answers": ["Nusa Tenggara Barat", "NTB", "West Nusa Tenggara"] },
    { "letter": "Kota Mataram", "answers": ["Nusa Tenggara Barat", "NTB", "West Nusa Tenggara"] },
    { "letter": "Sumbawa", "answers": ["Nusa Tenggara Barat", "NTB", "West Nusa Tenggara"] },
    { "letter": "Sumbawa Barat", "answers": ["Nusa Tenggara Barat", "NTB", "West Nusa Tenggara"] },
    { "letter": "Alor", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Belu", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Ende", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Flores Timur", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Kupang", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Kota Kupang", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Lembata", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Malaka", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Manggarai", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Manggarai Barat", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Manggarai Timur", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Nagekeo", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Ngada", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Rote Ndao", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Sabu Raijua", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Sikka", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Sumba Barat", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Sumba Barat Daya", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Sumba Tengah", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Sumba Timur", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Timor Tengah Selatan", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Timor Tengah Utara", "answers": ["Nusa Tenggara Timur", "NTT", "East Nusa Tenggara"] },
    { "letter": "Asmat", "answers": ["Papua"] },
    { "letter": "Biak Numfor", "answers": ["Papua"] },
    { "letter": "Boven Digoel", "answers": ["Papua"] },
    { "letter": "Deiyai", "answers": ["Papua"] },
    { "letter": "Dogiyai", "answers": ["Papua"] },
    { "letter": "Intan Jaya", "answers": ["Papua"] },
    { "letter": "Jayapura", "answers": ["Papua"] },
    { "letter": "Kota Jayapura", "answers": ["Papua"] },
    { "letter": "Jayawijaya", "answers": ["Papua"] },
    { "letter": "Keerom", "answers": ["Papua"] },
    { "letter": "Kepulauan Yapen", "answers": ["Papua"] },
    { "letter": "Lanny Jaya", "answers": ["Papua"] },
    { "letter": "Mamberamo Raya", "answers": ["Papua"] },
    { "letter": "Mamberamo Tengah", "answers": ["Papua"] },
    { "letter": "Mappi", "answers": ["Papua"] },
    { "letter": "Merauke", "answers": ["Papua"] },
    { "letter": "Mimika", "answers": ["Papua"] },
    { "letter": "Nabire", "answers": ["Papua"] },
    { "letter": "Nduga", "answers": ["Papua"] },
    { "letter": "Paniai", "answers": ["Papua"] },
    { "letter": "Pegunungan Bintang", "answers": ["Papua"] },
    { "letter": "Puncak", "answers": ["Papua"] },
    { "letter": "Puncak Jaya", "answers": ["Papua"] },
    { "letter": "Sarmi", "answers": ["Papua"] },
    { "letter": "Supiori", "answers": ["Papua"] },
    { "letter": "Tolikara", "answers": ["Papua"] },
    { "letter": "Waropen", "answers": ["Papua"] },
    { "letter": "Yahukimo", "answers": ["Papua"] },
    { "letter": "Yalimo", "answers": ["Papua"] },
    { "letter": "Fakfak", "answers": ["Papua Barat", "West Papua"] },
    { "letter": "Kaimana", "answers": ["Papua Barat", "West Papua"] },
    { "letter": "Manokwari", "answers": ["Papua Barat", "West Papua"] },
    { "letter": "Manokwari Selatan", "answers": ["Papua Barat", "West Papua"] },
    { "letter": "Maybrat", "answers": ["Papua Barat", "West Papua"] },
    { "letter": "Pegunungan Arfak", "answers": ["Papua Barat", "West Papua"] },
    { "letter": "Raja Ampat", "answers": ["Papua Barat", "West Papua"] },
    { "letter": "Sorong", "answers": ["Papua Barat", "West Papua"] },
    { "letter": "Kota Sorong", "answers": ["Papua Barat", "West Papua"] },
    { "letter": "Sorong Selatan", "answers": ["Papua Barat", "West Papua"] },
    { "letter": "Tambrauw", "answers": ["Papua Barat", "West Papua"] },
    { "letter": "Teluk Bintuni", "answers": ["Papua Barat", "West Papua"] },
    { "letter": "Teluk Wondama", "answers": ["Papua Barat", "West Papua"] },
    { "letter": "Bengkalis", "answers": ["Riau"] },
    { "letter": "Kota Dumai", "answers": ["Riau"] },
    { "letter": "Indragiri Hilir", "answers": ["Riau"] },
    { "letter": "Indragiri Hulu", "answers": ["Riau"] },
    { "letter": "Kampar", "answers": ["Riau"] },
    { "letter": "Kepulauan Meranti", "answers": ["Riau"] },
    { "letter": "Kuantan Singingi", "answers": ["Riau"] },
    { "letter": "Kota Pekanbaru", "answers": ["Riau"] },
    { "letter": "Pelalawan", "answers": ["Riau"] },
    { "letter": "Rokan Hilir", "answers": ["Riau"] },
    { "letter": "Rokan Hulu", "answers": ["Riau"] },
    { "letter": "Siak", "answers": ["Riau"] },
    { "letter": "Majene", "answers": ["Sulawesi Barat", "West Sulawesi"] },
    { "letter": "Mamasa", "answers": ["Sulawesi Barat", "West Sulawesi"] },
    { "letter": "Mamuju", "answers": ["Sulawesi Barat", "West Sulawesi"] },
    { "letter": "Mamuju Tengah", "answers": ["Sulawesi Barat", "West Sulawesi"] },
    { "letter": "Pasangkayu (Mamuju Utara)", "answers": ["Sulawesi Barat", "West Sulawesi"] },
    { "letter": "Polewali Mandar", "answers": ["Sulawesi Barat", "West Sulawesi"] },
    { "letter": "Bantaeng", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Barru", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Bone", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Bulukumba", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Enrekang", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Gowa", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Jeneponto", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Kepulauan Selayar", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Luwu", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Luwu Timur", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Luwu Utara", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Kota Makassar", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Maros", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Kota Palopo", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Pangkajene Kepulauan", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Kota Parepare", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Pinrang", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Sidenreng Rappang", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Sinjai", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Soppeng", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Takalar", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Tana Toraja", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Toraja Utara", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Wajo", "answers": ["Sulawesi Selatan", "South Sulawesi"] },
    { "letter": "Banggai", "answers": ["Sulawesi Tengah", "Central Sulawesi"] },
    { "letter": "Banggai Kepulauan", "answers": ["Sulawesi Tengah", "Central Sulawesi"] },
    { "letter": "Banggai Laut", "answers": ["Sulawesi Tengah", "Central Sulawesi"] },
    { "letter": "Buol", "answers": ["Sulawesi Tengah", "Central Sulawesi"] },
    { "letter": "Donggala", "answers": ["Sulawesi Tengah", "Central Sulawesi"] },
    { "letter": "Morowali", "answers": ["Sulawesi Tengah", "Central Sulawesi"] },
    { "letter": "Morowali Utara", "answers": ["Sulawesi Tengah", "Central Sulawesi"] },
    { "letter": "Kota Palu", "answers": ["Sulawesi Tengah", "Central Sulawesi"] },
    { "letter": "Parigi Moutong", "answers": ["Sulawesi Tengah", "Central Sulawesi"] },
    { "letter": "Poso", "answers": ["Sulawesi Tengah", "Central Sulawesi"] },
    { "letter": "Sigi", "answers": ["Sulawesi Tengah", "Central Sulawesi"] },
    { "letter": "Tojo Una-Una", "answers": ["Sulawesi Tengah", "Central Sulawesi"] },
    { "letter": "Toli-Toli", "answers": ["Sulawesi Tengah", "Central Sulawesi"] },
    { "letter": "Kota Bau-Bau", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Bombana", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Buton", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Buton Selatan", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Buton Tengah", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Buton Utara", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Kota Kendari", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Kolaka", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Kolaka Timur", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Kolaka Utara", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Konawe", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Konawe Kepulauan", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Konawe Selatan", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Konawe Utara", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Muna", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Muna Barat", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Wakatobi", "answers": ["Sulawesi Tenggara", "Southeast Sulawesi"] },
    { "letter": "Kota Bitung", "answers": ["Sulawesi Utara", "North Sulawesi"] },
    { "letter": "Bolaang Mongondow", "answers": ["Sulawesi Utara", "North Sulawesi"] },
    { "letter": "Bolaang Mongondow Selatan", "answers": ["Sulawesi Utara", "North Sulawesi"] },
    { "letter": "Bolaang Mongondow Timur", "answers": ["Sulawesi Utara", "North Sulawesi"] },
    { "letter": "Bolaang Mongondow Utara", "answers": ["Sulawesi Utara", "North Sulawesi"] },
    { "letter": "Kepulauan Sangihe", "answers": ["Sulawesi Utara", "North Sulawesi"] },
    { "letter": "Kepulauan Siau Tagulandang Biaro (Sitaro)", "answers": ["Sulawesi Utara", "North Sulawesi"] },
    { "letter": "Kepulauan Talaud", "answers": ["Sulawesi Utara", "North Sulawesi"] },
    { "letter": "Kota Kotamobagu", "answers": ["Sulawesi Utara", "North Sulawesi"] },
    { "letter": "Kota Manado", "answers": ["Sulawesi Utara", "North Sulawesi"] },
    { "letter": "Minahasa", "answers": ["Sulawesi Utara", "North Sulawesi"] },
    { "letter": "Minahasa Selatan", "answers": ["Sulawesi Utara", "North Sulawesi"] },
    { "letter": "Minahasa Tenggara", "answers": ["Sulawesi Utara", "North Sulawesi"] },
    { "letter": "Minahasa Utara", "answers": ["Sulawesi Utara", "North Sulawesi"] },
    { "letter": "Kota Tomohon", "answers": ["Sulawesi Utara", "North Sulawesi"] },
    { "letter": "Agam", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Kota Bukittinggi", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Dharmasraya", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Kepulauan Mentawai", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Lima Puluh Kota", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Kota Padang", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Kota Padang Panjang", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Padang Pariaman", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Kota Pariaman", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Pasaman", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Pasaman Barat", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Kota Payakumbuh", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Pesisir Selatan", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Kota Sawah Lunto", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Sijunjung", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Solok", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Kota Solok", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Solok Selatan", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Tanah Datar", "answers": ["Sumatera Barat", "West Sumatra"] },
    { "letter": "Banyuasin", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Empat Lawang", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Lahat", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Kota Lubuk Linggau", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Muara Enim", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Musi Banyuasin", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Musi Rawas", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Musi Rawas Utara", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Ogan Ilir", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Ogan Komering Ilir", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Ogan Komering Ulu", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Ogan Komering Ulu Selatan", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Ogan Komering Ulu Timur", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Kota Pagar Alam", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Kota Palembang", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Penukal Abab Lematang Ilir", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Kota Prabumulih", "answers": ["Sumatera Selatan", "South Sumatra"] },
    { "letter": "Asahan", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Batu Bara", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Kota Binjai", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Dairi", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Deli Serdang", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Kota Gunungsitoli", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Humbang Hasundutan", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Karo", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Labuhanbatu", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Labuhanbatu Selatan", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Labuhanbatu Utara", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Langkat", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Mandailing Natal", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Kota Medan", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Nias", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Nias Barat", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Nias Selatan", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Nias Utara", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Padang Lawas", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Padang Lawas Utara", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Kota Padang Sidempuan", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Pakpak Bharat", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Kota Pematang Siantar", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Samosir", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Serdang Bedagai", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Kota Sibolga", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Simalungun", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Kota Tanjung Balai", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Tapanuli Selatan", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Tapanuli Tengah", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Tapanuli Utara", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Kota Tebing Tinggi", "answers": ["Sumatera Utara", "North Sumatra"] },
    { "letter": "Toba Samosir", "answers": ["Sumatera Utara", "North Sumatra"] },
  ]
};

module.exports = KABUPATENS;