const PREFECTURES = {
	"footer": "Write the English name of the given Japanese prefecture.",
	"sets": [
    { "letter": "愛知", "answers": ["Aichi"] },
    { "letter": "秋田", "answers": ["Akita"] },
    { "letter": "青森", "answers": ["Aomori"] },
    { "letter": "千葉", "answers": ["Chiba"] },
    { "letter": "愛媛", "answers": ["Ehime"] },
    { "letter": "福井", "answers": ["Fukui"] },
    { "letter": "福岡", "answers": ["Fukuoka"] },
    { "letter": "福島", "answers": ["Fukushima"] },
    { "letter": "岐阜", "answers": ["Gifu"] },
    { "letter": "群馬", "answers": ["Gunma"] },
    { "letter": "広島", "answers": ["Hiroshima"] },
    { "letter": "北海道", "answers": ["Hokkaido"] },
    { "letter": "兵庫", "answers": ["Hyogo"] },
    { "letter": "茨城", "answers": ["Ibaraki"] },
    { "letter": "石川", "answers": ["Ishikawa"] },
    { "letter": "岩手", "answers": ["Iwate"] },
    { "letter": "香川", "answers": ["Kagawa"] },
    { "letter": "鹿児島", "answers": ["Kagoshima"] },
    { "letter": "神奈川", "answers": ["Kanagawa"] },
    { "letter": "高知", "answers": ["Kochi"] },
    { "letter": "熊本", "answers": ["Kumamoto"] },
    { "letter": "京都", "answers": ["Kyoto"] },
    { "letter": "三重", "answers": ["Mie"] },
    { "letter": "宮城", "answers": ["Miyagi"] },
    { "letter": "宮崎", "answers": ["Miyazaki"] },
    { "letter": "長野", "answers": ["Nagano"] },
    { "letter": "長崎", "answers": ["Nagasaki"] },
    { "letter": "奈良", "answers": ["Nara"] },
    { "letter": "新潟", "answers": ["Niigata"] },
    { "letter": "大分", "answers": ["Oita"] },
    { "letter": "岡山", "answers": ["Okayama"] },
    { "letter": "沖縄", "answers": ["Okinawa"] },
    { "letter": "大阪", "answers": ["Osaka"] },
    { "letter": "佐賀", "answers": ["Saga"] },
    { "letter": "埼玉", "answers": ["Saitama"] },
    { "letter": "滋賀", "answers": ["Shiga"] },
    { "letter": "島根", "answers": ["Shimane"] },
    { "letter": "静岡", "answers": ["Shizuoka"] },
    { "letter": "栃木", "answers": ["Tochigi"] },
    { "letter": "徳島", "answers": ["Tokushima"] },
    { "letter": "東京", "answers": ["Tokyo"] },
    { "letter": "鳥取", "answers": ["Tottori"] },
    { "letter": "富山", "answers": ["Toyama"] },
    { "letter": "和歌山", "answers": ["Wakayama"] },
    { "letter": "山形", "answers": ["Yamagata"] },
    { "letter": "山口", "answers": ["Yamaguchi"] },
    { "letter": "山梨", "answers": ["Yamanashi"] },
  ]
};

module.exports = PREFECTURES;