const THPROVINCES = {
	"footer": "Write the English name of the given Thai province.",
	"sets": [
    { "letter": "เชียงราย", "answers": ["Chiang Rai"] },
    { "letter": "เชียงใหม่", "answers": ["Chiang Mai"] },
    { "letter": "น่าน", "answers": ["Nan"] },
    { "letter": "พะเยา", "answers": ["Phayao"] },
    { "letter": "แพร่", "answers": ["Phrae"] },
    { "letter": "แม่ฮ่องสอน", "answers": ["Mae Hong Son"] },
    { "letter": "ลำปาง", "answers": ["Lampang"] },
    { "letter": "ลำพูน", "answers": ["Lamphun"] },
    { "letter": "อุตรดิตถ์", "answers": ["Uttaradit"] },
    { "letter": "กาฬสินธุ์", "answers": ["Kalasin"] },
    { "letter": "ขอนแก่น", "answers": ["Khon Kaen"] },
    { "letter": "ชัยภูมิ", "answers": ["Chaiyaphum"] },
    { "letter": "นครพนม", "answers": ["Nakhon Phanom"] },
    { "letter": "นครราชสีมา", "answers": ["Nakhon Ratchasima"] },
    { "letter": "บึงกาฬ", "answers": ["Bueng Kan"] },
    { "letter": "บุรีรัมย์", "answers": ["Buri Ram"] },
    { "letter": "มหาสารคาม", "answers": ["Maha Sarakham"] },
    { "letter": "มุกดาหาร", "answers": ["Mukdahan"] },
    { "letter": "ยโสธร", "answers": ["Yasothon"] },
    { "letter": "ร้อยเอ็ด", "answers": ["Roi Et"] },
    { "letter": "เลย", "answers": ["Loei"] },
    { "letter": "ศรีสะเกษ", "answers": ["Si Sa Ket"] },
    { "letter": "สกลนคร", "answers": ["Sakon Nakhon"] },
    { "letter": "สุรินทร์", "answers": ["Surin"] },
    { "letter": "หนองคาย", "answers": ["Nong Khai"] },
    { "letter": "หนองบัวลำภู", "answers": ["Nong Bua Lam Phu"] },
    { "letter": "อุดรธานี", "answers": ["Udon Thani"] },
    { "letter": "อุบลราชธานี", "answers": ["Ubon Ratchathani"] },
    { "letter": "อำนาจเจริญ", "answers": ["Amnat Charoen"] },
    { "letter": "กรุงเทพมหานคร", "answers": ["Bangkok"] },
    { "letter": "กำแพงเพชร", "answers": ["Kamphaeng Phet"] },
    { "letter": "ชัยนาท", "answers": ["Chai Nat"] },
    { "letter": "นครนายก", "answers": ["Nakhon Nayok"] },
    { "letter": "นครปฐม", "answers": ["Nakhon Pathom"] },
    { "letter": "นครสวรรค์", "answers": ["Nakhon Sawan"] },
    { "letter": "นนทบุรี", "answers": ["Nonthaburi"] },
    { "letter": "ปทุมธานี", "answers": ["Pathum Thani"] },
    { "letter": "พระนครศรีอยุธยา", "answers": ["Phra Nakhon Si Ayutthaya"] },
    { "letter": "พิจิตร", "answers": ["Phichit"] },
    { "letter": "พิษณุโลก", "answers": ["Phitsanulok"] },
    { "letter": "เพชรบูรณ์", "answers": ["Phetchabun"] },
    { "letter": "ลพบุรี", "answers": ["Lop Buri"] },
    { "letter": "สมุทรปราการ", "answers": ["Samut Prakan"] },
    { "letter": "สมุทรสงคราม", "answers": ["Samut Songkhram"] },
    { "letter": "สมุทรสาคร", "answers": ["Samut Sakhon"] },
    { "letter": "สระบุรี", "answers": ["Saraburi"] },
    { "letter": "สิงห์บุรี", "answers": ["Sing Buri"] },
    { "letter": "สุโขทัย", "answers": ["Sukhothai"] },
    { "letter": "สุพรรณบุรี", "answers": ["Suphan Buri"] },
    { "letter": "อ่างทอง", "answers": ["Ang Thong"] },
    { "letter": "อุทัยธานี", "answers": ["Uthai Thani"] },
    { "letter": "จันทบุรี", "answers": ["Chanthaburi"] },
    { "letter": "ฉะเชิงเทรา", "answers": ["Chachoengsao"] },
    { "letter": "ชลบุรี", "answers": ["Chon Buri"] },
    { "letter": "ตราด", "answers": ["Trat"] },
    { "letter": "ปราจีนบุรี", "answers": ["Prachin Buri"] },
    { "letter": "ระยอง", "answers": ["Rayong"] },
    { "letter": "สระแก้ว", "answers": ["Sa Kaeo"] },
    { "letter": "กาญจนบุรี", "answers": ["Kanchanaburi"] },
    { "letter": "ตาก", "answers": ["Tak"] },
    { "letter": "ประจวบคีรีขันธ์", "answers": ["Prachuap Khiri Khan"] },
    { "letter": "เพชรบุรี", "answers": ["Phetchaburi"] },
    { "letter": "ราชบุรี", "answers": ["Ratchaburi"] },
    { "letter": "กระบี่", "answers": ["Krabi"] },
    { "letter": "ชุมพร", "answers": ["Chumphon"] },
    { "letter": "ตรัง", "answers": ["Trang"] },
    { "letter": "นครศรีธรรมราช", "answers": ["Nakhon Si Thammarat"] },
    { "letter": "นราธิวาส", "answers": ["Narathiwat"] },
    { "letter": "ปัตตานี", "answers": ["Pattani"] },
    { "letter": "พังงา", "answers": ["Phangnga"] },
    { "letter": "พัทลุง", "answers": ["Phatthalung"] },
    { "letter": "ภูเก็ต", "answers": ["Phuket"] },
    { "letter": "ยะลา", "answers": ["Yala"] },
    { "letter": "ระนอง", "answers": ["Ranong"] },
    { "letter": "สตูล", "answers": ["Satun"] },
    { "letter": "สงขลา", "answers": ["Songkhla"] },
    { "letter": "สุราษฎร์ธานี", "answers": ["Surat Thani"] },
  ]
};

module.exports = THPROVINCES;