const THPVABBR = {
	"footer": "Write the full Thai province name whose abbreviation this is.",
	"sets": [
    { "letter": "ชร", "answers": ["Chiang Rai"] },
    { "letter": "ชม", "answers": ["Chiang Mai"] },
    { "letter": "นน", "answers": ["Nan"] },
    { "letter": "พย", "answers": ["Phayao"] },
    { "letter": "พร", "answers": ["Phrae"] },
    { "letter": "มส", "answers": ["Mae Hong Son"] },
    { "letter": "ลป", "answers": ["Lampang"] },
    { "letter": "ลพ", "answers": ["Lamphun"] },
    { "letter": "อต", "answers": ["Uttaradit"] },
    { "letter": "กส", "answers": ["Kalasin"] },
    { "letter": "ขก", "answers": ["Khon Kaen"] },
    { "letter": "ชย", "answers": ["Chaiyaphum"] },
    { "letter": "นพ", "answers": ["Nakhon Phanom"] },
    { "letter": "นม", "answers": ["Nakhon Ratchasima"] },
    { "letter": "บก", "answers": ["Bueng Kan"] },
    { "letter": "บร", "answers": ["Buri Ram"] },
    { "letter": "มค", "answers": ["Maha Sarakham"] },
    { "letter": "มห", "answers": ["Mukdahan"] },
    { "letter": "ยส", "answers": ["Yasothon"] },
    { "letter": "รอ", "answers": ["Roi Et"] },
    { "letter": "ลย", "answers": ["Loei"] },
    { "letter": "ศก", "answers": ["Si Sa Ket"] },
    { "letter": "สน", "answers": ["Sakon Nakhon"] },
    { "letter": "สร", "answers": ["Surin"] },
    { "letter": "นค", "answers": ["Nong Khai"] },
    { "letter": "นภ", "answers": ["Nong Bua Lam Phu"] },
    { "letter": "อด", "answers": ["Udon Thani"] },
    { "letter": "อบ", "answers": ["Ubon Ratchathani"] },
    { "letter": "อจ", "answers": ["Amnat Charoen"] },
    { "letter": "กท", "answers": ["Bangkok"] },
    { "letter": "กพ", "answers": ["Kamphaeng Phet"] },
    { "letter": "ชน", "answers": ["Chai Nat"] },
    { "letter": "นย", "answers": ["Nakhon Nayok"] },
    { "letter": "นฐ", "answers": ["Nakhon Pathom"] },
    { "letter": "นว", "answers": ["Nakhon Sawan"] },
    { "letter": "นบ", "answers": ["Nonthaburi"] },
    { "letter": "ปท", "answers": ["Pathum Thani"] },
    { "letter": "อย", "answers": ["Phra Nakhon Si Ayutthaya"] },
    { "letter": "พจ", "answers": ["Phichit"] },
    { "letter": "พล", "answers": ["Phitsanulok"] },
    { "letter": "พช", "answers": ["Phetchabun"] },
    { "letter": "ลบ", "answers": ["Lop Buri"] },
    { "letter": "สป", "answers": ["Samut Prakan"] },
    { "letter": "สส", "answers": ["Samut Songkhram"] },
    { "letter": "สค", "answers": ["Samut Sakhon"] },
    { "letter": "สบ", "answers": ["Saraburi"] },
    { "letter": "สห", "answers": ["Sing Buri"] },
    { "letter": "สท", "answers": ["Sukhothai"] },
    { "letter": "สพ", "answers": ["Suphan Buri"] },
    { "letter": "อท", "answers": ["Ang Thong"] },
    { "letter": "อน", "answers": ["Uthai Thani"] },
    { "letter": "จบ", "answers": ["Chanthaburi"] },
    { "letter": "ฉช", "answers": ["Chachoengsao"] },
    { "letter": "ชบ", "answers": ["Chon Buri"] },
    { "letter": "ตร", "answers": ["Trat"] },
    { "letter": "ปจ", "answers": ["Prachin Buri"] },
    { "letter": "รย", "answers": ["Rayong"] },
    { "letter": "สก", "answers": ["Sa Kaeo"] },
    { "letter": "กจ", "answers": ["Kanchanaburi"] },
    { "letter": "ตก", "answers": ["Tak"] },
    { "letter": "ปข", "answers": ["Prachuap Khiri Khan"] },
    { "letter": "พบ", "answers": ["Phetchaburi"] },
    { "letter": "รบ", "answers": ["Ratchaburi"] },
    { "letter": "กบ", "answers": ["Krabi"] },
    { "letter": "ชพ", "answers": ["Chumphon"] },
    { "letter": "ตง", "answers": ["Trang"] },
    { "letter": "นศ", "answers": ["Nakhon Si Thammarat"] },
    { "letter": "นธ", "answers": ["Narathiwat"] },
    { "letter": "ปน", "answers": ["Pattani"] },
    { "letter": "พง", "answers": ["Phangnga"] },
    { "letter": "พท", "answers": ["Phatthalung"] },
    { "letter": "ภก", "answers": ["Phuket"] },
    { "letter": "ยล", "answers": ["Yala"] },
    { "letter": "รน", "answers": ["Ranong"] },
    { "letter": "สต", "answers": ["Satun"] },
    { "letter": "สข", "answers": ["Songkhla"] },
    { "letter": "สฎ", "answers": ["Surat Thani"] },
  ]
};

module.exports = THPVABBR;