const THVOWELS = {
	"footer": "Write the Latin transliteration of the given Thai vowel letter.",
	"sets": [
    { "letter": "◌ะ, ◌, ◌ั◌", "answers": ["a"] },
    { "letter": "◌ิ, ◌ิ◌", "answers": ["i"] },
    { "letter": "◌ึ, ◌ึ◌", "answers": ["ue"] },
    { "letter": "◌ุ, ◌ุ◌", "answers": ["u"] },
    { "letter": "เ◌ะ, เ◌็◌", "answers": ["e"] },
    { "letter": "แ◌ะ, แ◌็◌", "answers": ["ae"] },
    { "letter": "โ◌ะ, ◌◌", "answers": ["o"] },
    { "letter": "เ◌าะ, ◌็อ◌", "answers": ["o"] },
    { "letter": "เ◌อะ", "answers": ["oe"] },
    { "letter": "เ◌ียะ", "answers": ["ia"] },
    { "letter": "เ◌ือะ", "answers": ["uea"] },
    { "letter": "◌ัวะ", "answers": ["ua"] },
    { "letter": "◌ิว", "answers": ["io"] },
    { "letter": "เ◌็ว", "answers": ["eo"] },
    { "letter": "เ◌า", "answers": ["ao"] },
    { "letter": "◌ัย", "answers": ["ai"] },
    { "letter": "ใ◌, ไ◌, ไ◌ย", "answers": ["ai"] },
    { "letter": "◌็อย", "answers": ["oi"] },
    { "letter": "◌ุย", "answers": ["ui"] },
    { "letter": "ำ", "answers": ["am"] },
    { "letter": "ฤ", "answers": ["rue, ri, roe"] },
    { "letter": "ฦ", "answers": ["lue"] },
    { "letter": "◌า, ◌า◌", "answers": ["a"] },
    { "letter": "◌ี, ◌ี◌", "answers": ["i"] },
    { "letter": "◌ือ, ◌ื◌", "answers": ["ue"] },
    { "letter": "◌ู, ◌ู◌", "answers": ["u"] },
    { "letter": "เ◌, เ◌◌", "answers": ["e"] },
    { "letter": "แ◌, แ◌◌", "answers": ["ae"] },
    { "letter": "โ◌, โ◌◌", "answers": ["o"] },
    { "letter": "◌อ, ◌อ◌, ◌◌, ◌็", "answers": ["o"] },
    { "letter": "เ◌อ, เ◌ิ◌, เ◌อ◌", "answers": ["oe"] },
    { "letter": "เ◌ีย, เ◌ีย◌", "answers": ["ia"] },
    { "letter": "เ◌ือ, เ◌ือ◌", "answers": ["uea"] },
    { "letter": "◌ัว, ◌ว◌", "answers": ["ua"] },
    { "letter": "เ◌ว", "answers": ["eo"] },
    { "letter": "แ◌ว", "answers": ["aeo"] },
    { "letter": "◌าว", "answers": ["ao"] },
    { "letter": "เ◌ียว", "answers": ["iao"] },
    { "letter": "◌าย", "answers": ["ai"] },
    { "letter": "◌อย", "answers": ["oi"] },
    { "letter": "โ◌ย", "answers": ["oi"] },
    { "letter": "เ◌ย", "answers": ["oei"] },
    { "letter": "◌วย", "answers": ["uai"] },
    { "letter": "เ◌ือย", "answers": ["ueai"] },
    { "letter": "ฤๅ", "answers": ["rue"] },
    { "letter": "ฦๅ", "answers": ["lue"] },
  ]
};

module.exports = THVOWELS;